// ═══════════════════════════════════════════════════════════════════════════
// CropsNH Data — verified against GTNewHorizons/CropsNH v2.0.76 decompiled jar
// 178 crops, 172 mutation recipes, 5 direct pool registrations
// Zero discrepancies vs decompiled source as of this build.
// ═══════════════════════════════════════════════════════════════════════════

const SOILS=[
  {id:'farmland', name:'Farmland', note:'Tilled dirt/enchanted earth/Ztones', blocks:'Farmland, Enchanted Earth, Ztones Garden Soil, Fertilized Dirt'},
  {id:'dirtGrass', name:'Dirt / Grass', note:'Dirt, grass, podzol', blocks:'Dirt, Grass, Mycelium variants'},
  {id:'stone', name:'Stone', note:'Stone, cobble, stonebrick, ore blocks', blocks:'Stone, Cobblestone, Stone Brick, Mossy Cobble + Chisel variants'},
  {id:'sand', name:'Sand', note:'Sand, sandstone', blocks:'Sand, Sandstone'},
  {id:'soulsand', name:'Soul Sand', note:'Nether Wart, Gaia Wart (+snow above)', blocks:'Soul Sand'},
  {id:'sugarcane', name:'Sugarcane Soil', note:'Sand OR dirt/grass compound', blocks:'Sand, Sandstone, Dirt, Grass (CompoundSoilList)'},
  {id:'netherrack', name:'Netherrack', note:'Netherrack + Chisel/TiC variants', blocks:'Netherrack, TiC Nether Bricks, Chisel Netherrack'},
  {id:'graveyard', name:'Graveyard Soil', note:'TiC Graveyard Soil (meta 3)', blocks:'TiC CraftedSoil:3 (Graveyard Soil)'},
  {id:'slimy', name:'Slimy Soil', note:'TiC slimy muds/slime dirt', blocks:'TiC Green/Blue Slimy Mud, Slime Dirt, Slime Grass'},
  {id:'slimyDirt', name:'Slimy Dirt/Grass', note:'Dirt/Grass OR Slimy compound (Bonsai Slimy only)', blocks:'Dirt, Grass + all Slimy Soil variants (CompoundSoilList)'},
  {id:'end', name:'End Stone', note:'End stone + Botania/Chisel variants', blocks:'End Stone, Botania End Stone Brick, Chisel End Stone'},
  {id:'mycelium', name:'Mycelium', note:'Mushrooms', blocks:'Mycelium'},
  {id:'thaumLogs', name:'Thaumcraft Logs', note:'Greatwood / Silverwood logs', blocks:'Greatwood Log, Silverwood Log'},
  {id:'brick', name:'Brick', note:'Brick blocks', blocks:'Brick Block, ExtraUtils Color Brick, ThaumicBases Old Brick'},
  {id:'gravel', name:'Gravel', note:'Gravel blocks', blocks:'Gravel'},
  {id:'oilSands', name:'Oil Sands', note:'GT Oil Sands ores', blocks:'GT Oil Sands ore variants'},
  {id:'oil', name:'Oil Soil', note:'Sand/Gravel/Soulsand/OilSands compound', blocks:'Sand, Gravel, Soul Sand, Oil Sands (OilBerry compound)'},
  {id:'mushroom', name:'Mushroom Soil', note:'Stone/Dirt/Mycelium compound', blocks:'Stone, Dirt/Grass, Mycelium'},
  {id:'netherMushroom', name:'Nether Mushroom Soil', note:'Mushroom + Netherrack compound', blocks:'Stone, Dirt, Mycelium, Netherrack'},
];

const CROPS=[
  {id:'Wheat',name:'Wheat',tier:1,soil:'farmland',pools:['EDIBLE','WHEAT','YELLOW'],altSeed:true,liked:['PLAINS','LUSH']},
  {id:'Carrot',name:'Carrot',tier:2,soil:'farmland',pools:[],altSeed:true,liked:['PLAINS','HOT','SANDY']},
  {id:'Potato',name:'Potato',tier:1,soil:'farmland',pools:['EDIBLE','ROOT','YELLOW'],altSeed:true,liked:['PLAINS','COLD']},
  {id:'Melon',name:'Melon',tier:2,soil:'farmland',pools:['EDIBLE','GREEN','HEALING','POTION_INGREDIENT','STEM'],altSeed:true,liked:['WET','LUSH']},
  {id:'Pumpkin',name:'Pumpkin',tier:2,soil:'farmland',pools:['EDIBLE','ORANGE','STEM'],altSeed:true,liked:['PLAINS','WET']},
  {id:'Cocoa',name:'Cocoa',tier:3,soil:'farmland',pools:['ADDICTIVE','BEAN','BROWN','EDIBLE','LEAFY','TREE'],altSeed:true,liked:['JUNGLE','WET','DENSE','LUSH']},
  {id:'Cactus',name:'Cactus',tier:3,soil:'sand',pools:['CACTUS','DANGEROUS','GREEN'],altSeed:true,liked:['SANDY','HOT','DRY']},
  {id:'SugarCane',name:'Sugar Cane',tier:2,soil:'sugarcane',pools:['EDIBLE','GREEN','REED'],altSeed:true,liked:['WET','HOT']},
  {id:'Vine',name:'Vine',tier:2,soil:'farmland',pools:['CLIMBABLE','GREEN','TENDRILLY'],altSeed:true,liked:['LUSH','JUNGLE','WET']},
  {id:'Waterlily',name:'Waterlily',tier:2,soil:'farmland',pools:['GREEN','WATERY'],altSeed:true,liked:['WET','SWAMP','RIVER']},
  {id:'Netherwart',name:'Nether Wart',tier:5,soil:'soulsand',pools:['NETHER','POTION_INGREDIENT','RED'],altSeed:true,liked:['NETHER','HOT']},
  {id:'GaiaWart',name:'Gaia Wart',tier:5,soil:'soulsand',blockUnder:'snow',pools:['NETHER'],note:'Not obtainable via breeding — no mutation recipe or pool registration. Check NEI for acquisition.',altSeed:true,liked:['SNOWY','COLD']},
  {id:'Dandelion',name:'Dandelion',tier:2,soil:'dirtGrass',pools:[],altSeed:true,liked:['PLAINS','FOREST']},
  {id:'Poppy',name:'Poppy',tier:2,soil:'dirtGrass',pools:['FLOWER','RED'],altSeed:true,liked:['PLAINS','HILLS']},
  {id:'BlueOrchid',name:'Blue Orchid',tier:2,soil:'dirtGrass',pools:[],altSeed:true,liked:['WET','SWAMP']},
  {id:'AzureBluet',name:'Azure Bluet',tier:2,soil:'dirtGrass',pools:['FLOWER','WHITE'],altSeed:true,liked:['HILLS','FOREST','LUSH']},
  {id:'RedTulip',name:'Red Tulip',tier:2,soil:'dirtGrass',pools:['FLOWER','RED','TULIP'],altSeed:true,liked:['PLAINS','HOT']},
  {id:'OrangeTulip',name:'Orange Tulip',tier:2,soil:'dirtGrass',pools:['FLOWER','ORANGE','TULIP'],altSeed:true,liked:['PLAINS','WET']},
  {id:'PinkTulip',name:'Pink Tulip',tier:2,soil:'dirtGrass',pools:['FLOWER','RED','TULIP'],altSeed:true,liked:['PLAINS','WET']},
  {id:'WhiteTulip',name:'White Tulip',tier:2,soil:'dirtGrass',pools:['FLOWER','TULIP','WHITE'],altSeed:true,liked:['PLAINS','COLD']},
  {id:'Allium',name:'Allium',tier:2,soil:'dirtGrass',pools:['FLOWER','PURPLE','ROOT'],altSeed:true,liked:['DRY','SANDY','SPARSE']},
  {id:'OxeyeDaisy',name:'Oxeye Daisy',tier:2,soil:'dirtGrass',pools:['FLOWER','WHITE'],altSeed:true,liked:['PLAINS','FOREST']},
  {id:'BrownMushroom',name:'Brown Mushroom',tier:1,soil:'mushroom',pools:['BROWN','EDIBLE','MUSHROOM'],altSeed:true,liked:['MUSHROOM','WET','SWAMP']},
  {id:'RedMushroom',name:'Red Mushroom',tier:1,soil:'mushroom',pools:['EDIBLE','MUSHROOM','RED'],altSeed:true,liked:['MUSHROOM','WET','SWAMP']},
  {id:'BonsaiOak',name:'Bonsai Oak',tier:1,soil:'dirtGrass',pools:['BROWN','EDIBLE','LEAFY','TREE','WOODEN'],liked:['FOREST','HILLS','PLAINS']},
  {id:'BonsaiBirch',name:'Bonsai Birch',tier:1,soil:'dirtGrass',pools:['LEAFY','TREE','WHITE','WOODEN'],liked:['FOREST','HILLS']},
  {id:'BonsaiSpruce',name:'Bonsai Spruce',tier:1,soil:'dirtGrass',pools:['BROWN','TREE','WOODEN'],liked:['CONIFEROUS','FOREST','MOUNTAIN']},
  {id:'BonsaiDarkOak',name:'Bonsai Dark Oak',tier:1,soil:'dirtGrass',pools:['BROWN','DARK','EDIBLE','LEAFY','TREE','WOODEN'],liked:['DENSE','FOREST','SPOOKY']},
  {id:'BonsaiAcacia',name:'Bonsai Acacia',tier:1,soil:'dirtGrass',pools:['LEAFY','ORANGE','TREE','WOODEN'],liked:['HOT','PLAINS','SAVANNA','SPARSE']},
  {id:'BonsaiJungle',name:'Bonsai Jungle',tier:1,soil:'dirtGrass',pools:['BROWN','LEAFY','TREE','WOODEN'],liked:['DENSE','HOT','JUNGLE','WET']},
  {id:'BonsaiRubber',name:'Bonsai Rubber',tier:1,soil:'dirtGrass',pools:['BROWN','STICKY','TREE','WOODEN'],liked:['CONIFEROUS','FOREST']},
  {id:'BonsaiSlimy',name:'Bonsai Slimy',tier:1,soil:'slimyDirt',pools:['STICKY','TREE','WOODEN'],liked:['WET','SWAMP']},
  {id:'StoneLily',name:'Stone Lily',tier:1,soil:'stone',blockUnder:'stone',pools:['GRAY','STONE'],liked:['MOUNTAIN','HILLS']},
  {id:'SandLily',name:'Sand Lily',tier:1,soil:'stone',blockUnder:'sand',pools:['STONE','YELLOW'],liked:['SANDY','DRY','HOT']},
  {id:'ClayLily',name:'Clay Lily',tier:1,soil:'stone',blockUnder:'clay',pools:['GRAY','STONE','WATERY'],liked:['WET','RIVER','SWAMP']},
  {id:'MarbleLily',name:'Marble Lily',tier:1,soil:'stone',blockUnder:'marble',pools:['STONE','WHITE'],liked:['MOUNTAIN','HILLS']},
  {id:'BasaltLily',name:'Basalt Lily',tier:1,soil:'stone',blockUnder:'basalt',pools:['BLACK','DARK','STONE'],liked:['MOUNTAIN','HILLS']},
  {id:'BlackGraniteLily',name:'Black Granite Lily',tier:1,soil:'stone',blockUnder:'blackGranite',pools:['BLACK','DARK','STONE'],liked:['MOUNTAIN','HILLS']},
  {id:'RedGraniteLily',name:'Red Granite Lily',tier:1,soil:'stone',blockUnder:'redGranite',pools:['RED','STONE'],liked:['MOUNTAIN','HILLS']},
  {id:'NetherStoneLily',name:'Nether Stone Lily',tier:1,soil:'stone',blockUnder:'netherrack',pools:['NETHER','RED','STONE'],liked:['NETHER','HOT','DRY']},
  {id:'SoulSandLily',name:'Soul Sand Lily',tier:2,soil:'stone',blockUnder:'soulSand',pools:['BROWN','DANGEROUS','NETHER','OIL','STONE'],liked:['NETHER','SPOOKY','SANDY']},
  {id:'EndStoneLily',name:'End Stone Lily',tier:1,soil:'stone',blockUnder:'endStone',pools:['ALIEN','STONE','YELLOW'],liked:['END','DRY','COLD']},
  {id:'StickyCane',name:'Sticky Cane',tier:4,soil:'sugarcane',pools:['GREEN','REED','STICKY'],liked:['WET','HOT','SANDY']},
  {id:'Flax',name:'Flax',tier:2,soil:'farmland',pools:['ADDICTIVE','BLUE','SILK','WHEAT'],altSeed:true,liked:['WET','RIVER','BEACH','SANDY']},
  {id:'Hemp',name:'Hemp',tier:5,soil:'farmland',pools:['ADDICTIVE','GREEN','SILK','STEM'],liked:['DRY','SANDY']},
  {id:'Indigo',name:'Indigo',tier:2,soil:'dirtGrass',pools:['BLUE','FLOWER'],altSeed:true,liked:['WET','LUSH']},
  {id:'Dayflower',name:'Dayflower',tier:2,soil:'dirtGrass',pools:['ADDICTIVE','BLUE','FLOWER'],liked:['COLD','HILLS','SPARSE']},
  {id:'Canola',name:'Canola',tier:4,soil:'farmland',pools:['EDIBLE','OIL','WHEAT','YELLOW'],liked:['COLD','PLAINS']},
  {id:'Fertilia',name:'Fertilia',tier:3,soil:'farmland',pools:['BROWN','HEALING','MUSHROOM'],liked:['SWAMP','WET','HOT']},
  {id:'Papyrus',name:'Papyrus',tier:5,soil:'farmland',pools:['STEM','WHITE'],liked:['WET','SWAMP','JUNGLE']},
  {id:'PurpleTulip',name:'Purple Tulip',tier:2,soil:'dirtGrass',pools:['FLOWER','PURPLE','TULIP'],liked:['WET','PLAINS']},
  {id:'Necrobloom',name:'Necrobloom',tier:3,soil:'farmland',pools:['DANGEROUS','FLOWER','POISONOUS','PURPLE'],liked:['DEAD','WASTELAND']},
  {id:'RedStraw',name:'Red Straw',tier:6,soil:'farmland',blockUnder:'redstone',pools:['EMISSIVE','POTION_INGREDIENT','RED','STONE','WHEAT'],liked:['PLAINS','HOT']},
  {id:'Withereed',name:'Withereed',tier:8,soil:'stone',blockUnder:'coal',pools:['COAL','FIERY','REED','STEM','SULFUR','UNDEAD'],liked:['DEAD','SPOOKY']},
  {id:'EvilOre',name:'Evil Ore',tier:8,soil:'netherrack',pools:['CRYSTALLINE','EVIL','FIERY','NETHER','WHITE'],liked:['HOT','DRY','NETHER']},
  {id:'Plumbilia',name:'Plumbilia',tier:6,soil:'stone',blockUnder:'lead',pools:['DENSE','LEAD','METALLIC','REED'],liked:['SAVANNA','PLAINS']},
  {id:'Tine',name:'Tine',tier:5,soil:'stone',blockUnder:'tin',pools:['BUSH','METALLIC','SHINY','TIN'],liked:['MOUNTAIN','HILLS']},
  {id:'Ferrofern',name:'Ferrofern',tier:6,soil:'stone',blockUnder:'iron',pools:['GRAY','IRON','METALLIC','TENDRILLY'],liked:['MOUNTAIN','HILLS']},
  {id:'Coppon',name:'Coppon',tier:6,soil:'stone',blockUnder:'copper',pools:['BUSH','COPPER','COTTON','METALLIC','ORANGE','SHINY'],liked:['SAVANNA','HOT','SANDY']},
  {id:'Nickelback',name:'Nickelback',tier:5,soil:'stone',blockUnder:'nickel',pools:['FIERY','METALLIC'],liked:['PLAINS','LUSH']},
  {id:'Galvania',name:'Galvania',tier:6,soil:'stone',blockUnder:'zinc',pools:['BUSH','METALLIC','WHITE'],liked:['DRY','HOT']},
  {id:'Malaxia',name:'Malaxia',tier:6,soil:'stone',blockUnder:'copper',pools:['BUSH','COPPER','LEAFY','METALLIC','ORANGE'],liked:['PLAINS','LUSH']},
  {id:'Cassitine',name:'Cassitine',tier:6,soil:'stone',blockUnder:'tin',pools:['BUSH','GRAY','LEAFY','METALLIC','SHINY','TIN'],liked:['COLD','SPARSE','DRY']},
  {id:'Plumbshade',name:'Plumbshade',tier:6,soil:'stone',blockUnder:'lead',pools:['BUSH','DENSE','LEAD','LEAFY','METALLIC','PURPLE'],liked:['HOT','WET']},
  {id:'Silviscus',name:'Silviscus',tier:8,soil:'stone',blockUnder:'silver',pools:['BUSH','LEAFY','METALLIC','SILVER','WHITE'],liked:['COLD','SNOWY','SPOOKY']},
  {id:'Argentia',name:'Argentia',tier:7,soil:'stone',blockUnder:'silver',pools:['METALLIC','SHINY','SILVER','TENDRILLY','WHITE'],liked:['MOUNTAIN','HOT']},
  {id:'Auronia',name:'Auronia',tier:8,soil:'stone',blockUnder:'gold',pools:['DENSE','GOLD','METALLIC','TENDRILLY','YELLOW'],liked:['MESA','SANDY']},
  {id:'Thiosulfine',name:'Thiosulfine',tier:6,soil:'stone',blockUnder:'sulfur',pools:['DANGEROUS','FLOWER','SULFUR','YELLOW'],liked:['NETHER','HOT']},
  {id:'Pyrolusium',name:'Pyrolusium',tier:12,soil:'stone',blockUnder:'manganese',pools:['BUSH','METALLIC'],liked:['NETHER','HOT']},
  {id:'Lazulia',name:'Lazulia',tier:7,soil:'stone',blockUnder:'lapis',pools:['BLUE','CRYSTALLINE','HEALING','SHINY'],liked:['HOT','SANDY']},
  {id:'Rubyne',name:'Rubyne',tier:4,soil:'farmland',blockUnder:'ruby',pools:['CRYSTALLINE','RED','SHINY'],liked:['MOUNTAIN','RIVER']},
  {id:'Sapphirum',name:'Sapphirum',tier:4,soil:'stone',blockUnder:'sapphire',pools:['CRYSTALLINE','METALLIC','SHINY'],liked:['OCEAN','WET','COLD']},
  {id:'BobsYerUncleRanks',name:'BobsYerUncleRanks',tier:6,soil:'stone',blockUnder:'emerald',pools:['BERRY','CRYSTALLINE','GREEN','SHINY','TENDRILLY'],liked:['MOUNTAIN','HILLS']},
  {id:'Diareed',name:'Diareed',tier:12,soil:'stone',blockUnder:'diamond',pools:['BLUE','COAL','CRYSTALLINE','FIERY','REED','SHINY'],liked:['COLD','SPARSE']},
  {id:'Glowheat',name:'Glowheat',tier:4,soil:'netherrack',blockUnder:'glowstone',pools:['CRYSTALLINE','EMISSIVE','POTION_INGREDIENT','SHINY','WHEAT'],liked:['PLAINS','HOT','NETHER']},
  {id:'SaltyRoot',name:'Salty Root',tier:4,soil:'farmland',pools:['GRAY','ROOT','SALTPETER'],liked:['DRY','SANDY','DEAD']},
  {id:'Corium',name:'Corium',tier:6,soil:'farmland',pools:['COW','SILK','TENDRILLY'],liked:['PLAINS','FOREST']},
  {id:'EggPlant',name:'Egg Plant',tier:6,soil:'farmland',pools:['ADDICTIVE','CHICKEN','EDIBLE','FLOWER'],altSeed:true,liked:['PLAINS','FOREST']},
  {id:'Creeperweed',name:'Creeperweed',tier:7,soil:'farmland',pools:['COAL','EVIL','FIERY','POTION_INGREDIENT','SALTPETER','SULFUR','TENDRILLY'],liked:['DEAD','SPOOKY']},
  {id:'Spidernip',name:'Spidernip',tier:4,soil:'farmland',pools:['ADDICTIVE','EDIBLE','EVIL','POISONOUS','POTION_INGREDIENT','SILK','WHITE'],liked:['WET','LUSH']},
  {id:'InkBloom',name:'Ink Bloom',tier:4,soil:'dirtGrass',pools:['BLACK','FLOWER','WATERY'],liked:['WET','OCEAN']},
  {id:'Slimeplant',name:'Slimeplant',tier:6,soil:'dirtGrass',pools:['BUSH','EVIL','GREEN','POTION_INGREDIENT','STICKY'],liked:['WET','SWAMP']},
  {id:'Goldfish',name:'Goldfish',tier:4,soil:'farmland',pools:['ADDICTIVE','DANGEROUS','EDIBLE','FISH','NETHER','WATERY'],liked:['RIVER','WET','SPOOKY']},
  {id:'Enderbloom',name:'Enderbloom',tier:10,soil:'farmland',blockUnder:'endStone',pools:['ALIEN','FLOWER','MAGICAL','SHINY'],liked:['END','COLD']},
  {id:'Zomplant',name:'Zomplant',tier:3,soil:'graveyard',pools:['BROWN','EDIBLE','EVIL','POISONOUS','UNDEAD'],liked:['DEAD','WASTELAND']},
  {id:'Corpseplant',name:'Corpseplant',tier:5,soil:'graveyard',pools:['BROWN','EDIBLE','EVIL','POISONOUS','TENDRILLY','UNDEAD'],liked:['DEAD','SPOOKY']},
  {id:'Tearstalks',name:'Tearstalks',tier:8,soil:'farmland',pools:['EVIL','HEALING','NETHER','POTION_INGREDIENT','STEM','WHITE'],liked:['NETHER','DEAD']},
  {id:'MilkWart',name:'Milk Wart',tier:6,soil:'farmland',pools:['COW','EDIBLE','HEALING'],liked:['PLAINS','LUSH']},
  {id:'Meatrose',name:'Meatrose',tier:7,soil:'dirtGrass',pools:['CHICKEN','COW','EDIBLE','FISH','FLOWER'],liked:['PLAINS','MAGICAL']},
  {id:'Lemon',name:'Lemon',tier:4,soil:'dirtGrass',pools:['EDIBLE','LEAFY','TREE','YELLOW'],altSeed:true,liked:['HOT','DRY','PLAINS']},
  {id:'Onion',name:'Onion',tier:4,soil:'farmland',pools:['BROWN','EDIBLE','ROOT'],altSeed:true,liked:['DRY','SANDY','SPARSE']},
  {id:'SugarBeet',name:'Sugar Beet',tier:4,soil:'farmland',pools:['ADDICTIVE','EDIBLE','POTION_INGREDIENT','ROOT','WHITE'],altSeed:true,liked:['COLD','WET']},
  {id:'Tomato',name:'Tomato',tier:4,soil:'farmland',pools:['EDIBLE','LEAFY','RED','TENDRILLY'],altSeed:true,liked:['HOT','WET']},
  {id:'Cucumber',name:'Cucumber',tier:4,soil:'farmland',pools:['EDIBLE','GREEN','TENDRILLY'],altSeed:true,liked:['HOT','LUSH']},
  {id:'Chilly',name:'Chilly',tier:4,soil:'farmland',pools:['EDIBLE','FIERY','RED'],altSeed:true,liked:['HOT','LUSH']},
  {id:'Coffee',name:'Coffee',tier:7,soil:'farmland',pools:['ADDICTIVE','BEAN','BROWN','EDIBLE','LEAFY'],altSeed:true,liked:['HOT','LUSH','WET']},
  {id:'Hops',name:'Hops',tier:5,soil:'farmland',pools:['EDIBLE','GREEN','WHEAT'],altSeed:true,liked:['PLAINS','LUSH']},
  {id:'Strawberry',name:'Strawberry',tier:2,soil:'farmland',pools:['BERRY','BUSH','EDIBLE','RED'],note:'PHC req',altSeed:true,liked:['PLAINS','LUSH']},
  {id:'Blueberry',name:'Blueberry',tier:2,soil:'farmland',pools:['BERRY','BLUE','BUSH','EDIBLE'],note:'Natura req',altSeed:true,liked:['HILLS','FOREST','LUSH']},
  {id:'Blackberry',name:'Blackberry',tier:2,soil:'farmland',pools:['BERRY','BLACK','BUSH','EDIBLE'],note:'Natura req',altSeed:true,liked:['WET','DENSE','LUSH']},
  {id:'Raspberry',name:'Raspberry',tier:2,soil:'farmland',pools:['BERRY','BUSH','EDIBLE','RED'],note:'Natura req',altSeed:true,liked:['PLAINS','DRY']},
  {id:'Grape',name:'Grape',tier:4,soil:'farmland',pools:['CLIMBABLE','EDIBLE','LEAFY','PURPLE','TENDRILLY'],note:'Natura req',altSeed:true,liked:['HOT','DRY','SPARSE']},
  {id:'Huckleberry',name:'Huckleberry',tier:2,soil:'farmland',pools:['BERRY','BUSH','EDIBLE','LEAFY','PURPLE'],note:'Natura req',altSeed:true,liked:['MOUNTAIN','HILLS','PLAINS','COLD']},
  {id:'Maloberry',name:'Maloberry',tier:2,soil:'farmland',pools:['BERRY','BUSH','EDIBLE','YELLOW'],note:'Natura req',altSeed:true,liked:['COLD','WET','LUSH']},
  {id:'Cotton',name:'Cotton',tier:3,soil:'farmland',pools:['COTTON','SILK','TENDRILLY','WHITE'],note:'Natura req',altSeed:true,liked:['DRY','HOT']},
  {id:'ManaBean',name:'Mana Bean',tier:5,soil:'thaumLogs',blockUnder:'mixedCrystalCluster',pools:['BEAN','BROWN','MAGICAL'],note:'TC req',liked:['MAGICAL','FOREST']},
  {id:'Cinderpearl',name:'Cinderpearl',tier:5,soil:'dirtGrass',blockUnder:'blaze',pools:['BLAZE','MAGICAL','ORANGE'],note:'TC req',altSeed:true,liked:['HOT','DRY','MAGICAL']},
  {id:'Shimmerleaf',name:'Shimmerleaf',tier:5,soil:'dirtGrass',blockUnder:'quicksilver',pools:['EMISSIVE','GRAY','MAGICAL','POISONOUS','SILVER'],note:'TC req',altSeed:true,liked:['MAGICAL','LUSH']},
  {id:'PrimordialBerry',name:'Primordial Berry',tier:16,soil:'farmland',pools:[],note:'TC req - plant-only',altSeed:true,liked:['END','MAGICAL']},
  {id:'Bauxia',name:'Bauxia',tier:6,soil:'stone',blockUnder:'aluminiumBauxite',pools:[],machine:true,liked:['COLD','DRY']},
  {id:'Micadia',name:'Micadia',tier:9,soil:'stone',blockUnder:'mica',pools:['STONE'],machine:true,liked:['HILLS','SPARSE']},
  {id:'Titania',name:'Titania',tier:9,soil:'stone',blockUnder:'titanium',pools:['STONE'],machine:true,liked:['HOT','SAVANNA']},
  {id:'OilBerry',name:'Oil Berry',tier:4,soil:'oil',pools:['OIL'],machine:true,liked:['HOT','WASTELAND']},
  {id:'Olivia',name:'Olivia',tier:2,soil:'stone',blockUnder:'olivine',pools:['STONE'],machine:true,liked:['HILLS','DRY']},
  {id:'Garnydinia',name:'Garnydinia',tier:7,soil:'stone',blockUnder:'garnetGem',pools:['STONE'],machine:true,liked:['SAVANNA','SANDY','MESA']},
  {id:'GodOfThunder',name:'God of Thunder',tier:9,soil:'stone',blockUnder:'thorium',pools:['STONE'],machine:true,liked:['WASTELAND','SPARSE']},
  {id:'Reactoria',name:'Reactoria',tier:12,soil:'stone',blockUnder:'uranium',pools:['STONE'],machine:true,liked:['COLD','HOT']},
  {id:'Scheelinium',name:'Scheelinium',tier:12,soil:'stone',blockUnder:'tungsten',pools:['STONE'],machine:true,liked:['OCEAN','WET','COLD']},
  {id:'Platina',name:'Platina',tier:11,soil:'stone',blockUnder:'platinum',pools:['STONE'],machine:true,liked:['HOT','SANDY']},
  {id:'SpaceFlower',name:'Space FlowerS',tier:13,soil:'farmland',blockUnder:'space',pools:['FLOWER'],machine:true,liked:['COLD','DRY','DEAD']},
  {id:'Iridine',name:'Iridine',tier:12,soil:'stone',blockUnder:'iridium',pools:['FLOWER','STONE'],machine:true,liked:['SNOWY','COLD']},
  {id:'Osmianth',name:'Osmianth',tier:12,soil:'stone',blockUnder:'osmium',pools:['FLOWER','STONE'],machine:true,liked:['OCEAN','RIVER']},
  {id:'Transformium',name:'Transformium',tier:12,soil:'farmland',pools:[],machine:true,liked:['END','COLD']},
  {id:'StarWart',name:'Star Wart',tier:12,soil:'stone',blockUnder:'netherStar',pools:['NETHER','STONE'],machine:true,liked:['NETHER','DEAD']},
  {id:'MagicalNightshade',name:'Magical Nightshade',tier:13,soil:'farmland',blockUnder:'shadowmetal',pools:['MAGICAL'],machine:true,altSeed:true,liked:['MAGICAL','COLD']},
  {id:'Trollplant',name:'Trollplant',tier:6,soil:'brick',pools:[],machine:true,req:'Plutonium dust ×1, Red Alloy Stick ×64, Brick Block ×5',liked:['SWAMP','SPOOKY']},
  {id:'Stargatium',name:'Stargatium',tier:12,soil:'stone',blockUnder:'naquadah',pools:['STONE'],machine:true,liked:['LUSH','WASTELAND']},
  {id:'Eyebulb',name:'Eyebulb',tier:1,soil:'netherrack',pools:['EVIL','NETHER','RED','TENDRILLY'],note:'BoP req',altSeed:true,liked:['NETHER','SPOOKY']},
  {id:'Glowflower',name:'Glowflower',tier:3,soil:'dirtGrass',pools:['BLUE','EMISSIVE','NETHER','POTION_INGREDIENT','SHINY'],note:'BoP req',altSeed:true,liked:['WET','LUSH','MAGICAL','FOREST']},
  {id:'Bamboo',name:'Bamboo',tier:2,soil:'dirtGrass',pools:['DANGEROUS','GREEN','LEAFY','STEM'],note:'BoP req',altSeed:true,liked:['DENSE','JUNGLE','LUSH','FOREST']},
  {id:'FloweringVine',name:'Flowering Vine',tier:3,soil:'farmland',pools:['CLIMBABLE','FLOWER','GREEN','TENDRILLY'],note:'BoP req',altSeed:true,liked:['JUNGLE','DENSE']},
  {id:'GlowingCoral',name:'Glowing Coral',tier:5,soil:'farmland',blockUnder:'glowstone',pools:['EMISSIVE','POTION_INGREDIENT','PURPLE','SHINY','WATERY'],note:'BoP req',altSeed:true,liked:['OCEAN','RIVER']},
  {id:'Ivy',name:'Ivy',tier:2,soil:'farmland',pools:['CLIMBABLE','DANGEROUS','FLOWER','GREEN','POISONOUS','TENDRILLY'],note:'BoP req',altSeed:true,liked:['NETHER','JUNGLE','MAGICAL','DENSE']},
  {id:'Moss',name:'Moss',tier:4,soil:'farmland',pools:['CLIMBABLE','GREEN','TENDRILLY','TWILIGHT_FOREST'],note:'BoP req',altSeed:true,liked:['WET','SWAMP','LUSH']},
  {id:'Blightberry',name:'Blightberry',tier:4,soil:'netherrack',pools:['ADDICTIVE','BERRY','BUSH','DANGEROUS','EDIBLE','GREEN','HEALING','NETHER','POISONOUS','POTION_INGREDIENT'],note:'Natura req',altSeed:true,liked:['NETHER','DRY']},
  {id:'Duskberry',name:'Duskberry',tier:4,soil:'netherrack',pools:['ADDICTIVE','BERRY','BUSH','DANGEROUS','EDIBLE','GRAY','NETHER','POISONOUS','POTION_INGREDIENT'],note:'Natura req',altSeed:true,liked:['NETHER','HOT']},
  {id:'Skyberry',name:'Skyberry',tier:4,soil:'netherrack',pools:['ADDICTIVE','BERRY','BLUE','BUSH','DANGEROUS','EDIBLE','NETHER','POISONOUS','POTION_INGREDIENT'],note:'Natura req',altSeed:true,liked:['NETHER','DRY']},
  {id:'Stingberry',name:'Stingberry',tier:4,soil:'netherrack',pools:['ADDICTIVE','BERRY','BROWN','BUSH','DANGEROUS','EDIBLE','NETHER','POISONOUS','POTION_INGREDIENT'],note:'Natura req',altSeed:true,liked:['NETHER','HOT']},
  {id:'Thornvine',name:'Thornvine',tier:3,soil:'netherrack',pools:['CLIMBABLE','DANGEROUS','EMISSIVE','NETHER','TENDRILLY','YELLOW'],note:'Natura req',altSeed:true,liked:['NETHER','DRY']},
  {id:'WaterArtichoke',name:'Water Artichoke',tier:4,soil:'farmland',pools:['BLUE','EDIBLE','FLOWER','POTION_INGREDIENT','WATERY'],note:'Witchery req',altSeed:true,liked:['RIVER','WET','OCEAN']},
  {id:'Mandrake',name:'Mandrake',tier:4,soil:'farmland',pools:['BROWN','DANGEROUS','EVIL','FLOWER','MAGICAL','POTION_INGREDIENT'],note:'Witchery req',altSeed:true,liked:['MAGICAL','SPOOKY']},
  {id:'Belladonna',name:'Belladonna',tier:4,soil:'farmland',pools:['FLOWER','POISONOUS','POTION_INGREDIENT','PURPLE'],note:'Witchery req',altSeed:true,liked:['WET','SPOOKY']},
  {id:'Garlic',name:'Garlic',tier:3,soil:'farmland',pools:['EDIBLE','POTION_INGREDIENT','ROOT','WHITE'],note:'Witchery req',altSeed:true,liked:['PLAINS','DRY']},
  {id:'GlintWeed',name:'Glint Weed',tier:4,soil:'farmland',pools:['FLOWER','MAGICAL','ORANGE'],note:'Witchery req',altSeed:true,liked:['MAGICAL','PLAINS','SANDY']},
  {id:'Snowbell',name:'Snowbell',tier:4,soil:'farmland',pools:['FLOWER','POISONOUS','POTION_INGREDIENT','WHITE'],note:'Witchery req',altSeed:true,liked:['SNOWY','COLD']},
  {id:'Wolfsbane',name:'Wolfsbane',tier:4,soil:'farmland',pools:['FLOWER','POISONOUS','POTION_INGREDIENT','PURPLE'],note:'Witchery req',altSeed:true,liked:['MAGICAL','FOREST','SPOOKY']},
  {id:'EmberMoss',name:'Ember Moss',tier:7,soil:'farmland',pools:['CLIMBABLE','DANGEROUS','FIERY','POTION_INGREDIENT','RED','TENDRILLY'],note:'Witchery req',altSeed:true,liked:['HOT','DRY']},
  {id:'SpanishMoss',name:'Spanish Moss',tier:7,soil:'farmland',pools:['CLIMBABLE','GREEN','MAGICAL'],note:'Witchery req',altSeed:true,liked:['LUSH','WET','FOREST','SWAMP']},
  {id:'Torchberry',name:'Torchberry',tier:2,soil:'farmland',pools:['BERRY','EMISSIVE','TWILIGHT_FOREST','YELLOW'],note:'TF req',altSeed:true,liked:['FOREST','HILLS']},
  {id:'BoPBerry',name:'BoP Berry',tier:2,soil:'farmland',pools:['BERRY','BUSH','EDIBLE','RED'],note:'BoP req',altSeed:true,liked:['FOREST','DENSE']},
  {id:'Turnip',name:'Turnip',tier:2,soil:'farmland',pools:['EDIBLE','PURPLE','ROOT'],note:'BoP req',altSeed:true,liked:['PLAINS','WET','COLD']},
  {id:'WildCarrot',name:'Wild Carrot',tier:2,soil:'farmland',pools:['EDIBLE','ROOT','WHITE'],note:'BoP req',altSeed:true,liked:['PLAINS','HOT','SANDY']},
  {id:'Barley',name:'Barley',tier:2,soil:'farmland',pools:['EDIBLE','GREEN','WHEAT'],note:'Natura+BoP req',altSeed:true,liked:['PLAINS','DRY']},
  {id:'Blazereed',name:'Blazereed',tier:6,soil:'netherrack',pools:['BLAZE','EVIL','FIERY','NETHER','POTION_INGREDIENT','REED','SULFUR'],note:'TC req',liked:['NETHER','HOT']},
  {id:'SaguaroCactus',name:'Saguaro Cactus',tier:4,soil:'sand',pools:['CACTUS','DANGEROUS','EDIBLE','GREEN'],note:'Natura req',altSeed:true,liked:['HOT','DRY','SANDY']},
  {id:'Tea',name:'Tea',tier:4,soil:'farmland',pools:['EDIBLE','GREEN','LEAFY'],note:'Natura req',altSeed:true,liked:['WET','HILLS','HOT']},
  {id:'IronOreBerry',name:'Iron Ore Berry',tier:5,soil:'stone',blockUnder:'iron',pools:['DANGEROUS','GRAY','IRON','METALLIC','ORE_BERRY'],note:'TiC req',altSeed:true,liked:['MOUNTAIN','HILLS']},
  {id:'GoldOreBerry',name:'Gold Ore Berry',tier:5,soil:'stone',blockUnder:'gold',pools:['DANGEROUS','DENSE','GOLD','METALLIC','ORE_BERRY','YELLOW'],note:'TiC req',altSeed:true,liked:['MESA','SANDY']},
  {id:'CopperOreBerry',name:'Copper Ore Berry',tier:5,soil:'stone',blockUnder:'copper',pools:['COPPER','DANGEROUS','METALLIC','ORANGE','ORE_BERRY','SHINY'],note:'TiC req',altSeed:true,liked:['SAVANNA','HOT','SANDY']},
  {id:'TinOreBerry',name:'Tin Ore Berry',tier:4,soil:'stone',blockUnder:'tin',pools:['DANGEROUS','METALLIC','ORE_BERRY','SHINY','TIN','WHITE'],note:'TiC req',altSeed:true,liked:['MOUNTAIN','HILLS']},
  {id:'AluminiumOreBerry',name:'Aluminium Ore Berry',tier:5,soil:'stone',blockUnder:'aluminium',pools:['DANGEROUS','METALLIC','ORE_BERRY','WHITE'],note:'TiC req',altSeed:true,liked:['COLD','DRY']},
  {id:'EssenceOreBerry',name:'Essence Ore Berry',tier:5,soil:'stone',blockUnder:'skull',pools:['DANGEROUS','EDIBLE','GREEN','ORE_BERRY','UNDEAD'],note:'TiC req',altSeed:true,liked:['MAGICAL','DEAD']},
  {id:'ArditeOreBerry',name:'Ardite Ore Berry',tier:5,soil:'stone',blockUnder:'ardite',pools:['DANGEROUS','METALLIC','ORANGE','ORE_BERRY'],note:'TiC req',liked:['NETHER','HOT']},
  {id:'CobaltOreBerry',name:'Cobalt Ore Berry',tier:5,soil:'stone',blockUnder:'cobalt',pools:['BLUE','DANGEROUS','METALLIC','NETHER','ORE_BERRY'],note:'TiC req',liked:['NETHER','DRY']},
  {id:'ThaumiumOreBerry',name:'Thaumium Ore Berry',tier:7,soil:'stone',blockUnder:'thaumium',pools:['DANGEROUS','MAGICAL','METALLIC','ORE_BERRY','PURPLE','VOID_TOUCHED'],note:'TiC+TC req',liked:['MAGICAL','SPOOKY']},
  {id:'ThauminiteOreBerry',name:'Thauminite Ore Berry',tier:7,soil:'stone',blockUnder:'thauminite',pools:['BLUE','DANGEROUS','MAGICAL','METALLIC','ORE_BERRY','VOID_TOUCHED'],note:'TiC+TC+ThaumicBases req',liked:['MAGICAL','FOREST']},
  {id:'VoidOreBerry',name:'Void Ore Berry',tier:7,soil:'stone',blockUnder:'void',pools:['MAGICAL','VOID_TOUCHED'],note:'TC req',altSeed:true,liked:['MAGICAL','WASTELAND']},
  {id:'KnightmetalBerry',name:'Knightmetal Berry',tier:8,soil:'stone',blockUnder:'knightmetal',pools:['DANGEROUS','GRAY','METALLIC','ORE_BERRY','TWILIGHT_FOREST'],note:'TiC+TF req',liked:['SPOOKY','DEAD']},
  {id:'AndesiteLily',name:'Andesite Lily',tier:1,soil:'stone',blockUnder:'modernAndesite',pools:['GRAY','STONE'],liked:['MOUNTAIN','HILLS']},
  {id:'DioriteLily',name:'Diorite Lily',tier:1,soil:'stone',blockUnder:'modernDiorite',pools:['STONE','WHITE'],liked:['MOUNTAIN','HILLS']},
  {id:'GraniteLily',name:'Granite Lily',tier:1,soil:'stone',blockUnder:'modernGranite',pools:['RED','STONE'],liked:['MOUNTAIN','HILLS']},
  {id:'TuffLily',name:'Tuff Lily',tier:1,soil:'stone',blockUnder:'tuff',pools:['DARK','GRAY','STONE'],note:'EtFuturum req',liked:['MOUNTAIN','HILLS']},
  {id:'DeepslateLily',name:'Deepslate Lily',tier:1,soil:'stone',blockUnder:'deepslate',pools:['BLACK','DARK','DENSE','STONE'],note:'EtFuturum req',liked:['MOUNTAIN','HILLS']},
  {id:'BlueGlowshroom',name:'Blue Glowshroom',tier:3,soil:'netherMushroom',pools:['BLUE','EDIBLE','EMISSIVE','MUSHROOM','NETHER','POTION_INGREDIENT'],note:'Natura req'},
  {id:'GreenGlowshroom',name:'Green Glowshroom',tier:3,soil:'netherMushroom',pools:[],note:'Natura req'},
  {id:'PurpleGlowshroom',name:'Purple Glowshroom',tier:3,soil:'netherMushroom',pools:['EDIBLE','EMISSIVE','MUSHROOM','NETHER','POTION_INGREDIENT','PURPLE'],note:'Natura req'},
  {id:'Glowshroom',name:'Glowshroom',tier:3,soil:'netherMushroom',pools:['EMISSIVE','GREEN','MUSHROOM','NETHER','POTION_INGREDIENT'],note:'BoP req',altSeed:true,liked:['NETHER','MAGICAL','MUSHROOM']},
  {id:'Liveroot',name:'Liveroot',tier:8,soil:'farmland',pools:['BROWN','ROOT','TENDRILLY','TWILIGHT_FOREST','WOODEN'],note:'TwilightForest req',liked:['SPOOKY','DENSE']},
  {id:'Steeleafranks',name:'Steeleafranks',tier:10,soil:'stone',blockUnder:'steeleaf',pools:['GREEN','IRON','METALLIC','TENDRILLY','TWILIGHT_FOREST'],note:'TwilightForest req',liked:['SPOOKY','DEAD']},
];
const MUTS=[
  {out:'Allium',par:['PinkTulip','PurpleTulip'],pools:['FLOWER','PURPLE','ROOT']},
  {out:'AluminiumOreBerry',par:['GoldOreBerry','EssenceOreBerry'],pools:['DANGEROUS','METALLIC','ORE_BERRY','WHITE']},
  {out:'AndesiteLily',par:['StoneLily','ClayLily'],pools:['GRAY','STONE']},
  {out:'ArditeOreBerry',par:['NetherStoneLily','Coppon','CopperOreBerry','Malaxia'],pools:['DANGEROUS','METALLIC','ORANGE','ORE_BERRY']},
  {out:'Argentia',par:['Plumbilia','Tine'],pools:['METALLIC','SHINY','SILVER','TENDRILLY','WHITE']},
  {out:'Auronia',par:['Plumbilia','Coppon'],pools:['DENSE','GOLD','METALLIC','TENDRILLY','YELLOW']},
  {out:'AzureBluet',par:['Poppy','Potato'],pools:['FLOWER','WHITE']},
  {out:'Bamboo',par:['BonsaiJungle','Vine'],pools:['DANGEROUS','GREEN','LEAFY','STEM']},
  {out:'Barley',par:['Bamboo','Wheat'],pools:['EDIBLE','GREEN','WHEAT']},
  {out:'BasaltLily',par:['StoneLily','InkBloom'],pools:['BLACK','DARK','STONE']},
  {out:'Belladonna',par:['PurpleTulip','Huckleberry'],pools:['FLOWER','POISONOUS','POTION_INGREDIENT','PURPLE']},
  {out:'BlackGraniteLily',par:['StoneLily','BasaltLily'],pools:['BLACK','DARK','STONE']},
  {out:'Blackberry',par:['Strawberry','Blueberry'],pools:['BERRY','BLACK','BUSH','EDIBLE']},
  {out:'Blazereed',par:['SugarCane','Cinderpearl'],pools:['BLAZE','EVIL','FIERY','NETHER','POTION_INGREDIENT','REED','SULFUR']},
  {out:'Blightberry',par:['Maloberry','Raspberry'],pools:['ADDICTIVE','BERRY','BUSH','DANGEROUS','EDIBLE','GREEN','HEALING','NETHER','POISONOUS','POTION_INGREDIENT']},
  {out:'BlueOrchid',par:['Poppy','Waterlily'],pools:[]},
  {out:'Blueberry',par:['AzureBluet','BonsaiOak'],pools:['BERRY','BLUE','BUSH','EDIBLE']},
  {out:'BobsYerUncleRanks',par:['Diareed','Olivia'],pools:['BERRY','CRYSTALLINE','GREEN','SHINY','TENDRILLY']},
  {out:'BonsaiAcacia',par:['BonsaiOak','Cactus'],pools:['LEAFY','ORANGE','TREE','WOODEN']},
  {out:'BonsaiBirch',par:['BonsaiOak','SugarCane'],pools:['LEAFY','TREE','WHITE','WOODEN']},
  {out:'BonsaiDarkOak',par:['BonsaiSpruce','BonsaiOak'],pools:['BROWN','DARK','EDIBLE','LEAFY','TREE','WOODEN']},
  {out:'BonsaiJungle',par:['BonsaiOak','Vine'],pools:['BROWN','LEAFY','TREE','WOODEN']},
  {out:'BonsaiOak',par:['Wheat','BrownMushroom'],pools:['BROWN','EDIBLE','LEAFY','TREE','WOODEN']},
  {out:'BonsaiRubber',par:['BonsaiJungle','BonsaiSpruce'],pools:['BROWN','STICKY','TREE','WOODEN']},
  {out:'BonsaiSpruce',par:['BonsaiOak','Pumpkin'],pools:['BROWN','TREE','WOODEN']},
  {out:'BoPBerry',par:['Poppy','Blackberry'],pools:['BERRY','BUSH','EDIBLE','RED']},
  {out:'BrownMushroom',par:['Cocoa','RedMushroom'],pools:['BROWN','EDIBLE','MUSHROOM']},
  {out:'Cactus',par:['SugarCane','Potato'],pools:['CACTUS','DANGEROUS','GREEN']},
  {out:'Canola',par:['OxeyeDaisy','Wheat'],pools:['EDIBLE','OIL','WHEAT','YELLOW']},
  {out:'Cassitine',par:['Malaxia','StoneLily','MarbleLily'],pools:['BUSH','GRAY','LEAFY','METALLIC','SHINY','TIN']},
  {out:'Chilly',par:['Cactus','Cocoa'],pools:['EDIBLE','FIERY','RED']},
  {out:'Cinderpearl',par:['EmberMoss','GlintWeed'],pools:['BLAZE','MAGICAL','ORANGE']},
  {out:'ClayLily',par:['StoneLily','Waterlily'],pools:['GRAY','STONE','WATERY']},
  {out:'CobaltOreBerry',par:['NetherStoneLily','ArditeOreBerry','Lazulia','GoldOreBerry'],pools:['BLUE','DANGEROUS','METALLIC','NETHER','ORE_BERRY']},
  {out:'Cocoa',par:['Melon','BonsaiJungle'],pools:['ADDICTIVE','BEAN','BROWN','EDIBLE','LEAFY','TREE']},
  {out:'Coffee',par:['Cocoa','BonsaiAcacia'],pools:['ADDICTIVE','BEAN','BROWN','EDIBLE','LEAFY']},
  {out:'CopperOreBerry',par:['Malaxia','BoPBerry','StoneLily'],pools:['COPPER','DANGEROUS','METALLIC','ORANGE','ORE_BERRY','SHINY']},
  {out:'Coppon',par:['StoneLily','NetherStoneLily'],pools:['BUSH','COPPER','COTTON','METALLIC','ORANGE','SHINY']},
  {out:'Corium',par:['Wheat','Cocoa'],pools:['COW','SILK','TENDRILLY']},
  {out:'Corpseplant',par:['Zomplant','Eyebulb'],pools:['BROWN','EDIBLE','EVIL','POISONOUS','TENDRILLY','UNDEAD']},
  {out:'Cotton',par:['Flax','Hemp'],pools:['COTTON','SILK','TENDRILLY','WHITE']},
  {out:'Creeperweed',par:['NetherStoneLily','Withereed','SaltyRoot'],pools:['COAL','EVIL','FIERY','POTION_INGREDIENT','SALTPETER','SULFUR','TENDRILLY']},
  {out:'Cucumber',par:['Melon','Carrot'],pools:['EDIBLE','GREEN','TENDRILLY']},
  {out:'Dayflower',par:['AzureBluet','BlueOrchid'],pools:['ADDICTIVE','BLUE','FLOWER']},
  {out:'DeepslateLily',par:['TuffLily','BlackGraniteLily'],pools:['BLACK','DARK','DENSE','STONE']},
  {out:'Diareed',par:['Withereed','EvilOre'],pools:['BLUE','COAL','CRYSTALLINE','FIERY','REED','SHINY']},
  {out:'DioriteLily',par:['StoneLily','MarbleLily'],pools:['STONE','WHITE']},
  {out:'Duskberry',par:['InkBloom','Blackberry'],pools:['ADDICTIVE','BERRY','BUSH','DANGEROUS','EDIBLE','GRAY','NETHER','POISONOUS','POTION_INGREDIENT']},
  {out:'EggPlant',par:['Corium','OxeyeDaisy'],pools:['ADDICTIVE','CHICKEN','EDIBLE','FLOWER']},
  {out:'EmberMoss',par:['RedTulip','Moss'],pools:['CLIMBABLE','DANGEROUS','FIERY','POTION_INGREDIENT','RED','TENDRILLY']},
  {out:'EndStoneLily',par:['StoneLily','Enderbloom'],pools:['ALIEN','STONE','YELLOW']},
  {out:'Enderbloom',par:['EndStoneLily','Creeperweed'],pools:['ALIEN','FLOWER','MAGICAL','SHINY']},
  {out:'EssenceOreBerry',par:['Creeperweed','Zomplant','Spidernip','Tearstalks'],pools:['DANGEROUS','EDIBLE','GREEN','ORE_BERRY','UNDEAD']},
  {out:'EvilOre',par:['NetherStoneLily','SoulSandLily'],pools:['CRYSTALLINE','EVIL','FIERY','NETHER','WHITE']},
  {out:'Eyebulb',par:['NetherStoneLily','RedTulip'],pools:['EVIL','NETHER','RED','TENDRILLY']},
  {out:'Ferrofern',par:['StoneLily','BlackGraniteLily'],pools:['GRAY','IRON','METALLIC','TENDRILLY']},
  {out:'Fertilia',par:['Corium','Corpseplant'],pools:['BROWN','HEALING','MUSHROOM']},
  {out:'Flax',par:['Wheat','AzureBluet'],pools:['ADDICTIVE','BLUE','SILK','WHEAT']},
  {out:'FloweringVine',par:['OxeyeDaisy','Ivy'],pools:['CLIMBABLE','FLOWER','GREEN','TENDRILLY']},
  {out:'Galvania',par:['Tine','Ferrofern'],pools:['BUSH','METALLIC','WHITE']},
  {out:'Garlic',par:['Onion','Allium'],pools:['EDIBLE','POTION_INGREDIENT','ROOT','WHITE']},
  {out:'GlintWeed',par:['Vine','EmberMoss'],pools:['FLOWER','MAGICAL','ORANGE']},
  {out:'Glowflower',par:['NetherStoneLily','Dandelion'],pools:['BLUE','EMISSIVE','NETHER','POTION_INGREDIENT','SHINY']},
  {out:'Glowheat',par:['Glowflower','Wheat'],pools:['CRYSTALLINE','EMISSIVE','POTION_INGREDIENT','SHINY','WHEAT']},
  {out:'GlowingCoral',par:['Glowflower','Waterlily'],pools:['EMISSIVE','POTION_INGREDIENT','PURPLE','SHINY','WATERY']},
  {out:'Glowshroom',par:['BlueGlowshroom','GreenGlowshroom','PurpleGlowshroom'],pools:['EMISSIVE','GREEN','MUSHROOM','NETHER','POTION_INGREDIENT']},
  {out:'GoldOreBerry',par:['CopperOreBerry','IronOreBerry','TinOreBerry'],pools:['DANGEROUS','DENSE','GOLD','METALLIC','ORE_BERRY','YELLOW']},
  {out:'Goldfish',par:['Waterlily','WaterArtichoke','Mandrake'],pools:['ADDICTIVE','DANGEROUS','EDIBLE','FISH','NETHER','WATERY']},
  {out:'GraniteLily',par:['BlackGraniteLily','RedGraniteLily'],pools:['RED','STONE']},
  {out:'Grape',par:['Blueberry','Blackberry'],pools:['CLIMBABLE','EDIBLE','LEAFY','PURPLE','TENDRILLY']},
  {out:'Hemp',par:['Flax','Papyrus'],pools:['ADDICTIVE','GREEN','SILK','STEM']},
  {out:'Hops',par:['Hemp','Dandelion'],pools:['EDIBLE','GREEN','WHEAT']},
  {out:'Huckleberry',par:['Blackberry','Grape'],pools:['BERRY','BUSH','EDIBLE','LEAFY','PURPLE']},
  {out:'Indigo',par:['Dayflower','BlueOrchid'],pools:['BLUE','FLOWER']},
  {out:'InkBloom',par:['Blackberry','Goldfish'],pools:['BLACK','FLOWER','WATERY']},
  {out:'IronOreBerry',par:['TinOreBerry','StoneLily'],pools:['DANGEROUS','GRAY','IRON','METALLIC','ORE_BERRY']},
  {out:'Ivy',par:['Vine','BonsaiSpruce'],pools:['CLIMBABLE','DANGEROUS','FLOWER','GREEN','POISONOUS','TENDRILLY']},
  {out:'KnightmetalBerry',par:['IronOreBerry','Torchberry','BonsaiDarkOak'],pools:['DANGEROUS','GRAY','METALLIC','ORE_BERRY','TWILIGHT_FOREST']},
  {out:'Lazulia',par:['StoneLily','Indigo'],pools:['BLUE','CRYSTALLINE','HEALING','SHINY']},
  {out:'Lemon',par:['BonsaiOak','BonsaiAcacia'],pools:['EDIBLE','LEAFY','TREE','YELLOW']},
  {out:'Liveroot',par:['Torchberry','BonsaiDarkOak'],pools:['BROWN','ROOT','TENDRILLY','TWILIGHT_FOREST','WOODEN']},
  {out:'Malaxia',par:['OrangeTulip','Pumpkin','StoneLily'],pools:['BUSH','COPPER','LEAFY','METALLIC','ORANGE']},
  {out:'Maloberry',par:['OrangeTulip','Blueberry'],pools:['BERRY','BUSH','EDIBLE','YELLOW']},
  {out:'ManaBean',par:['Cocoa','Cinderpearl','Shimmerleaf'],pools:['BEAN','BROWN','MAGICAL']},
  {out:'Mandrake',par:['Carrot','Belladonna'],pools:['BROWN','DANGEROUS','EVIL','FLOWER','MAGICAL','POTION_INGREDIENT']},
  {out:'MarbleLily',par:['StoneLily','OxeyeDaisy'],pools:['STONE','WHITE']},
  {out:'Meatrose',par:['Goldfish','EggPlant','Corium'],pools:['CHICKEN','COW','EDIBLE','FISH','FLOWER']},
  {out:'Melon',par:['Pumpkin','BonsaiJungle'],pools:['EDIBLE','GREEN','HEALING','POTION_INGREDIENT','STEM']},
  {out:'MilkWart',par:['Corium','Netherwart'],pools:['COW','EDIBLE','HEALING']},
  {out:'Moss',par:['Ivy','FloweringVine'],pools:['CLIMBABLE','GREEN','TENDRILLY','TWILIGHT_FOREST']},
  {out:'Necrobloom',par:['Spidernip','PurpleTulip'],pools:['DANGEROUS','FLOWER','POISONOUS','PURPLE']},
  {out:'NetherStoneLily',par:['StoneLily','Netherwart'],pools:['NETHER','RED','STONE']},
  {out:'Netherwart',par:['RedMushroom','BrownMushroom'],pools:['NETHER','POTION_INGREDIENT','RED']},
  {out:'Nickelback',par:['Ferrofern','Coppon'],pools:['FIERY','METALLIC']},
  {out:'Onion',par:['Allium','Carrot'],pools:['BROWN','EDIBLE','ROOT']},
  {out:'OrangeTulip',par:['RedTulip','Dandelion'],pools:['FLOWER','ORANGE','TULIP']},
  {out:'OxeyeDaisy',par:['AzureBluet','Dandelion'],pools:['FLOWER','WHITE']},
  {out:'Papyrus',par:['Corium','BonsaiBirch'],pools:['STEM','WHITE']},
  {out:'PinkTulip',par:['RedTulip','WhiteTulip'],pools:['FLOWER','RED','TULIP']},
  {out:'Plumbilia',par:['Coppon','Withereed'],pools:['DENSE','LEAD','METALLIC','REED']},
  {out:'Plumbshade',par:['AzureBluet','Malaxia','BlackGraniteLily'],pools:['BUSH','DENSE','LEAD','LEAFY','METALLIC','PURPLE']},
  {out:'Poppy',par:['BlueOrchid','Waterlily'],pools:['FLOWER','RED']},
  {out:'Pumpkin',par:['Carrot','SugarCane'],pools:['EDIBLE','ORANGE','STEM']},
  {out:'PurpleGlowshroom',par:['BlueGlowshroom','BlueOrchid','Glowflower'],pools:['EDIBLE','EMISSIVE','MUSHROOM','NETHER','POTION_INGREDIENT','PURPLE']},
  {out:'PurpleTulip',par:['RedTulip','BlueOrchid'],pools:['FLOWER','PURPLE','TULIP']},
  {out:'Pyrolusium',par:['Nickelback','Bauxia'],pools:['BUSH','METALLIC']},
  {out:'Raspberry',par:['RedTulip','OxeyeDaisy'],pools:['BERRY','BUSH','EDIBLE','RED']},
  {out:'RedGraniteLily',par:['StoneLily','Poppy'],pools:['RED','STONE']},
  {out:'RedMushroom',par:['Pumpkin','Poppy'],pools:['EDIBLE','MUSHROOM','RED']},
  {out:'RedStraw',par:['NetherStoneLily','Wheat'],pools:['EMISSIVE','POTION_INGREDIENT','RED','STONE','WHEAT']},
  {out:'RedTulip',par:['Poppy','WhiteTulip'],pools:['FLOWER','RED','TULIP']},
  {out:'Rubyne',par:['RedStraw','Diareed'],pools:['CRYSTALLINE','RED','SHINY']},
  {out:'SaguaroCactus',par:['Cactus','SandLily'],pools:['CACTUS','DANGEROUS','EDIBLE','GREEN']},
  {out:'SaltyRoot',par:['SugarBeet','Canola'],pools:['GRAY','ROOT','SALTPETER']},
  {out:'SandLily',par:['StoneLily','Cactus'],pools:['STONE','YELLOW']},
  {out:'Sapphirum',par:['EvilOre','Lazulia'],pools:['CRYSTALLINE','METALLIC','SHINY']},
  {out:'Shimmerleaf',par:['WhiteTulip','RedStraw'],pools:['EMISSIVE','GRAY','MAGICAL','POISONOUS','SILVER']},
  {out:'Silviscus',par:['Cassitine','Malaxia','MarbleLily'],pools:['BUSH','LEAFY','METALLIC','SILVER','WHITE']},
  {out:'Skyberry',par:['Dayflower','Blueberry'],pools:['ADDICTIVE','BERRY','BLUE','BUSH','DANGEROUS','EDIBLE','NETHER','POISONOUS','POTION_INGREDIENT']},
  {out:'Slimeplant',par:['BlueOrchid','ClayLily'],pools:['BUSH','EVIL','GREEN','POTION_INGREDIENT','STICKY']},
  {out:'Snowbell',par:['Belladonna','GlintWeed'],pools:['FLOWER','POISONOUS','POTION_INGREDIENT','WHITE']},
  {out:'SoulSandLily',par:['NetherStoneLily','SandLily'],pools:['BROWN','DANGEROUS','NETHER','OIL','STONE']},
  {out:'SpanishMoss',par:['Moss','EmberMoss'],pools:['CLIMBABLE','GREEN','MAGICAL']},
  {out:'Spidernip',par:['Flax','Hemp','Zomplant'],pools:['ADDICTIVE','EDIBLE','EVIL','POISONOUS','POTION_INGREDIENT','SILK','WHITE']},
  {out:'Steeleafranks',par:['Torchberry','KnightmetalBerry'],pools:['GREEN','IRON','METALLIC','TENDRILLY','TWILIGHT_FOREST']},
  {out:'StickyCane',par:['BonsaiJungle','SugarCane'],pools:['GREEN','REED','STICKY']},
  {out:'Stingberry',par:['Thornvine','SaguaroCactus'],pools:['ADDICTIVE','BERRY','BROWN','BUSH','DANGEROUS','EDIBLE','NETHER','POISONOUS','POTION_INGREDIENT']},
  {out:'StoneLily',par:['Vine','Pumpkin'],pools:['GRAY','STONE']},
  {out:'Strawberry',par:['Wheat','Raspberry'],pools:['BERRY','BUSH','EDIBLE','RED']},
  {out:'SugarBeet',par:['SugarCane','Allium'],pools:['ADDICTIVE','EDIBLE','POTION_INGREDIENT','ROOT','WHITE']},
  {out:'SugarCane',par:['Carrot','Potato'],pools:['EDIBLE','GREEN','REED']},
  {out:'Tea',par:['Blueberry','BonsaiJungle'],pools:['EDIBLE','GREEN','LEAFY']},
  {out:'Tearstalks',par:['Goldfish','SoulSandLily','NetherStoneLily'],pools:['EVIL','HEALING','NETHER','POTION_INGREDIENT','STEM','WHITE']},
  {out:'ThauminiteOreBerry',par:['ThaumiumOreBerry','ManaBean'],pools:['BLUE','DANGEROUS','MAGICAL','METALLIC','ORE_BERRY','VOID_TOUCHED']},
  {out:'Thiosulfine',par:['Galvania','Plumbilia'],pools:['DANGEROUS','FLOWER','SULFUR','YELLOW']},
  {out:'Thornvine',par:['Vine','Cactus'],pools:['CLIMBABLE','DANGEROUS','EMISSIVE','NETHER','TENDRILLY','YELLOW']},
  {out:'TinOreBerry',par:['Cassitine','BoPBerry','StoneLily'],pools:['DANGEROUS','METALLIC','ORE_BERRY','SHINY','TIN','WHITE']},
  {out:'Tine',par:['StoneLily','BonsaiSpruce'],pools:['BUSH','METALLIC','SHINY','TIN']},
  {out:'Tomato',par:['Onion','RedTulip'],pools:['EDIBLE','LEAFY','RED','TENDRILLY']},
  {out:'Torchberry',par:['Glowflower','BoPBerry'],pools:['BERRY','EMISSIVE','TWILIGHT_FOREST','YELLOW']},
  {out:'TuffLily',par:['BlackGraniteLily','AndesiteLily'],pools:['DARK','GRAY','STONE']},
  {out:'Turnip',par:['Potato','BoPBerry'],pools:['EDIBLE','PURPLE','ROOT']},
  {out:'Vine',par:['Pumpkin','BlueOrchid'],pools:['CLIMBABLE','GREEN','TENDRILLY']},
  {out:'VoidOreBerry',par:['ThaumiumOreBerry','StoneLily','GoldOreBerry'],pools:['MAGICAL','VOID_TOUCHED']},
  {out:'WaterArtichoke',par:['Waterlily','Hops'],pools:['BLUE','EDIBLE','FLOWER','POTION_INGREDIENT','WATERY']},
  {out:'Waterlily',par:['Vine','SugarCane'],pools:['GREEN','WATERY']},
  {out:'WhiteTulip',par:['PinkTulip','OxeyeDaisy'],pools:['FLOWER','TULIP','WHITE']},
  {out:'WildCarrot',par:['Carrot','BoPBerry'],pools:['EDIBLE','ROOT','WHITE']},
  {out:'Withereed',par:['BasaltLily','BlackGraniteLily'],pools:['COAL','FIERY','REED','STEM','SULFUR','UNDEAD']},
  {out:'Wolfsbane',par:['WaterArtichoke','Belladonna'],pools:['FLOWER','POISONOUS','POTION_INGREDIENT','PURPLE']},
  {out:'Zomplant',par:['Withereed','Eyebulb'],pools:['BROWN','EDIBLE','EVIL','POISONOUS','UNDEAD']},
  {out:'BonsaiSlimy',par:['Slimeplant','BonsaiJungle','BonsaiRubber'],pools:['STICKY','TREE','WOODEN'],machine:true},
  {out:'Bauxia',par:['Galvania','Nickelback'],pools:['STONE'],machine:true},
  {out:'Garnydinia',par:['Diareed','RedStraw'],pools:['STONE'],machine:true},
  {out:'GodOfThunder',par:['BobsYerUncleRanks','Withereed'],pools:['STONE'],machine:true},
  {out:'Iridine',par:['Scheelinium','Platina'],pools:['FLOWER','STONE'],machine:true},
  {out:'MagicalNightshade',par:['PrimordialBerry','ManaBean','Cinderpearl','Shimmerleaf'],pools:['MAGICAL'],machine:true},
  {out:'Micadia',par:['Tine','Bauxia'],pools:['STONE'],machine:true},
  {out:'OilBerry',par:['SoulSandLily','Withereed'],pools:['OIL'],machine:true},
  {out:'Olivia',par:['EndStoneLily','EvilOre'],pools:['STONE'],machine:true},
  {out:'Osmianth',par:['Platina','Scheelinium'],pools:['FLOWER','STONE'],machine:true},
  {out:'Platina',par:['Diareed','Rubyne'],pools:['STONE'],machine:true},
  {out:'Reactoria',par:['Titania','GodOfThunder'],pools:[],machine:true},
  {out:'Scheelinium',par:['Titania','Pyrolusium','EndStoneLily'],pools:['STONE'],machine:true},
  {out:'SpaceFlower',par:['EndStoneLily','Titania'],pools:['FLOWER'],machine:true},
  {out:'Stargatium',par:['Iridine','Trollplant'],pools:['STONE'],machine:true},
  {out:'StarWart',par:['Withereed','Titania','GodOfThunder'],pools:['NETHER','STONE'],machine:true},
  {out:'Titania',par:['Bauxia','RedStraw'],pools:['STONE'],machine:true},
  {out:'Transformium',par:['Trollplant','Bauxia','Titania'],pools:[],machine:true},
];
const POOL_MAP = {"ADDICTIVE": ["Blightberry", "Cocoa", "Coffee", "Dayflower", "Duskberry", "EggPlant", "Flax", "Goldfish", "Hemp", "Skyberry", "Spidernip", "Stingberry", "SugarBeet"], "ALIEN": ["EndStoneLily", "Enderbloom"], "BEAN": ["Cocoa", "Coffee", "ManaBean"], "BERRY": ["Blackberry", "Blightberry", "Blueberry", "BoPBerry", "BobsYerUncleRanks", "Duskberry", "Huckleberry", "Maloberry", "Raspberry", "Skyberry", "Stingberry", "Strawberry", "Torchberry"], "BLACK": ["BasaltLily", "BlackGraniteLily", "Blackberry", "DeepslateLily", "InkBloom"], "BLAZE": ["Blazereed", "Cinderpearl"], "BLUE": ["BlueGlowshroom", "Blueberry", "CobaltOreBerry", "Dayflower", "Diareed", "Flax", "Glowflower", "Indigo", "Lazulia", "Skyberry", "ThauminiteOreBerry", "WaterArtichoke"], "BROWN": ["BonsaiDarkOak", "BonsaiJungle", "BonsaiOak", "BonsaiRubber", "BonsaiSpruce", "BrownMushroom", "Cocoa", "Coffee", "Corpseplant", "Fertilia", "Liveroot", "ManaBean", "Mandrake", "Onion", "SoulSandLily", "Stingberry", "Zomplant"], "BUSH": ["Blackberry", "Blightberry", "Blueberry", "BoPBerry", "Cassitine", "Coppon", "Duskberry", "Galvania", "Huckleberry", "Malaxia", "Maloberry", "Plumbshade", "Pyrolusium", "Raspberry", "Silviscus", "Skyberry", "Slimeplant", "Stingberry", "Strawberry", "Tine"], "CACTUS": ["Cactus", "SaguaroCactus"], "CHICKEN": ["EggPlant", "Meatrose"], "CLIMBABLE": ["EmberMoss", "FloweringVine", "Grape", "Ivy", "Moss", "SpanishMoss", "Thornvine", "Vine"], "COAL": ["Creeperweed", "Diareed", "Withereed"], "COPPER": ["CopperOreBerry", "Coppon", "Malaxia"], "COTTON": ["Coppon", "Cotton"], "COW": ["Corium", "Meatrose", "MilkWart"], "CRYSTALLINE": ["BobsYerUncleRanks", "Diareed", "EvilOre", "Glowheat", "Lazulia", "Rubyne", "Sapphirum"], "DANGEROUS": ["AluminiumOreBerry", "ArditeOreBerry", "Bamboo", "Blightberry", "Cactus", "CobaltOreBerry", "CopperOreBerry", "Duskberry", "EmberMoss", "EssenceOreBerry", "GoldOreBerry", "Goldfish", "IronOreBerry", "Ivy", "KnightmetalBerry", "Mandrake", "Necrobloom", "SaguaroCactus", "Skyberry", "SoulSandLily", "Stingberry", "ThauminiteOreBerry", "ThaumiumOreBerry", "Thiosulfine", "Thornvine", "TinOreBerry"], "DARK": ["BasaltLily", "BlackGraniteLily", "BonsaiDarkOak", "DeepslateLily", "TuffLily"], "DENSE": ["Auronia", "DeepslateLily", "GoldOreBerry", "Plumbilia", "Plumbshade"], "EDIBLE": ["Barley", "Blackberry", "Blightberry", "BlueGlowshroom", "Blueberry", "BoPBerry", "BonsaiDarkOak", "BonsaiOak", "BrownMushroom", "Canola", "Chilly", "Cocoa", "Coffee", "Corpseplant", "Cucumber", "Duskberry", "EggPlant", "EssenceOreBerry", "Garlic", "Goldfish", "Grape", "Hops", "Huckleberry", "Lemon", "Maloberry", "Meatrose", "Melon", "MilkWart", "Onion", "Potato", "Pumpkin", "PurpleGlowshroom", "Raspberry", "RedMushroom", "SaguaroCactus", "Skyberry", "Spidernip", "Stingberry", "Strawberry", "SugarBeet", "SugarCane", "Tea", "Tomato", "Turnip", "WaterArtichoke", "Wheat", "WildCarrot", "Zomplant"], "EMISSIVE": ["BlueGlowshroom", "Glowflower", "Glowheat", "GlowingCoral", "Glowshroom", "PurpleGlowshroom", "RedStraw", "Shimmerleaf", "Thornvine", "Torchberry"], "EVIL": ["Blazereed", "Corpseplant", "Creeperweed", "EvilOre", "Eyebulb", "Mandrake", "Slimeplant", "Spidernip", "Tearstalks", "Zomplant"], "FIERY": ["Blazereed", "Chilly", "Creeperweed", "Diareed", "EmberMoss", "EvilOre", "Nickelback", "Withereed"], "FISH": ["Goldfish", "Meatrose"], "FLOWER": ["Allium", "AzureBluet", "Belladonna", "Dayflower", "EggPlant", "Enderbloom", "FloweringVine", "GlintWeed", "Indigo", "InkBloom", "Iridine", "Ivy", "Mandrake", "Meatrose", "Necrobloom", "OrangeTulip", "Osmianth", "OxeyeDaisy", "PinkTulip", "Poppy", "PurpleTulip", "RedTulip", "Snowbell", "SpaceFlower", "Thiosulfine", "WaterArtichoke", "WhiteTulip", "Wolfsbane"], "GOLD": ["Auronia", "GoldOreBerry"], "GRAY": ["AndesiteLily", "Cassitine", "ClayLily", "Duskberry", "Ferrofern", "IronOreBerry", "KnightmetalBerry", "SaltyRoot", "Shimmerleaf", "StoneLily", "TuffLily"], "GREEN": ["Bamboo", "Barley", "Blightberry", "BobsYerUncleRanks", "Cactus", "Cucumber", "EssenceOreBerry", "FloweringVine", "Glowshroom", "Hemp", "Hops", "Ivy", "Melon", "Moss", "SaguaroCactus", "Slimeplant", "SpanishMoss", "Steeleafranks", "StickyCane", "SugarCane", "Tea", "Vine", "Waterlily"], "HEALING": ["Blightberry", "Fertilia", "Lazulia", "Melon", "MilkWart", "Tearstalks"], "IRON": ["Ferrofern", "IronOreBerry", "Steeleafranks"], "LEAD": ["Plumbilia", "Plumbshade"], "LEAFY": ["Bamboo", "BonsaiAcacia", "BonsaiBirch", "BonsaiDarkOak", "BonsaiJungle", "BonsaiOak", "Cassitine", "Cocoa", "Coffee", "Grape", "Huckleberry", "Lemon", "Malaxia", "Plumbshade", "Silviscus", "Tea", "Tomato"], "MAGICAL": ["Cinderpearl", "Enderbloom", "GlintWeed", "MagicalNightshade", "ManaBean", "Mandrake", "Shimmerleaf", "SpanishMoss", "ThauminiteOreBerry", "ThaumiumOreBerry", "VoidOreBerry"], "METALLIC": ["AluminiumOreBerry", "ArditeOreBerry", "Argentia", "Auronia", "Cassitine", "CobaltOreBerry", "CopperOreBerry", "Coppon", "Ferrofern", "Galvania", "GoldOreBerry", "IronOreBerry", "KnightmetalBerry", "Malaxia", "Nickelback", "Plumbilia", "Plumbshade", "Pyrolusium", "Sapphirum", "Silviscus", "Steeleafranks", "ThauminiteOreBerry", "ThaumiumOreBerry", "TinOreBerry", "Tine"], "MUSHROOM": ["BlueGlowshroom", "BrownMushroom", "Fertilia", "Glowshroom", "PurpleGlowshroom", "RedMushroom"], "NETHER": ["Blazereed", "Blightberry", "BlueGlowshroom", "CobaltOreBerry", "Duskberry", "EvilOre", "Eyebulb", "GaiaWart", "Glowflower", "Glowshroom", "Goldfish", "NetherStoneLily", "Netherwart", "PurpleGlowshroom", "Skyberry", "SoulSandLily", "StarWart", "Stingberry", "Tearstalks", "Thornvine"], "OIL": ["Canola", "OilBerry", "SoulSandLily"], "ORANGE": ["ArditeOreBerry", "BonsaiAcacia", "Cinderpearl", "CopperOreBerry", "Coppon", "GlintWeed", "Malaxia", "OrangeTulip", "Pumpkin"], "ORE_BERRY": ["AluminiumOreBerry", "ArditeOreBerry", "CobaltOreBerry", "CopperOreBerry", "EssenceOreBerry", "GoldOreBerry", "IronOreBerry", "KnightmetalBerry", "ThauminiteOreBerry", "ThaumiumOreBerry", "TinOreBerry"], "POISONOUS": ["Belladonna", "Blightberry", "Corpseplant", "Duskberry", "Ivy", "Necrobloom", "Shimmerleaf", "Skyberry", "Snowbell", "Spidernip", "Stingberry", "Wolfsbane", "Zomplant"], "POTION_INGREDIENT": ["Belladonna", "Blazereed", "Blightberry", "BlueGlowshroom", "Creeperweed", "Duskberry", "EmberMoss", "Garlic", "Glowflower", "Glowheat", "GlowingCoral", "Glowshroom", "Mandrake", "Melon", "Netherwart", "PurpleGlowshroom", "RedStraw", "Skyberry", "Slimeplant", "Snowbell", "Spidernip", "Stingberry", "SugarBeet", "Tearstalks", "WaterArtichoke", "Wolfsbane"], "PURPLE": ["Allium", "Belladonna", "GlowingCoral", "Grape", "Huckleberry", "Necrobloom", "Plumbshade", "PurpleGlowshroom", "PurpleTulip", "ThaumiumOreBerry", "Turnip", "Wolfsbane"], "RED": ["BoPBerry", "Chilly", "EmberMoss", "Eyebulb", "GraniteLily", "NetherStoneLily", "Netherwart", "PinkTulip", "Poppy", "Raspberry", "RedGraniteLily", "RedMushroom", "RedStraw", "RedTulip", "Rubyne", "Strawberry", "Tomato"], "REED": ["Blazereed", "Diareed", "Plumbilia", "StickyCane", "SugarCane", "Withereed"], "ROOT": ["Allium", "Garlic", "Liveroot", "Onion", "Potato", "SaltyRoot", "SugarBeet", "Turnip", "WildCarrot"], "SALTPETER": ["Creeperweed", "SaltyRoot"], "SHINY": ["Argentia", "BobsYerUncleRanks", "Cassitine", "CopperOreBerry", "Coppon", "Diareed", "Enderbloom", "Glowflower", "Glowheat", "GlowingCoral", "Lazulia", "Rubyne", "Sapphirum", "TinOreBerry", "Tine"], "SILK": ["Corium", "Cotton", "Flax", "Hemp", "Spidernip"], "SILVER": ["Argentia", "Shimmerleaf", "Silviscus"], "STEM": ["Bamboo", "Hemp", "Melon", "Papyrus", "Pumpkin", "Tearstalks", "Withereed"], "STICKY": ["BonsaiRubber", "BonsaiSlimy", "Slimeplant", "StickyCane"], "STONE": ["AndesiteLily", "BasaltLily", "BlackGraniteLily", "ClayLily", "DeepslateLily", "DioriteLily", "EndStoneLily", "Garnydinia", "GodOfThunder", "GraniteLily", "Iridine", "MarbleLily", "Micadia", "NetherStoneLily", "Olivia", "Osmianth", "Platina", "Reactoria", "RedGraniteLily", "RedStraw", "SandLily", "Scheelinium", "SoulSandLily", "StarWart", "Stargatium", "StoneLily", "Titania", "TuffLily"], "SULFUR": ["Blazereed", "Creeperweed", "Thiosulfine", "Withereed"], "TENDRILLY": ["Argentia", "Auronia", "BobsYerUncleRanks", "Corium", "Corpseplant", "Cotton", "Creeperweed", "Cucumber", "EmberMoss", "Eyebulb", "Ferrofern", "FloweringVine", "Grape", "Ivy", "Liveroot", "Moss", "Steeleafranks", "Thornvine", "Tomato", "Vine"], "TIN": ["Cassitine", "TinOreBerry", "Tine"], "TREE": ["BonsaiAcacia", "BonsaiBirch", "BonsaiDarkOak", "BonsaiJungle", "BonsaiOak", "BonsaiRubber", "BonsaiSlimy", "BonsaiSpruce", "Cocoa", "Lemon"], "TULIP": ["OrangeTulip", "PinkTulip", "PurpleTulip", "RedTulip", "WhiteTulip"], "TWILIGHT_FOREST": ["KnightmetalBerry", "Liveroot", "Moss", "Steeleafranks", "Torchberry"], "UNDEAD": ["Corpseplant", "EssenceOreBerry", "Withereed", "Zomplant"], "VOID_TOUCHED": ["ThauminiteOreBerry", "ThaumiumOreBerry", "VoidOreBerry"], "WATERY": ["ClayLily", "GlowingCoral", "Goldfish", "InkBloom", "WaterArtichoke", "Waterlily"], "WHEAT": ["Barley", "Canola", "Flax", "Glowheat", "Hops", "RedStraw", "Wheat"], "WHITE": ["AluminiumOreBerry", "Argentia", "AzureBluet", "BonsaiBirch", "Cotton", "DioriteLily", "EvilOre", "Galvania", "Garlic", "MarbleLily", "OxeyeDaisy", "Papyrus", "Silviscus", "Snowbell", "Spidernip", "SugarBeet", "Tearstalks", "TinOreBerry", "WhiteTulip", "WildCarrot"], "WOODEN": ["BonsaiAcacia", "BonsaiBirch", "BonsaiDarkOak", "BonsaiJungle", "BonsaiOak", "BonsaiRubber", "BonsaiSlimy", "BonsaiSpruce", "Liveroot"], "YELLOW": ["Auronia", "Canola", "EndStoneLily", "GoldOreBerry", "Lemon", "Maloberry", "Potato", "SandLily", "Thiosulfine", "Thornvine", "Torchberry", "Wheat"]};
const CROP_POOLS = {"Allium": ["FLOWER", "PURPLE", "ROOT"], "AluminiumOreBerry": ["DANGEROUS", "METALLIC", "ORE_BERRY", "WHITE"], "AndesiteLily": ["GRAY", "STONE"], "ArditeOreBerry": ["DANGEROUS", "METALLIC", "ORANGE", "ORE_BERRY"], "Argentia": ["METALLIC", "SHINY", "SILVER", "TENDRILLY", "WHITE"], "Auronia": ["DENSE", "GOLD", "METALLIC", "TENDRILLY", "YELLOW"], "AzureBluet": ["FLOWER", "WHITE"], "Bamboo": ["DANGEROUS", "GREEN", "LEAFY", "STEM"], "Barley": ["EDIBLE", "GREEN", "WHEAT"], "BasaltLily": ["BLACK", "DARK", "STONE"], "Belladonna": ["FLOWER", "POISONOUS", "POTION_INGREDIENT", "PURPLE"], "BlackGraniteLily": ["BLACK", "DARK", "STONE"], "Blackberry": ["BERRY", "BLACK", "BUSH", "EDIBLE"], "Blazereed": ["BLAZE", "EVIL", "FIERY", "NETHER", "POTION_INGREDIENT", "REED", "SULFUR"], "Blightberry": ["ADDICTIVE", "BERRY", "BUSH", "DANGEROUS", "EDIBLE", "GREEN", "HEALING", "NETHER", "POISONOUS", "POTION_INGREDIENT"], "BlueGlowshroom": ["BLUE", "EDIBLE", "EMISSIVE", "MUSHROOM", "NETHER", "POTION_INGREDIENT"], "Blueberry": ["BERRY", "BLUE", "BUSH", "EDIBLE"], "BoPBerry": ["BERRY", "BUSH", "EDIBLE", "RED"], "BobsYerUncleRanks": ["BERRY", "CRYSTALLINE", "GREEN", "SHINY", "TENDRILLY"], "BonsaiAcacia": ["LEAFY", "ORANGE", "TREE", "WOODEN"], "BonsaiBirch": ["LEAFY", "TREE", "WHITE", "WOODEN"], "BonsaiDarkOak": ["BROWN", "DARK", "EDIBLE", "LEAFY", "TREE", "WOODEN"], "BonsaiJungle": ["BROWN", "LEAFY", "TREE", "WOODEN"], "BonsaiOak": ["BROWN", "EDIBLE", "LEAFY", "TREE", "WOODEN"], "BonsaiRubber": ["BROWN", "STICKY", "TREE", "WOODEN"], "BonsaiSlimy": ["STICKY", "TREE", "WOODEN"], "BonsaiSpruce": ["BROWN", "TREE", "WOODEN"], "BrownMushroom": ["BROWN", "EDIBLE", "MUSHROOM"], "Cactus": ["CACTUS", "DANGEROUS", "GREEN"], "Canola": ["EDIBLE", "OIL", "WHEAT", "YELLOW"], "Cassitine": ["BUSH", "GRAY", "LEAFY", "METALLIC", "SHINY", "TIN"], "Chilly": ["EDIBLE", "FIERY", "RED"], "Cinderpearl": ["BLAZE", "MAGICAL", "ORANGE"], "ClayLily": ["GRAY", "STONE", "WATERY"], "CobaltOreBerry": ["BLUE", "DANGEROUS", "METALLIC", "NETHER", "ORE_BERRY"], "Cocoa": ["ADDICTIVE", "BEAN", "BROWN", "EDIBLE", "LEAFY", "TREE"], "Coffee": ["ADDICTIVE", "BEAN", "BROWN", "EDIBLE", "LEAFY"], "CopperOreBerry": ["COPPER", "DANGEROUS", "METALLIC", "ORANGE", "ORE_BERRY", "SHINY"], "Coppon": ["BUSH", "COPPER", "COTTON", "METALLIC", "ORANGE", "SHINY"], "Corium": ["COW", "SILK", "TENDRILLY"], "Corpseplant": ["BROWN", "EDIBLE", "EVIL", "POISONOUS", "TENDRILLY", "UNDEAD"], "Cotton": ["COTTON", "SILK", "TENDRILLY", "WHITE"], "Creeperweed": ["COAL", "EVIL", "FIERY", "POTION_INGREDIENT", "SALTPETER", "SULFUR", "TENDRILLY"], "Cucumber": ["EDIBLE", "GREEN", "TENDRILLY"], "Dayflower": ["ADDICTIVE", "BLUE", "FLOWER"], "DeepslateLily": ["BLACK", "DARK", "DENSE", "STONE"], "Diareed": ["BLUE", "COAL", "CRYSTALLINE", "FIERY", "REED", "SHINY"], "DioriteLily": ["STONE", "WHITE"], "Duskberry": ["ADDICTIVE", "BERRY", "BUSH", "DANGEROUS", "EDIBLE", "GRAY", "NETHER", "POISONOUS", "POTION_INGREDIENT"], "EggPlant": ["ADDICTIVE", "CHICKEN", "EDIBLE", "FLOWER"], "EmberMoss": ["CLIMBABLE", "DANGEROUS", "FIERY", "POTION_INGREDIENT", "RED", "TENDRILLY"], "EndStoneLily": ["ALIEN", "STONE", "YELLOW"], "Enderbloom": ["ALIEN", "FLOWER", "MAGICAL", "SHINY"], "EssenceOreBerry": ["DANGEROUS", "EDIBLE", "GREEN", "ORE_BERRY", "UNDEAD"], "EvilOre": ["CRYSTALLINE", "EVIL", "FIERY", "NETHER", "WHITE"], "Eyebulb": ["EVIL", "NETHER", "RED", "TENDRILLY"], "Ferrofern": ["GRAY", "IRON", "METALLIC", "TENDRILLY"], "Fertilia": ["BROWN", "HEALING", "MUSHROOM"], "Flax": ["ADDICTIVE", "BLUE", "SILK", "WHEAT"], "FloweringVine": ["CLIMBABLE", "FLOWER", "GREEN", "TENDRILLY"], "GaiaWart": ["NETHER"], "Galvania": ["BUSH", "METALLIC", "WHITE"], "Garlic": ["EDIBLE", "POTION_INGREDIENT", "ROOT", "WHITE"], "Garnydinia": ["STONE"], "GlintWeed": ["FLOWER", "MAGICAL", "ORANGE"], "Glowflower": ["BLUE", "EMISSIVE", "NETHER", "POTION_INGREDIENT", "SHINY"], "Glowheat": ["CRYSTALLINE", "EMISSIVE", "POTION_INGREDIENT", "SHINY", "WHEAT"], "GlowingCoral": ["EMISSIVE", "POTION_INGREDIENT", "PURPLE", "SHINY", "WATERY"], "Glowshroom": ["EMISSIVE", "GREEN", "MUSHROOM", "NETHER", "POTION_INGREDIENT"], "GodOfThunder": ["STONE"], "GoldOreBerry": ["DANGEROUS", "DENSE", "GOLD", "METALLIC", "ORE_BERRY", "YELLOW"], "Goldfish": ["ADDICTIVE", "DANGEROUS", "EDIBLE", "FISH", "NETHER", "WATERY"], "GraniteLily": ["RED", "STONE"], "Grape": ["CLIMBABLE", "EDIBLE", "LEAFY", "PURPLE", "TENDRILLY"], "Hemp": ["ADDICTIVE", "GREEN", "SILK", "STEM"], "Hops": ["EDIBLE", "GREEN", "WHEAT"], "Huckleberry": ["BERRY", "BUSH", "EDIBLE", "LEAFY", "PURPLE"], "Indigo": ["BLUE", "FLOWER"], "InkBloom": ["BLACK", "FLOWER", "WATERY"], "Iridine": ["FLOWER", "STONE"], "IronOreBerry": ["DANGEROUS", "GRAY", "IRON", "METALLIC", "ORE_BERRY"], "Ivy": ["CLIMBABLE", "DANGEROUS", "FLOWER", "GREEN", "POISONOUS", "TENDRILLY"], "KnightmetalBerry": ["DANGEROUS", "GRAY", "METALLIC", "ORE_BERRY", "TWILIGHT_FOREST"], "Lazulia": ["BLUE", "CRYSTALLINE", "HEALING", "SHINY"], "Lemon": ["EDIBLE", "LEAFY", "TREE", "YELLOW"], "Liveroot": ["BROWN", "ROOT", "TENDRILLY", "TWILIGHT_FOREST", "WOODEN"], "MagicalNightshade": ["MAGICAL"], "Malaxia": ["BUSH", "COPPER", "LEAFY", "METALLIC", "ORANGE"], "Maloberry": ["BERRY", "BUSH", "EDIBLE", "YELLOW"], "ManaBean": ["BEAN", "BROWN", "MAGICAL"], "Mandrake": ["BROWN", "DANGEROUS", "EVIL", "FLOWER", "MAGICAL", "POTION_INGREDIENT"], "MarbleLily": ["STONE", "WHITE"], "Meatrose": ["CHICKEN", "COW", "EDIBLE", "FISH", "FLOWER"], "Melon": ["EDIBLE", "GREEN", "HEALING", "POTION_INGREDIENT", "STEM"], "Micadia": ["STONE"], "MilkWart": ["COW", "EDIBLE", "HEALING"], "Moss": ["CLIMBABLE", "GREEN", "TENDRILLY", "TWILIGHT_FOREST"], "Necrobloom": ["DANGEROUS", "FLOWER", "POISONOUS", "PURPLE"], "NetherStoneLily": ["NETHER", "RED", "STONE"], "Netherwart": ["NETHER", "POTION_INGREDIENT", "RED"], "Nickelback": ["FIERY", "METALLIC"], "OilBerry": ["OIL"], "Olivia": ["STONE"], "Onion": ["BROWN", "EDIBLE", "ROOT"], "OrangeTulip": ["FLOWER", "ORANGE", "TULIP"], "Osmianth": ["FLOWER", "STONE"], "OxeyeDaisy": ["FLOWER", "WHITE"], "Papyrus": ["STEM", "WHITE"], "PinkTulip": ["FLOWER", "RED", "TULIP"], "Platina": ["STONE"], "Plumbilia": ["DENSE", "LEAD", "METALLIC", "REED"], "Plumbshade": ["BUSH", "DENSE", "LEAD", "LEAFY", "METALLIC", "PURPLE"], "Poppy": ["FLOWER", "RED"], "Potato": ["EDIBLE", "ROOT", "YELLOW"], "Pumpkin": ["EDIBLE", "ORANGE", "STEM"], "PurpleGlowshroom": ["EDIBLE", "EMISSIVE", "MUSHROOM", "NETHER", "POTION_INGREDIENT", "PURPLE"], "PurpleTulip": ["FLOWER", "PURPLE", "TULIP"], "Pyrolusium": ["BUSH", "METALLIC"], "Raspberry": ["BERRY", "BUSH", "EDIBLE", "RED"], "Reactoria": ["STONE"], "RedGraniteLily": ["RED", "STONE"], "RedMushroom": ["EDIBLE", "MUSHROOM", "RED"], "RedStraw": ["EMISSIVE", "POTION_INGREDIENT", "RED", "STONE", "WHEAT"], "RedTulip": ["FLOWER", "RED", "TULIP"], "Rubyne": ["CRYSTALLINE", "RED", "SHINY"], "SaguaroCactus": ["CACTUS", "DANGEROUS", "EDIBLE", "GREEN"], "SaltyRoot": ["GRAY", "ROOT", "SALTPETER"], "SandLily": ["STONE", "YELLOW"], "Sapphirum": ["CRYSTALLINE", "METALLIC", "SHINY"], "Scheelinium": ["STONE"], "Shimmerleaf": ["EMISSIVE", "GRAY", "MAGICAL", "POISONOUS", "SILVER"], "Silviscus": ["BUSH", "LEAFY", "METALLIC", "SILVER", "WHITE"], "Skyberry": ["ADDICTIVE", "BERRY", "BLUE", "BUSH", "DANGEROUS", "EDIBLE", "NETHER", "POISONOUS", "POTION_INGREDIENT"], "Slimeplant": ["BUSH", "EVIL", "GREEN", "POTION_INGREDIENT", "STICKY"], "Snowbell": ["FLOWER", "POISONOUS", "POTION_INGREDIENT", "WHITE"], "SoulSandLily": ["BROWN", "DANGEROUS", "NETHER", "OIL", "STONE"], "SpaceFlower": ["FLOWER"], "SpanishMoss": ["CLIMBABLE", "GREEN", "MAGICAL"], "Spidernip": ["ADDICTIVE", "EDIBLE", "EVIL", "POISONOUS", "POTION_INGREDIENT", "SILK", "WHITE"], "StarWart": ["NETHER", "STONE"], "Stargatium": ["STONE"], "Steeleafranks": ["GREEN", "IRON", "METALLIC", "TENDRILLY", "TWILIGHT_FOREST"], "StickyCane": ["GREEN", "REED", "STICKY"], "Stingberry": ["ADDICTIVE", "BERRY", "BROWN", "BUSH", "DANGEROUS", "EDIBLE", "NETHER", "POISONOUS", "POTION_INGREDIENT"], "StoneLily": ["GRAY", "STONE"], "Strawberry": ["BERRY", "BUSH", "EDIBLE", "RED"], "SugarBeet": ["ADDICTIVE", "EDIBLE", "POTION_INGREDIENT", "ROOT", "WHITE"], "SugarCane": ["EDIBLE", "GREEN", "REED"], "Tea": ["EDIBLE", "GREEN", "LEAFY"], "Tearstalks": ["EVIL", "HEALING", "NETHER", "POTION_INGREDIENT", "STEM", "WHITE"], "ThauminiteOreBerry": ["BLUE", "DANGEROUS", "MAGICAL", "METALLIC", "ORE_BERRY", "VOID_TOUCHED"], "ThaumiumOreBerry": ["DANGEROUS", "MAGICAL", "METALLIC", "ORE_BERRY", "PURPLE", "VOID_TOUCHED"], "Thiosulfine": ["DANGEROUS", "FLOWER", "SULFUR", "YELLOW"], "Thornvine": ["CLIMBABLE", "DANGEROUS", "EMISSIVE", "NETHER", "TENDRILLY", "YELLOW"], "TinOreBerry": ["DANGEROUS", "METALLIC", "ORE_BERRY", "SHINY", "TIN", "WHITE"], "Tine": ["BUSH", "METALLIC", "SHINY", "TIN"], "Titania": ["STONE"], "Tomato": ["EDIBLE", "LEAFY", "RED", "TENDRILLY"], "Torchberry": ["BERRY", "EMISSIVE", "TWILIGHT_FOREST", "YELLOW"], "TuffLily": ["DARK", "GRAY", "STONE"], "Turnip": ["EDIBLE", "PURPLE", "ROOT"], "Vine": ["CLIMBABLE", "GREEN", "TENDRILLY"], "VoidOreBerry": ["MAGICAL", "VOID_TOUCHED"], "WaterArtichoke": ["BLUE", "EDIBLE", "FLOWER", "POTION_INGREDIENT", "WATERY"], "Waterlily": ["GREEN", "WATERY"], "Wheat": ["EDIBLE", "WHEAT", "YELLOW"], "WhiteTulip": ["FLOWER", "TULIP", "WHITE"], "WildCarrot": ["EDIBLE", "ROOT", "WHITE"], "Withereed": ["COAL", "FIERY", "REED", "STEM", "SULFUR", "UNDEAD"], "Wolfsbane": ["FLOWER", "POISONOUS", "POTION_INGREDIENT", "PURPLE"], "Zomplant": ["BROWN", "EDIBLE", "EVIL", "POISONOUS", "UNDEAD"]};

const DIRECT_POOL_REGISTRATIONS = {"Carrot": ["EDIBLE", "ORANGE", "ROOT"], "Dandelion": ["FLOWER", "YELLOW"], "Poppy": ["FLOWER", "RED"], "Potato": ["EDIBLE", "ROOT", "YELLOW"], "Wheat": ["EDIBLE", "WHEAT", "YELLOW"]};


// Biome tags and rainfall — verified against GTNH biome table
const BIOMES={
  "Ocean":["OCEAN"],
  "Plains":["PLAINS"],
  "Desert":["HOT","DRY","SANDY"],
  "Extreme Hills":["MOUNTAIN","HILLS"],
  "Forest":["FOREST"],
  "Taiga":["COLD","CONIFEROUS","FOREST"],
  "Swampland":["WET","SWAMP"],
  "River":["RIVER"],
  "Hell":["HOT","DRY","NETHER"],
  "Sky":["COLD","DRY","END"],
  "FrozenOcean":["COLD","OCEAN","SNOWY"],
  "FrozenRiver":["COLD","RIVER","SNOWY"],
  "Ice Plains":["COLD","SNOWY","WASTELAND"],
  "Ice Mountains":["COLD","MOUNTAIN","SNOWY"],
  "MushroomIsland":["MUSHROOM"],
  "MushroomIslandShore":["MUSHROOM","BEACH"],
  "Beach":["BEACH"],
  "DesertHills":["HOT","DRY","HILLS","SANDY"],
  "ForestHills":["FOREST","HILLS"],
  "TaigaHills":["COLD","CONIFEROUS","FOREST","HILLS"],
  "Extreme Hills Edge":["MOUNTAIN"],
  "Jungle":["HOT","DENSE","WET","JUNGLE"],
  "JungleHills":["HOT","DENSE","WET","JUNGLE","HILLS"],
  "JungleEdge":["HOT","WET","JUNGLE","FOREST"],
  "Deep Ocean":["OCEAN"],
  "Stone Beach":["BEACH"],
  "Cold Beach":["COLD","SNOWY","BEACH"],
  "Birch Forest":["FOREST"],
  "Birch Forest Hills":["FOREST","HILLS"],
  "Roofed Forest":["DENSE","SPOOKY","FOREST"],
  "Cold Taiga":["COLD","CONIFEROUS","FOREST","SNOWY"],
  "Cold Taiga Hills":["COLD","CONIFEROUS","FOREST","HILLS","SNOWY"],
  "Mega Taiga":["COLD","CONIFEROUS","FOREST"],
  "Mega Taiga Hills":["COLD","CONIFEROUS","FOREST","HILLS"],
  "Extreme Hills+":["SPARSE","FOREST","MOUNTAIN"],
  "Savanna":["HOT","SPARSE","SAVANNA","PLAINS"],
  "Savanna Plateau":["HOT","SPARSE","SAVANNA","PLAINS"],
  "Mesa":["MESA","SANDY"],
  "Mesa Plateau F":["SPARSE","MESA","SANDY"],
  "Mesa Plateau":["MESA","SANDY"],
  "Alps Forest":["COLD","FOREST","MOUNTAIN","SNOWY"],
  "Alps":["COLD","MOUNTAIN","SNOWY"],
  "Arctic":["COLD","DEAD","SNOWY","WASTELAND"],
  "Bamboo Forest":["DENSE","JUNGLE","LUSH","FOREST"],
  "Bayou":["WET","LUSH","OCEAN","RIVER","SWAMP"],
  "Bog":["WET","DEAD","FOREST","SWAMP"],
  "Boreal Forest":["DENSE","CONIFEROUS","LUSH","FOREST"],
  "Brushland":["HOT","DRY","SAVANNA","PLAINS"],
  "Canyon":["HOT","SPARSE","DRY","MOUNTAIN","HILLS","SANDY"],
  "Canyon Ravine":["HOT","DRY","HILLS","SANDY"],
  "Chaparral":["SPARSE","PLAINS"],
  "Cherry Blossom Grove":["LUSH","MAGICAL","FOREST"],
  "Coniferous Forest":["DENSE","CONIFEROUS","FOREST","HILLS"],
  "Coral Reef":["OCEAN","RIVER"],
  "Crag":["DRY","SPOOKY","DEAD","MOUNTAIN","WASTELAND"],
  "Dead Forest":["SPARSE","SPOOKY","DEAD","FOREST"],
  "Dead Swamp":["SPARSE","SPOOKY","DEAD","SWAMP"],
  "Deciduous Forest":["DENSE","DRY","FOREST"],
  "Dry River":["HOT","DRY","PLAINS","SANDY"],
  "Eucalyptus Forest":["HOT","WET","PLAINS"],
  "Fen":["WET","DEAD","FOREST","SWAMP"],
  "Flower Field":["LUSH","PLAINS"],
  "Frost Forest":["COLD","SPARSE","FOREST","SNOWY"],
  "Fungi Forest":["WET","LUSH","MUSHROOM","MAGICAL","FOREST","SWAMP"],
  "Garden":["LUSH","MAGICAL","PLAINS"],
  "Glacier":["COLD","DEAD","HILLS","SNOWY"],
  "Grassland":["SPARSE","LUSH","PLAINS","HILLS","SWAMP"],
  "Grove":["DENSE","LUSH","FOREST","PLAINS"],
  "Heathland":["DRY","SAVANNA","PLAINS"],
  "Highland":["SPARSE","MOUNTAIN","HILLS"],
  "Jade Cliffs":["DENSE","FOREST","MOUNTAIN"],
  "Kelp Forest":["OCEAN","RIVER","FOREST"],
  "Land of Lakes":["WET","PLAINS"],
  "Land of Lakes Marsh":["WET","SWAMP"],
  "Lavender Fields":["SPARSE","LUSH","PLAINS"],
  "Lush Desert":["HOT","DRY","SAVANNA","LUSH","SANDY"],
  "Lush River":["RIVER","PLAINS"],
  "Lush Swamp":["WET","LUSH","OCEAN","RIVER","SWAMP"],
  "Mangrove":["WET","LUSH","OCEAN","RIVER","FOREST"],
  "Maple Woods":["COLD","FOREST"],
  "Marsh":["SPARSE","WET","LUSH","OCEAN","RIVER","SWAMP"],
  "Meadow Forest":["LUSH","FOREST","PLAINS"],
  "Meadow":["LUSH","FOREST","PLAINS"],
  "Moor":["SPARSE","WET","HILLS","SWAMP"],
  "Mountain":["DRY","FOREST","MOUNTAIN"],
  "Mystic Grove":["WET","LUSH","MAGICAL","FOREST"],
  "Oasis":["HOT","DRY","JUNGLE","LUSH","SANDY"],
  "Ominous Woods":["SPOOKY","DEAD","MAGICAL","FOREST","SWAMP"],
  "Orchard":["SPARSE","LUSH","FOREST","PLAINS"],
  "Origin Valley":["PLAINS"],
  "Outback":["HOT","DRY","SAVANNA","PLAINS","SANDY"],
  "Polar Chasm":["HOT","DRY","SAVANNA","PLAINS"],
  "Prairie":["SPARSE","DRY","PLAINS"],
  "Quagmire":["WET","SPOOKY","DEAD","SWAMP","WASTELAND"],
  "Rainforest":["DENSE","WET","JUNGLE","LUSH","FOREST","HILLS"],
  "Redwood Forest":["DENSE","CONIFEROUS","FOREST"],
  "Sacred Springs":["DENSE","WET","LUSH","MAGICAL","FOREST","MOUNTAIN"],
  "Scrubland":["HOT","SPARSE","DRY","SAVANNA","PLAINS"],
  "Seasonal Forest Clearing":["PLAINS"],
  "Seasonal Forest":["DENSE","LUSH","FOREST"],
  "Shield":["WET","CONIFEROUS","OCEAN","RIVER","FOREST"],
  "Shrubland":["SPARSE","DRY","PLAINS"],
  "Silkglades":["SPOOKY","DEAD","FOREST","SWAMP"],
  "Sludgepit":["WET","SPOOKY","DEAD","FOREST","SWAMP","WASTELAND"],
  "Snowy Coniferous Forest":["COLD","DENSE","CONIFEROUS","FOREST","HILLS","SNOWY"],
  "Spectral Garden":["HOT","DRY","SAVANNA","PLAINS"],
  "Spruce Woods":["DENSE","CONIFEROUS","LUSH","FOREST"],
  "Steppe":["HOT","SPARSE","DRY","SAVANNA","DEAD","PLAINS","SANDY"],
  "Temperate Rainforest":["WET","CONIFEROUS","LUSH","FOREST","HILLS"],
  "Thicket":["DENSE","DRY","DEAD","FOREST","PLAINS"],
  "Tropical Rainforest":["HOT","DENSE","WET","JUNGLE","LUSH"],
  "Tropics":["WET","JUNGLE","LUSH","OCEAN","RIVER","BEACH"],
  "Tundra":["COLD","SPARSE","DRY","DEAD","WASTELAND"],
  "Visceral Heap":["SPOOKY","NETHER"],
  "Volcano":["HOT","DRY","MOUNTAIN","WASTELAND"],
  "Wasteland":["SPARSE","SPOOKY","DEAD","WASTELAND"],
  "Wetland":["DENSE","WET","LUSH","FOREST","SWAMP"],
  "Woodland":["DENSE","DRY","FOREST"],
  "Xeric Shrubland":["HOT","PLAINS","SANDY"],
  "Dense Forest":["PLAINS"],
  "Ocean Oil Field":["OCEAN","RIVER"],
  "Desert Oil Field":["SANDY"],
  "Boneyard":["SPOOKY","NETHER","WASTELAND"],
  "Sunflower Plains":["PLAINS"],
  "Desert M":["HOT","DRY","PLAINS","SANDY"],
  "Extreme Hills M":["HILLS"],
  "Flower Forest":["FOREST","HILLS"],
  "Taiga M":["HILLS"],
  "Swampland M":["WET","SWAMP"],
  "Corrupted Sands":["SPOOKY","NETHER","SANDY"],
  "Phantasmagoric Inferno":["SPOOKY","NETHER"],
  "Undergarden":["JUNGLE","SPOOKY","NETHER"],
  "Ice Plains Spikes":["COLD","HILLS","SNOWY"],
  "moon":["COLD","DRY","DEAD"],
  "marsFlat":["COLD","DRY","DEAD","SANDY"],
  "asteroids":["COLD","DRY","SPOOKY","DEAD"],
  "space":["DRY","PLAINS"],
  "Jungle M":["HOT","WET","HILLS"],
  "JungleEdge M":["HOT","HILLS"],
  "Birch Forest M":["HILLS"],
  "Birch Forest Hills M":["HILLS"],
  "Roofed Forest M":["HILLS"],
  "Cold Taiga M":["COLD","HILLS","SNOWY"],
  "Mega Spruce Taiga":["DENSE","FOREST"],
  "Mega Spruce Taiga 2":["DENSE","FOREST"],
  "Extreme Hills+ M":["HILLS"],
  "Savanna M":["HOT","SPARSE","DRY","SAVANNA","HILLS"],
  "Savanna Plateau M":["HOT","SPARSE","DRY","SAVANNA","HILLS"],
  "Mesa (Bryce)":["HOT","DRY","PLAINS","SANDY"],
  "Mesa Plateau F M":["HOT","DRY","FOREST","SANDY"],
  "Mesa Plateau M":["HOT","DRY","PLAINS","SANDY"],
  "Twilight Clearing":["SPARSE","PLAINS"],
  "Dark Forest":["DENSE","SPOOKY","FOREST"],
  "Dark Forest Center":["DENSE","SPOOKY","MAGICAL","FOREST"],
  "Deep Mushroom Forest":["MUSHROOM","FOREST"],
  "Fire Swamp":["HOT","SWAMP","WASTELAND"],
  "Twilight Glacier":["COLD","SNOWY","WASTELAND"],
  "Twilight Highlands":["CONIFEROUS","FOREST","MOUNTAIN"],
  "Highlands Center":["DRY","DEAD","MESA","WASTELAND"],
  "Twilight Lake":["OCEAN"],
  "Firefly Forest":["LUSH","FOREST"],
  "Mushroom Forest":["MUSHROOM","FOREST"],
  "Oak Savanna":["SPARSE","FOREST"],
  "Twilight Stream":["RIVER"],
  "Twilight Swamp":["WET","SWAMP"],
  "Thornlands":["DRY","DEAD","HILLS","WASTELAND"],
  "Twilight Forest":["FOREST"],
  "Dense Twilight Forest":["DENSE","FOREST"],
  "Enchanted Forest":["MAGICAL","FOREST"],
  "Eerie":["SPOOKY","MAGICAL"],
  "Eldritch":["SPOOKY","END","MAGICAL"],
  "Magical Forest":["MAGICAL","FOREST"],
  "Tainted Land":["MAGICAL","WASTELAND"],
  "Snowy Forest":["COLD","CONIFEROUS","FOREST","SNOWY"],
  "Toxic Everglades":["DENSE","DEAD","FOREST","HILLS"],
  "rwg_riverIce":["COLD","RIVER","SNOWY"],
  "rwg_riverCold":["COLD","CONIFEROUS","RIVER","FOREST"],
  "rwg_riverTemperate":["COLD","RIVER","FOREST"],
  "rwg_riverHot":["HOT","DRY","RIVER","SANDY"],
  "rwg_riverWet":["HOT","WET","JUNGLE","RIVER"],
  "rwg_riverOasis":["HOT","WET","JUNGLE","RIVER"],
  "rwg_oceanIce":["COLD","OCEAN","SNOWY","BEACH"],
  "rwg_oceanCold":["COLD","CONIFEROUS","OCEAN","FOREST","BEACH"],
  "rwg_oceanTemperate":["COLD","OCEAN","FOREST","BEACH"],
  "rwg_oceanHot":["HOT","DRY","OCEAN","SANDY","BEACH"],
  "rwg_oceanOasis":["HOT","WET","JUNGLE","OCEAN","BEACH"],
  "rwg_snowDesert":["COLD","SNOWY","WASTELAND"],
  "rwg_coldPlains":["COLD","WASTELAND"],
  "rwg_coldForest":["COLD","DENSE","CONIFEROUS","FOREST","HILLS"],
  "rwg_hotPlains":["HOT","SPARSE","SAVANNA","PLAINS"],
  "rwg_hotForest":["HOT","SPARSE","SAVANNA","PLAINS"],
  "rwg_hotDesert":["HOT","DRY","SANDY"],
  "rwg_plains":["PLAINS"],
  "rwg_tropical":["HOT","WET","JUNGLE"],
  "rwg_redwood":["COLD","CONIFEROUS","FOREST"],
  "rwg_jungle":["HOT","WET","JUNGLE"],
  "rwg_oasis":["HOT","WET","PLAINS"],
  "rwg_temperateForest":["PLAINS"],
  "rwg_oceanWet":["HOT","WET","JUNGLE","OCEAN","BEACH"],
};
const BIOME_RAINFALL={"Ocean":0.5,"Plains":0.4,"Desert":0.0,"Extreme Hills":0.3,"Forest":0.8,"Taiga":0.8,"Swampland":0.9,"River":0.5,"Hell":0.0,"Sky":0.5,"FrozenOcean":0.5,"FrozenRiver":0.5,"Ice Plains":0.5,"Ice Mountains":0.5,"MushroomIsland":1.0,"MushroomIslandShore":1.0,"Beach":0.4,"DesertHills":0.0,"ForestHills":0.8,"TaigaHills":0.8,"Extreme Hills Edge":0.3,"Jungle":0.9,"JungleHills":0.9,"JungleEdge":0.8,"Deep Ocean":0.5,"Stone Beach":0.3,"Cold Beach":0.3,"Birch Forest":0.6,"Birch Forest Hills":0.6,"Roofed Forest":0.8,"Cold Taiga":0.4,"Cold Taiga Hills":0.4,"Mega Taiga":0.8,"Mega Taiga Hills":0.8,"Extreme Hills+":0.3,"Savanna":0.0,"Savanna Plateau":0.0,"Mesa":0.0,"Mesa Plateau F":0.0,"Mesa Plateau":0.0,"Alps Forest":0.5,"Alps":0.5,"Arctic":0.5,"Bamboo Forest":0.9,"Bayou":0.9,"Bog":0.9,"Boreal Forest":0.6,"Brushland":0.1,"Canyon":0.3,"Canyon Ravine":0.3,"Chaparral":0.6,"Cherry Blossom Grove":0.8,"Coniferous Forest":0.5,"Coral Reef":0.9,"Crag":0.0,"Dead Forest":0.3,"Dead Swamp":0.9,"Deciduous Forest":0.8,"Dry River":0.0,"Eucalyptus Forest":1.0,"Fen":0.4,"Flower Field":0.7,"Frost Forest":0.5,"Fungi Forest":1.0,"Garden":0.8,"Glacier":0.2,"Grassland":0.7,"Grove":0.8,"Heathland":0.2,"Highland":0.8,"Jade Cliffs":0.9,"Kelp Forest":0.9,"Land of Lakes":0.9,"Land of Lakes Marsh":0.9,"Lavender Fields":0.7,"Lush Desert":0.5,"Lush River":0.8,"Lush Swamp":1.0,"Mangrove":0.9,"Maple Woods":0.8,"Marsh":0.9,"Meadow Forest":0.7,"Meadow":0.7,"Moor":1.0,"Mountain":0.1,"Mystic Grove":1.0,"Oasis":0.3,"Ominous Woods":0.9,"Orchard":0.7,"Origin Valley":0.8,"Outback":0.05,"Polar Chasm":0.0,"Prairie":0.3,"Quagmire":0.9,"Rainforest":1.0,"Redwood Forest":0.7,"Sacred Springs":0.5,"Scrubland":0.0,"Seasonal Forest Clearing":0.8,"Seasonal Forest":0.8,"Shield":0.8,"Shrubland":0.05,"Silkglades":0.9,"Sludgepit":0.9,"Snowy Coniferous Forest":0.5,"Spectral Garden":0.0,"Spruce Woods":0.8,"Steppe":0.05,"Temperate Rainforest":1.2,"Thicket":0.2,"Tropical Rainforest":1.0,"Tropics":1.0,"Tundra":0.5,"Visceral Heap":0.0,"Volcano":0.05,"Wasteland":0.05,"Wetland":0.9,"Woodland":0.4,"Xeric Shrubland":0.2,"Dense Forest":0.7,"Ocean Oil Field":0.5,"Desert Oil Field":0.0,"Boneyard":0.0,"Sunflower Plains":0.4,"Desert M":0.0,"Extreme Hills M":0.3,"Flower Forest":0.8,"Taiga M":0.8,"Swampland M":0.9,"Corrupted Sands":0.0,"Phantasmagoric Inferno":0.0,"Undergarden":0.0,"Ice Plains Spikes":0.5,"moon":0.0,"marsFlat":0.0,"asteroids":0.0,"space":0.0,"Jungle M":0.9,"JungleEdge M":0.8,"Birch Forest M":0.6,"Birch Forest Hills M":0.6,"Roofed Forest M":0.8,"Cold Taiga M":0.4,"Mega Spruce Taiga":0.8,"Mega Spruce Taiga 2":0.8,"Extreme Hills+ M":0.3,"Savanna M":0.0,"Savanna Plateau M":0.0,"Mesa (Bryce)":0.0,"Mesa Plateau F M":0.0,"Mesa Plateau M":0.0,"Twilight Clearing":0.4,"Dark Forest":0.8,"Dark Forest Center":0.8,"Deep Mushroom Forest":1.0,"Fire Swamp":0.4,"Twilight Glacier":0.1,"Twilight Highlands":0.7,"Highlands Center":0.2,"Twilight Lake":1.0,"Firefly Forest":1.0,"Mushroom Forest":0.8,"Oak Savanna":0.0,"Twilight Stream":1.0,"Twilight Swamp":0.9,"Thornlands":0.2,"Twilight Forest":0.5,"Dense Twilight Forest":0.8,"Enchanted Forest":0.5,"Eerie":0.5,"Eldritch":0.5,"Magical Forest":0.6,"Tainted Land":0.5,"Snowy Forest":0.9,"Toxic Everglades":0.7,"rwg_riverIce":0.1,"rwg_riverCold":0.4,"rwg_riverTemperate":0.6,"rwg_riverHot":0.2,"rwg_riverWet":0.9,"rwg_riverOasis":0.9,"rwg_oceanIce":0.1,"rwg_oceanCold":0.4,"rwg_oceanTemperate":0.6,"rwg_oceanHot":0.2,"rwg_oceanOasis":0.9,"rwg_snowDesert":0.1,"rwg_coldPlains":0.2,"rwg_coldForest":0.4,"rwg_hotPlains":0.1,"rwg_hotForest":0.2,"rwg_hotDesert":0.0,"rwg_plains":0.4,"rwg_tropical":0.8,"rwg_redwood":0.6,"rwg_jungle":0.9,"rwg_oasis":0.9,"rwg_temperateForest":0.6,"rwg_oceanWet":0.9};
