// ═══════════════════════════════════════════════════════════════════════════
// CropsNH Data — verified against GTNewHorizons/CropsNH v2.0.76 decompiled jar
// 178 crops, 172 mutation recipes, 5 direct pool registrations
// Zero discrepancies vs decompiled source as of this build.
// ═══════════════════════════════════════════════════════════════════════════

const SOILS=[
  {id:'farmland', name:'Farmland', note:'Tilled dirt/enchanted earth/Ztones', blocks:'Farmland, Enchanted Earth, Ztones Garden Soil, Fertilized Dirt'},
  {id:'dirtGrass', name:'Dirt / Grass', note:'Dirt, grass, podzol', blocks:'Dirt, Grass, Mycelium variants'},
  {id:'stone', name:'Stone', note:'Stone, cobble, stonebrick, ore blocks', blocks:'Stone, Cobblestone, Stone Brick, Mossy Cobble + Chisel variants'},
  {id:'sand', name:'Sand', note:'Sand, sandstone', blocks:'Sand, Sandstone'},
  {id:'soulsand', name:'Soul Sand', note:'Nether Wart, Gaia Wart (+snow above)', blocks:'Soul Sand'},
  {id:'sugarcane', name:'Sugarcane Soil', note:'Sand OR dirt/grass compound', blocks:'Sand, Sandstone, Dirt, Grass (CompoundSoilList)'},
  {id:'netherrack', name:'Netherrack', note:'Netherrack + Chisel/TiC variants', blocks:'Netherrack, TiC Nether Bricks, Chisel Netherrack'},
  {id:'graveyard', name:'Graveyard Soil', note:'TiC Graveyard Soil (meta 3)', blocks:'TiC CraftedSoil:3 (Graveyard Soil)'},
  {id:'slimy', name:'Slimy Soil', note:'TiC slimy muds/slime dirt', blocks:'TiC Green/Blue Slimy Mud, Slime Dirt, Slime Grass'},
  {id:'slimyDirt', name:'Slimy Dirt/Grass', note:'Dirt/Grass OR Slimy compound (Bonsai Slimy only)', blocks:'Dirt, Grass + all Slimy Soil variants (CompoundSoilList)'},
  {id:'end', name:'End Stone', note:'End stone + Botania/Chisel variants', blocks:'End Stone, Botania End Stone Brick, Chisel End Stone'},
  {id:'mycelium', name:'Mycelium', note:'Mushrooms', blocks:'Mycelium'},
  {id:'thaumLogs', name:'Thaumcraft Logs', note:'Greatwood / Silverwood logs', blocks:'Greatwood Log, Silverwood Log'},
  {id:'brick', name:'Brick', note:'Brick blocks', blocks:'Brick Block, ExtraUtils Color Brick, ThaumicBases Old Brick'},
  {id:'gravel', name:'Gravel', note:'Gravel blocks', blocks:'Gravel'},
  {id:'oilSands', name:'Oil Sands', note:'GT Oil Sands ores', blocks:'GT Oil Sands ore variants'},
  {id:'oil', name:'Oil Soil', note:'Sand/Gravel/Soulsand/OilSands compound', blocks:'Sand, Gravel, Soul Sand, Oil Sands (OilBerry compound)'},
  {id:'mushroom', name:'Mushroom Soil', note:'Stone/Dirt/Mycelium compound', blocks:'Stone, Dirt/Grass, Mycelium'},
  {id:'netherMushroom', name:'Nether Mushroom Soil', note:'Mushroom + Netherrack compound', blocks:'Stone, Dirt, Mycelium, Netherrack'},
];

const CROPS=[
  {id:'Wheat',name:'Wheat',tier:1,soil:'farmland',pools:['aYellow','aFood','aWheat'],liked:['PLAINS','LUSH']},
  {id:'Carrot',name:'Carrot',tier:2,soil:'farmland',pools:['aOrange','aFood','aCarrots','aRoot'],liked:['PLAINS','HOT','SANDY']},
  {id:'Potato',name:'Potato',tier:1,soil:'farmland',pools:['aYellow','aFood','aRoot'],liked:['PLAINS','COLD']},
  {id:'Melon',name:'Melon',tier:2,soil:'farmland',pools:['aGreen','aFood','aStem'],liked:['WET','LUSH']},
  {id:'Pumpkin',name:'Pumpkin',tier:2,soil:'farmland',pools:['aOrange','aStem'],liked:['PLAINS','WET']},
  {id:'Cocoa',name:'Cocoa',tier:3,soil:'farmland',pools:['aBrown','aFood','aStem'],liked:['JUNGLE','WET','DENSE','LUSH']},
  {id:'Cactus',name:'Cactus',tier:3,soil:'sand',pools:['aGreen','aCactus','aDanger'],liked:['SANDY','HOT','DRY']},
  {id:'SugarCane',name:'Sugar Cane',tier:2,soil:'sugarcane',pools:['aReed','aGreen','aFood','aStem'],liked:['WET','HOT']},
  {id:'Vine',name:'Vine',tier:2,soil:'farmland',pools:['aGreen','aTendrilly','aClimbable'],liked:['LUSH','JUNGLE','WET']},
  {id:'Waterlily',name:'Waterlily',tier:2,soil:'farmland',pools:['aBlue','aWater','aGreen'],liked:['WET','SWAMP','RIVER']},
  {id:'Netherwart',name:'Nether Wart',tier:5,soil:'soulsand',pools:['aRed','aNether','aIngredient','aSoulsand'],liked:['NETHER','HOT']},
  {id:'GaiaWart',name:'Gaia Wart',tier:5,soil:'soulsand',blockUnder:'snow',pools:[],note:'Not obtainable via breeding — no mutation recipe or pool registration. Check NEI for acquisition.',liked:['SNOWY','COLD']},
  {id:'Dandelion',name:'Dandelion',tier:2,soil:'dirtGrass',pools:['aFlower','aYellow'],liked:['PLAINS','FOREST']},
  {id:'Poppy',name:'Poppy',tier:2,soil:'dirtGrass',pools:['aRed','aFlower','aRose'],liked:['PLAINS','HILLS']},
  {id:'BlueOrchid',name:'Blue Orchid',tier:2,soil:'dirtGrass',pools:['aFlower','aBlue'],liked:['WET','SWAMP']},
  {id:'AzureBluet',name:'Azure Bluet',tier:2,soil:'dirtGrass',pools:['aFlower','aWhite'],liked:['HILLS','FOREST','LUSH']},
  {id:'RedTulip',name:'Red Tulip',tier:2,soil:'dirtGrass',pools:['aFlower','aRed','aTulip'],liked:['PLAINS','HOT']},
  {id:'OrangeTulip',name:'Orange Tulip',tier:2,soil:'dirtGrass',pools:['aFlower','aOrange','aTulip'],liked:['PLAINS','WET']},
  {id:'PinkTulip',name:'Pink Tulip',tier:2,soil:'dirtGrass',pools:['aFlower','aRed','aTulip'],liked:['PLAINS','WET']},
  {id:'WhiteTulip',name:'White Tulip',tier:2,soil:'dirtGrass',pools:['aFlower','aWhite','aTulip'],liked:['PLAINS','COLD']},
  {id:'Allium',name:'Allium',tier:2,soil:'dirtGrass',pools:['aFlower','aPurple','aRoot'],liked:['DRY','SANDY','SPARSE']},
  {id:'OxeyeDaisy',name:'Oxeye Daisy',tier:2,soil:'dirtGrass',pools:['aFlower','aWhite'],liked:['PLAINS','FOREST']},
  {id:'BrownMushroom',name:'Brown Mushroom',tier:1,soil:'mushroom',pools:['aBrown','aFood','aMushroom'],liked:['MUSHROOM','WET','SWAMP']},
  {id:'RedMushroom',name:'Red Mushroom',tier:1,soil:'mushroom',pools:['aRed','aFood','aMushroom'],liked:['MUSHROOM','WET','SWAMP']},
  {id:'BonsaiOak',name:'Bonsai Oak',tier:1,soil:'dirtGrass',pools:['aTree','aBonsai','aLeafy','aFood','aWood'],liked:['FOREST','HILLS','PLAINS']},
  {id:'BonsaiBirch',name:'Bonsai Birch',tier:1,soil:'dirtGrass',pools:['aTree','aBonsai','aLeafy','aWood'],liked:['FOREST','HILLS']},
  {id:'BonsaiSpruce',name:'Bonsai Spruce',tier:1,soil:'dirtGrass',pools:['aTree','aBonsai','aLeafy','aWood'],liked:['CONIFEROUS','FOREST','MOUNTAIN']},
  {id:'BonsaiDarkOak',name:'Bonsai Dark Oak',tier:1,soil:'dirtGrass',pools:['aTree','aBonsai','aLeafy','aDark','aWood'],liked:['DENSE','FOREST','SPOOKY']},
  {id:'BonsaiAcacia',name:'Bonsai Acacia',tier:1,soil:'dirtGrass',pools:['aTree','aBonsai','aLeafy','aWood'],liked:['HOT','PLAINS','SAVANNA','SPARSE']},
  {id:'BonsaiJungle',name:'Bonsai Jungle',tier:1,soil:'dirtGrass',pools:['aTree','aBonsai','aLeafy','aWood'],liked:['DENSE','HOT','JUNGLE','WET']},
  {id:'BonsaiRubber',name:'Bonsai Rubber',tier:1,soil:'dirtGrass',pools:['aTree','aBonsai','aLeafy','aWood','aSticky'],liked:['CONIFEROUS','FOREST']},
  {id:'BonsaiSlimy',name:'Bonsai Slimy',tier:1,soil:'slimyDirt',pools:['aSlime','aBouncy'],liked:['WET','SWAMP']},
  {id:'StoneLily',name:'Stone Lily',tier:1,soil:'stone',blockUnder:'stone',pools:['aGray','aStone','aMetal'],liked:['MOUNTAIN','HILLS']},
  {id:'SandLily',name:'Sand Lily',tier:1,soil:'stone',blockUnder:'sand',pools:['aYellow','aStone','aCactus'],liked:['SANDY','DRY','HOT']},
  {id:'ClayLily',name:'Clay Lily',tier:1,soil:'stone',blockUnder:'clay',pools:['aGray','aStone','aWater'],liked:['WET','RIVER','SWAMP']},
  {id:'MarbleLily',name:'Marble Lily',tier:1,soil:'stone',blockUnder:'marble',pools:['aWhite','aStone','aShiny'],liked:['MOUNTAIN','HILLS']},
  {id:'BasaltLily',name:'Basalt Lily',tier:1,soil:'stone',blockUnder:'basalt',pools:['aBlack','aStone','aDark'],liked:['MOUNTAIN','HILLS']},
  {id:'BlackGraniteLily',name:'Black Granite Lily',tier:1,soil:'stone',blockUnder:'blackGranite',pools:['aBlack','aStone','aDark'],liked:['MOUNTAIN','HILLS']},
  {id:'RedGraniteLily',name:'Red Granite Lily',tier:1,soil:'stone',blockUnder:'redGranite',pools:['aRed','aStone','aFire'],liked:['MOUNTAIN','HILLS']},
  {id:'NetherStoneLily',name:'Nether Stone Lily',tier:1,soil:'stone',blockUnder:'netherrack',pools:['aNether','aStone','aEvil'],liked:['NETHER','HOT','DRY']},
  {id:'SoulSandLily',name:'Soul Sand Lily',tier:2,soil:'stone',blockUnder:'soulSand',pools:['aNether','aStone','aEvil','aSoulsand','aOil'],liked:['NETHER','SPOOKY','SANDY']},
  {id:'EndStoneLily',name:'End Stone Lily',tier:1,soil:'stone',blockUnder:'endStone',pools:['aYellow','aStone','aAlien','aEnder'],liked:['END','DRY','COLD']},
  {id:'StickyCane',name:'Sticky Cane',tier:4,soil:'sugarcane',pools:['aReed','aSticky','aGreen','aStem'],liked:['WET','HOT','SANDY']},
  {id:'Flax',name:'Flax',tier:2,soil:'farmland',pools:['aSilk','aTendrilly','aAddictive'],liked:['WET','RIVER','BEACH','SANDY']},
  {id:'Hemp',name:'Hemp',tier:5,soil:'farmland',pools:['aSilk','aGreen','aOrange','aStem','aAddictive'],liked:['DRY','SANDY']},
  {id:'Indigo',name:'Indigo',tier:2,soil:'dirtGrass',pools:['aFlower','aBlue','aIngredient'],liked:['WET','LUSH']},
  {id:'Dayflower',name:'Dayflower',tier:2,soil:'dirtGrass',pools:['aBlue','aFlower','aAddictive'],liked:['COLD','HILLS','SPARSE']},
  {id:'Canola',name:'Canola',tier:4,soil:'farmland',pools:['aFood','aYellow','aOil'],liked:['COLD','PLAINS']},
  {id:'Fertilia',name:'Fertilia',tier:3,soil:'farmland',pools:['aHealing','aFlower'],liked:['SWAMP','WET','HOT']},
  {id:'Papyrus',name:'Papyrus',tier:5,soil:'farmland',pools:['aWhite','aStem'],liked:['WET','SWAMP','JUNGLE']},
  {id:'PurpleTulip',name:'Purple Tulip',tier:2,soil:'dirtGrass',pools:['aPurple','aFlower','aTulip'],liked:['WET','PLAINS']},
  {id:'Necrobloom',name:'Necrobloom',tier:3,soil:'farmland',pools:['aPurple','aFlower','aTulip','aPoison','aDanger'],liked:['DEAD','WASTELAND']},
  {id:'RedStraw',name:'Red Straw',tier:6,soil:'farmland',blockUnder:'redstone',pools:['aRed','aStone','aWheat'],liked:['PLAINS','HOT']},
  {id:'Withereed',name:'Withereed',tier:8,soil:'stone',blockUnder:'coal',pools:['aFire','aUndead','aReed','aCoal','aRotten','aSulfur'],liked:['DEAD','SPOOKY']},
  {id:'EvilOre',name:'Evil Ore',tier:8,soil:'netherrack',pools:['aCrystal','aFire','aNether'],liked:['HOT','DRY','NETHER']},
  {id:'Plumbilia',name:'Plumbilia',tier:6,soil:'stone',blockUnder:'lead',pools:['aMetal','aLead','aReed','aDense'],liked:['SAVANNA','PLAINS']},
  {id:'Tine',name:'Tine',tier:5,soil:'stone',blockUnder:'tin',pools:['aShiny','aMetal','aPine','aTin','aBush'],liked:['MOUNTAIN','HILLS']},
  {id:'Ferrofern',name:'Ferrofern',tier:6,soil:'stone',blockUnder:'iron',pools:['aGray','aLeaves','aMetal','aIron'],liked:['MOUNTAIN','HILLS']},
  {id:'Coppon',name:'Coppon',tier:6,soil:'stone',blockUnder:'copper',pools:['aShiny','aMetal','aCotton','aCopper','aBush'],liked:['SAVANNA','HOT','SANDY']},
  {id:'Nickelback',name:'Nickelback',tier:5,soil:'stone',blockUnder:'nickel',pools:['aMetal','aFire','aAlloy'],liked:['PLAINS','LUSH']},
  {id:'Galvania',name:'Galvania',tier:6,soil:'stone',blockUnder:'zinc',pools:['aMetal','aAlloy','aBush'],liked:['DRY','HOT']},
  {id:'Malaxia',name:'Malaxia',tier:6,soil:'stone',blockUnder:'copper',pools:['aOrange','aLeaves','aMetal','aCopper'],liked:['PLAINS','LUSH']},
  {id:'Cassitine',name:'Cassitine',tier:6,soil:'stone',blockUnder:'tin',pools:['aShiny','aLeaves','aMetal','aTin'],liked:['COLD','SPARSE','DRY']},
  {id:'Plumbshade',name:'Plumbshade',tier:6,soil:'stone',blockUnder:'lead',pools:['aDense','aLeaves','aMetal','aLead'],liked:['HOT','WET']},
  {id:'Silviscus',name:'Silviscus',tier:8,soil:'stone',blockUnder:'silver',pools:['aSilver','aLeaves','aMetal','aSilver'],liked:['COLD','SNOWY','SPOOKY']},
  {id:'Argentia',name:'Argentia',tier:7,soil:'stone',blockUnder:'silver',pools:['aShiny','aMetal','aSilver'],liked:['MOUNTAIN','HOT']},
  {id:'Auronia',name:'Auronia',tier:8,soil:'stone',blockUnder:'gold',pools:['aGold','aLeaves','aMetal','aDense'],liked:['MESA','SANDY']},
  {id:'Thiosulfine',name:'Thiosulfine',tier:6,soil:'stone',blockUnder:'sulfur',pools:['aYellow','aFlower','aBad','aSulfur'],liked:['NETHER','HOT']},
  {id:'Pyrolusium',name:'Pyrolusium',tier:12,soil:'stone',blockUnder:'manganese',pools:['aMetal','aBush'],liked:['NETHER','HOT']},
  {id:'Lazulia',name:'Lazulia',tier:7,soil:'stone',blockUnder:'lapis',pools:['aShiny','aBad','aCrystal','aBlue'],liked:['HOT','SANDY']},
  {id:'Rubyne',name:'Rubyne',tier:4,soil:'farmland',blockUnder:'ruby',pools:['aRed','aCrystal','aShiny'],liked:['MOUNTAIN','RIVER']},
  {id:'Sapphirum',name:'Sapphirum',tier:4,soil:'stone',blockUnder:'sapphire',pools:['aCrystal','aShiny','aMetal'],liked:['OCEAN','WET','COLD']},
  {id:'BobsYerUncleRanks',name:'BobsYerUncleRanks',tier:6,soil:'stone',blockUnder:'emerald',pools:['aShiny','aTendrilly','aCrystal'],liked:['MOUNTAIN','HILLS']},
  {id:'Diareed',name:'Diareed',tier:12,soil:'stone',blockUnder:'diamond',pools:['aFire','aShiny','aReed','aCoal','aCrystal'],liked:['COLD','SPARSE']},
  {id:'Glowheat',name:'Glowheat',tier:4,soil:'netherrack',blockUnder:'glowstone',pools:['aLight','aShiny','aCrystal','aWheat'],liked:['PLAINS','HOT','NETHER']},
  {id:'SaltyRoot',name:'Salty Root',tier:4,soil:'farmland',pools:['aGray','aRoot','aSaltpeter'],liked:['DRY','SANDY','DEAD']},
  {id:'Corium',name:'Corium',tier:6,soil:'farmland',pools:['aCow','aSilk','aTendrilly','aMilk'],liked:['PLAINS','FOREST']},
  {id:'EggPlant',name:'Egg Plant',tier:6,soil:'farmland',pools:['aChicken','aFood','aFlower','aAddictive'],liked:['PLAINS','FOREST']},
  {id:'Creeperweed',name:'Creeperweed',tier:7,soil:'farmland',pools:['aTendrilly','aFire','aSulfur','aSaltpeter','aCoal'],liked:['DEAD','SPOOKY']},
  {id:'Spidernip',name:'Spidernip',tier:4,soil:'farmland',pools:['aToxic','aSilk','aFlower','aIngredient','aAddictive'],liked:['WET','LUSH']},
  {id:'InkBloom',name:'Ink Bloom',tier:4,soil:'dirtGrass',pools:['aBlack','aFlower','aRose'],liked:['WET','OCEAN']},
  {id:'Slimeplant',name:'Slimeplant',tier:6,soil:'dirtGrass',pools:['aSlime','aBouncy','aSticky','aBush'],liked:['WET','SWAMP']},
  {id:'Goldfish',name:'Goldfish',tier:4,soil:'farmland',pools:['aNether','aFish','aFood','aBad','aWater'],liked:['RIVER','WET','SPOOKY']},
  {id:'Enderbloom',name:'Enderbloom',tier:10,soil:'farmland',blockUnder:'endStone',pools:['aEnder','aFlower','aShiny','aAlien'],liked:['END','COLD']},
  {id:'Zomplant',name:'Zomplant',tier:3,soil:'graveyard',pools:['aZombie','aRotten','aUndead'],liked:['DEAD','WASTELAND']},
  {id:'Corpseplant',name:'Corpseplant',tier:5,soil:'graveyard',pools:['aToxic','aUndead','aTendrilly','aFood','aRotten','aZombie'],liked:['DEAD','SPOOKY']},
  {id:'Tearstalks',name:'Tearstalks',tier:8,soil:'farmland',pools:['aHealing','aNether','aIngredient','aReed'],liked:['NETHER','DEAD']},
  {id:'MilkWart',name:'Milk Wart',tier:6,soil:'farmland',pools:['aFood','aMilk','aCow'],liked:['PLAINS','LUSH']},
  {id:'Meatrose',name:'Meatrose',tier:7,soil:'dirtGrass',pools:['aFood','aFlower','aCow','aFish','aChicken','aRose'],liked:['PLAINS','MAGICAL']},
  {id:'Lemon',name:'Lemon',tier:4,soil:'dirtGrass',pools:['aFood','aYellow','aTree','aLeafy'],liked:['HOT','DRY','PLAINS']},
  {id:'Onion',name:'Onion',tier:4,soil:'farmland',pools:['aFood','aBrown','aRoot'],liked:['DRY','SANDY','SPARSE']},
  {id:'SugarBeet',name:'Sugar Beet',tier:4,soil:'farmland',pools:['aFood','aWhite','aIngredient','aRoot'],liked:['COLD','WET']},
  {id:'Tomato',name:'Tomato',tier:4,soil:'farmland',pools:['aFood','aRed','aTendrilly'],liked:['HOT','WET']},
  {id:'Cucumber',name:'Cucumber',tier:4,soil:'farmland',pools:['aFood','aGreen','aTendrilly'],liked:['HOT','LUSH']},
  {id:'Chilly',name:'Chilly',tier:4,soil:'farmland',pools:['aFood','aRed','aFire'],liked:['HOT','LUSH']},
  {id:'Coffee',name:'Coffee',tier:7,soil:'farmland',pools:['aLeaves','aIngredient','aBean','aAddictive'],liked:['HOT','LUSH','WET']},
  {id:'Hops',name:'Hops',tier:5,soil:'farmland',pools:['aGreen','aIngredient','aWheat'],liked:['PLAINS','LUSH']},
  {id:'Strawberry',name:'Strawberry',tier:2,soil:'farmland',pools:['aBerry','aFood','aRed'],note:'PHC req',liked:['PLAINS','LUSH']},
  {id:'Blueberry',name:'Blueberry',tier:2,soil:'farmland',pools:['aBerry','aFood','aBlue'],note:'Natura req',liked:['HILLS','FOREST','LUSH']},
  {id:'Blackberry',name:'Blackberry',tier:2,soil:'farmland',pools:['aBerry','aFood','aBlack'],note:'Natura req',liked:['WET','DENSE','LUSH']},
  {id:'Raspberry',name:'Raspberry',tier:2,soil:'farmland',pools:['aBerry','aFood','aRed'],note:'Natura req',liked:['PLAINS','DRY']},
  {id:'Grape',name:'Grape',tier:4,soil:'farmland',pools:['aFood','aPurple','aClimbable','aTendrilly'],note:'Natura req',liked:['HOT','DRY','SPARSE']},
  {id:'Huckleberry',name:'Huckleberry',tier:2,soil:'farmland',pools:['aBerry','aFood','aPurple','aLeaves'],note:'Natura req',liked:['MOUNTAIN','HILLS','PLAINS','COLD']},
  {id:'Maloberry',name:'Maloberry',tier:2,soil:'farmland',pools:['aBerry','aFood','aYellow'],note:'Natura req',liked:['COLD','WET','LUSH']},
  {id:'Cotton',name:'Cotton',tier:3,soil:'farmland',pools:['aWhite','aCotton'],note:'Natura req',liked:['DRY','HOT']},
  {id:'ManaBean',name:'Mana Bean',tier:5,soil:'thaumLogs',blockUnder:'mixedCrystalCluster',pools:['aBerry','aBean','aMagic'],note:'TC req',liked:['MAGICAL','FOREST']},
  {id:'Cinderpearl',name:'Cinderpearl',tier:5,soil:'dirtGrass',blockUnder:'blaze',pools:['aMagic','aBlaze','aNether'],note:'TC req',liked:['HOT','DRY','MAGICAL']},
  {id:'Shimmerleaf',name:'Shimmerleaf',tier:5,soil:'dirtGrass',blockUnder:'quicksilver',pools:['aMagic','aSilver','aToxic','aShimmer'],note:'TC req',liked:['MAGICAL','LUSH']},
  {id:'PrimordialBerry',name:'Primordial Berry',tier:16,soil:'farmland',pools:['aMagic'],note:'TC req - plant-only',liked:['END','MAGICAL']},
  {id:'Bauxia',name:'Bauxia',tier:6,soil:'stone',blockUnder:'aluminiumBauxite',pools:[],machine:true,liked:['COLD','DRY']},
  {id:'Micadia',name:'Micadia',tier:9,soil:'stone',blockUnder:'mica',pools:[],machine:true,liked:['HILLS','SPARSE']},
  {id:'Titania',name:'Titania',tier:9,soil:'stone',blockUnder:'titanium',pools:[],machine:true,liked:['HOT','SAVANNA']},
  {id:'OilBerry',name:'Oil Berry',tier:4,soil:'oil',pools:[],machine:true,liked:['HOT','WASTELAND']},
  {id:'Olivia',name:'Olivia',tier:2,soil:'stone',blockUnder:'olivine',pools:[],machine:true,liked:['HILLS','DRY']},
  {id:'Garnydinia',name:'Garnydinia',tier:7,soil:'stone',blockUnder:'garnetGem',pools:[],machine:true,liked:['SAVANNA','SANDY','MESA']},
  {id:'GodOfThunder',name:'God of Thunder',tier:9,soil:'stone',blockUnder:'thorium',pools:[],machine:true,liked:['WASTELAND','SPARSE']},
  {id:'Reactoria',name:'Reactoria',tier:12,soil:'stone',blockUnder:'uranium',pools:[],machine:true,liked:['COLD','HOT']},
  {id:'Scheelinium',name:'Scheelinium',tier:12,soil:'stone',blockUnder:'tungsten',pools:[],machine:true,liked:['OCEAN','WET','COLD']},
  {id:'Platina',name:'Platina',tier:11,soil:'stone',blockUnder:'platinum',pools:[],machine:true,liked:['HOT','SANDY']},
  {id:'SpaceFlower',name:'Space FlowerS',tier:13,soil:'farmland',blockUnder:'space',pools:[],machine:true,liked:['COLD','DRY','DEAD']},
  {id:'Iridine',name:'Iridine',tier:12,soil:'stone',blockUnder:'iridium',pools:[],machine:true,liked:['SNOWY','COLD']},
  {id:'Osmianth',name:'Osmianth',tier:12,soil:'stone',blockUnder:'osmium',pools:[],machine:true,liked:['OCEAN','RIVER']},
  {id:'Transformium',name:'Transformium',tier:12,soil:'farmland',pools:[],machine:true,liked:['END','COLD']},
  {id:'StarWart',name:'Star Wart',tier:12,soil:'stone',blockUnder:'netherStar',pools:[],machine:true,liked:['NETHER','DEAD']},
  {id:'MagicalNightshade',name:'Magical Nightshade',tier:13,soil:'farmland',blockUnder:'shadowmetal',pools:[],machine:true,liked:['MAGICAL','COLD']},
  {id:'Trollplant',name:'Trollplant',tier:6,soil:'brick',pools:[],machine:true,req:'Plutonium dust ×1, Red Alloy Stick ×64, Brick Block ×5',liked:['SWAMP','SPOOKY']},
  {id:'Stargatium',name:'Stargatium',tier:12,soil:'stone',blockUnder:'naquadah',pools:[],machine:true,liked:['LUSH','WASTELAND']},
  {id:'Eyebulb',name:'Eyebulb',tier:1,soil:'netherrack',pools:['aNether','aEvil','aBad'],note:'BoP req',liked:['NETHER','SPOOKY']},
  {id:'Glowflower',name:'Glowflower',tier:3,soil:'dirtGrass',pools:['aNether','aLight','aShiny'],note:'BoP req',liked:['WET','LUSH','MAGICAL','FOREST']},
  {id:'Bamboo',name:'Bamboo',tier:2,soil:'dirtGrass',pools:['aGreen','aPointed','aStem'],note:'BoP req',liked:['DENSE','JUNGLE','LUSH','FOREST']},
  {id:'FloweringVine',name:'Flowering Vine',tier:3,soil:'farmland',pools:['aGreen','aTendrilly','aFlower','aClimbable'],note:'BoP req',liked:['JUNGLE','DENSE']},
  {id:'GlowingCoral',name:'Glowing Coral',tier:5,soil:'farmland',blockUnder:'glowstone',pools:['aWater','aLight','aShiny'],note:'BoP req',liked:['OCEAN','RIVER']},
  {id:'Ivy',name:'Ivy',tier:2,soil:'farmland',pools:['aGreen','aTendrilly','aFlower','aBad','aPoison','aClimbable','aPointed'],note:'BoP req',liked:['NETHER','JUNGLE','MAGICAL','DENSE']},
  {id:'Moss',name:'Moss',tier:4,soil:'farmland',pools:['aGreen','aClimbable'],note:'BoP req',liked:['WET','SWAMP','LUSH']},
  {id:'Blightberry',name:'Blightberry',tier:4,soil:'netherrack',pools:['aBerry','aToxic','aBad','aGreen','aNether','aAddictive'],note:'Natura req',liked:['NETHER','DRY']},
  {id:'Duskberry',name:'Duskberry',tier:4,soil:'netherrack',pools:['aBerry','aToxic','aBad','aGray','aNether','aAddictive'],note:'Natura req',liked:['NETHER','HOT']},
  {id:'Skyberry',name:'Skyberry',tier:4,soil:'netherrack',pools:['aBerry','aToxic','aBad','aBlue','aNether','aAddictive'],note:'Natura req',liked:['NETHER','DRY']},
  {id:'Stingberry',name:'Stingberry',tier:4,soil:'netherrack',pools:['aBerry','aToxic','aBad','aGreen','aNether','aAddictive','aDanger'],note:'Natura req',liked:['NETHER','HOT']},
  {id:'Thornvine',name:'Thornvine',tier:3,soil:'netherrack',pools:['aNether','aClimbable','aBad','aDanger'],note:'Natura req',liked:['NETHER','DRY']},
  {id:'WaterArtichoke',name:'Water Artichoke',tier:4,soil:'farmland',pools:['aFlower','aWater','aBlue','aIngredient'],note:'Witchery req',altSeed:true,liked:['RIVER','WET','OCEAN']},
  {id:'Mandrake',name:'Mandrake',tier:4,soil:'farmland',pools:['aFlower','aMagic','aBad','aToxic','aIngredient'],note:'Witchery req',liked:['MAGICAL','SPOOKY']},
  {id:'Belladonna',name:'Belladonna',tier:4,soil:'farmland',pools:['aPurple','aFlower','aToxic','aIngredient'],note:'Witchery req',liked:['WET','SPOOKY']},
  {id:'Garlic',name:'Garlic',tier:3,soil:'farmland',pools:['aFood','aIngredient','aHealing','aRoot'],note:'Witchery req',liked:['PLAINS','DRY']},
  {id:'GlintWeed',name:'Glint Weed',tier:4,soil:'farmland',pools:['aOrange','aFlower','aMagic'],note:'Witchery req',liked:['MAGICAL','PLAINS','SANDY']},
  {id:'Snowbell',name:'Snowbell',tier:4,soil:'farmland',pools:['aWhite','aFlower','aToxic','aIngredient'],note:'Witchery req',liked:['SNOWY','COLD']},
  {id:'Wolfsbane',name:'Wolfsbane',tier:4,soil:'farmland',pools:['aFlower','aToxic','aPurple','aIngredient'],note:'Witchery req',liked:['MAGICAL','FOREST','SPOOKY']},
  {id:'EmberMoss',name:'Ember Moss',tier:7,soil:'farmland',pools:['aFire','aIngredient','aBad','aClimbable'],note:'Witchery req',liked:['HOT','DRY']},
  {id:'SpanishMoss',name:'Spanish Moss',tier:7,soil:'farmland',pools:['aGreen','aClimbable','aMagic'],note:'Witchery req',liked:['LUSH','WET','FOREST','SWAMP']},
  {id:'Torchberry',name:'Torchberry',tier:2,soil:'farmland',pools:['aBerry','aLight','aShimmer'],note:'TF req',liked:['FOREST','HILLS']},
  {id:'BoPBerry',name:'BoP Berry',tier:2,soil:'farmland',pools:['aBerry','aFood','aRed','aIngredient'],note:'BoP req',liked:['FOREST','DENSE']},
  {id:'Turnip',name:'Turnip',tier:2,soil:'farmland',pools:['aFood','aPurple','aCarrots'],note:'BoP req',liked:['PLAINS','WET','COLD']},
  {id:'WildCarrot',name:'Wild Carrot',tier:2,soil:'farmland',pools:['aFood','aWhite','aCarrots'],note:'BoP req',liked:['PLAINS','HOT','SANDY']},
  {id:'Barley',name:'Barley',tier:2,soil:'farmland',pools:['aGreen','aFood','aWheat'],note:'Natura+BoP req',liked:['PLAINS','DRY']},
  {id:'Blazereed',name:'Blazereed',tier:6,soil:'netherrack',pools:['aFire','aBlaze','aReed','aSulfur','aNether'],note:'TC req',liked:['NETHER','HOT']},
  {id:'SaguaroCactus',name:'Saguaro Cactus',tier:4,soil:'sand',pools:['aGreen','aFood','aCactus','aDanger'],note:'Natura req',liked:['HOT','DRY','SANDY']},
  {id:'Tea',name:'Tea',tier:4,soil:'farmland',pools:['aFood','aGreen','aIngredient'],note:'Natura req',liked:['WET','HILLS','HOT']},
  {id:'IronOreBerry',name:'Iron Ore Berry',tier:5,soil:'stone',blockUnder:'iron',pools:['aOreBerry','aGray','aMetal','aDanger','aIron'],note:'TiC req',liked:['MOUNTAIN','HILLS']},
  {id:'GoldOreBerry',name:'Gold Ore Berry',tier:5,soil:'stone',blockUnder:'gold',pools:['aOreBerry','aGold','aMetal','aDanger','aYellow','aDense'],note:'TiC req',liked:['MESA','SANDY']},
  {id:'CopperOreBerry',name:'Copper Ore Berry',tier:5,soil:'stone',blockUnder:'copper',pools:['aOreBerry','aCopper','aMetal','aShiny','aDanger','aOrange'],note:'TiC req',liked:['SAVANNA','HOT','SANDY']},
  {id:'TinOreBerry',name:'Tin Ore Berry',tier:4,soil:'stone',blockUnder:'tin',pools:['aOreBerry','aTin','aMetal','aShiny','aDanger','aWhite'],note:'TiC req',liked:['MOUNTAIN','HILLS']},
  {id:'AluminiumOreBerry',name:'Aluminium Ore Berry',tier:5,soil:'stone',blockUnder:'aluminium',pools:['aOreBerry','aAluminium','aMetal','aAluminium','aDanger'],note:'TiC req',liked:['COLD','DRY']},
  {id:'EssenceOreBerry',name:'Essence Ore Berry',tier:5,soil:'stone',blockUnder:'skull',pools:['aOreBerry','aUndead','aDanger','aGreen'],note:'TiC req',liked:['MAGICAL','DEAD']},
  {id:'ArditeOreBerry',name:'Ardite Ore Berry',tier:5,soil:'stone',blockUnder:'ardite',pools:['aOreBerry','aMetal','aOrange','aDanger'],note:'TiC req',liked:['NETHER','HOT']},
  {id:'CobaltOreBerry',name:'Cobalt Ore Berry',tier:5,soil:'stone',blockUnder:'cobalt',pools:['aOreBerry','aMetal','aBlue','aDanger'],note:'TiC req',liked:['NETHER','DRY']},
  {id:'ThaumiumOreBerry',name:'Thaumium Ore Berry',tier:7,soil:'stone',blockUnder:'thaumium',pools:['aOreBerry','aMagic','aMetal','aVoid','aDanger','aPurple'],note:'TiC+TC req',liked:['MAGICAL','SPOOKY']},
  {id:'ThauminiteOreBerry',name:'Thauminite Ore Berry',tier:7,soil:'stone',blockUnder:'thauminite',pools:['aOreBerry','aMagic','aMetal','aVoid','aDanger','aBlue'],note:'TiC+TC+ThaumicBases req',liked:['MAGICAL','FOREST']},
  {id:'VoidOreBerry',name:'Void Ore Berry',tier:7,soil:'stone',pools:['aOreBerry','aMagic','aMetal','aVoid','aDanger','aBlack'],note:'TC req',liked:['MAGICAL','WASTELAND']},
  {id:'KnightmetalBerry',name:'Knightmetal Berry',tier:8,soil:'stone',blockUnder:'knightmetal',pools:['aOreBerry','aMetal','aDanger','aGray','aGreen'],note:'TiC+TF req',liked:['SPOOKY','DEAD']},
  {id:'AndesiteLily',name:'Andesite Lily',tier:1,soil:'stone',blockUnder:'modernAndesite',pools:['aGray','aStone','aMetal'],liked:['MOUNTAIN','HILLS']},
  {id:'DioriteLily',name:'Diorite Lily',tier:1,soil:'stone',blockUnder:'modernDiorite',pools:['aWhite','aStone','aShiny'],liked:['MOUNTAIN','HILLS']},
  {id:'GraniteLily',name:'Granite Lily',tier:1,soil:'stone',blockUnder:'modernGranite',pools:['aRed','aStone','aFire'],liked:['MOUNTAIN','HILLS']},
  {id:'TuffLily',name:'Tuff Lily',tier:1,soil:'stone',blockUnder:'tuff',pools:['aGray','aStone','aDark'],note:'EtFuturum req',liked:['MOUNTAIN','HILLS']},
  {id:'DeepslateLily',name:'Deepslate Lily',tier:1,soil:'stone',blockUnder:'deepslate',pools:['aBlack','aStone','aDark'],note:'EtFuturum req',liked:['MOUNTAIN','HILLS']},
  {id:'BlueGlowshroom',name:'Blue Glowshroom',tier:3,soil:'netherMushroom',pools:['aFood','aMushroom','aIngredient','aNether','aLight'],note:'Natura req'},
  {id:'GreenGlowshroom',name:'Green Glowshroom',tier:3,soil:'netherMushroom',pools:['aFood','aMushroom','aIngredient','aNether','aLight'],note:'Natura req'},
  {id:'PurpleGlowshroom',name:'Purple Glowshroom',tier:3,soil:'netherMushroom',pools:['aFood','aMushroom','aIngredient','aNether','aLight'],note:'Natura req'},
  {id:'Glowshroom',name:'Glowshroom',tier:3,soil:'netherMushroom',pools:['aFood','aMushroom','aIngredient','aNether','aLight','aGreen'],note:'BoP req',liked:['NETHER','MAGICAL','MUSHROOM']},
  {id:'Liveroot',name:'Liveroot',tier:8,soil:'farmland',pools:['aWood','aTendrilly'],note:'TwilightForest req',liked:['SPOOKY','DENSE']},
  {id:'Steeleafranks',name:'Steeleafranks',tier:10,soil:'stone',blockUnder:'steeleaf',pools:['aMetal','aTendrilly','aIron'],note:'TwilightForest req',liked:['SPOOKY','DEAD']},
];
const MUTS=[
  {out:'BonsaiOak',par:['Wheat','BrownMushroom'],pools:['aTree','aBonsai','aLeafy','aFood','aWood']},
  {out:'BonsaiBirch',par:['BonsaiOak','SugarCane'],pools:['aTree','aBonsai','aLeafy','aWood']},
  {out:'BonsaiSpruce',par:['BonsaiOak','Pumpkin'],pools:['aTree','aBonsai','aLeafy','aWood']},
  {out:'BonsaiDarkOak',par:['BonsaiSpruce','BonsaiOak'],pools:['aTree','aBonsai','aLeafy','aDark','aWood']},
  {out:'BonsaiAcacia',par:['BonsaiOak','Cactus'],pools:['aTree','aBonsai','aLeafy','aWood']},
  {out:'BonsaiJungle',par:['BonsaiOak','Vine'],pools:['aTree','aBonsai','aLeafy','aWood']},
  {out:'BonsaiRubber',par:['BonsaiJungle','BonsaiSpruce'],pools:['aTree','aBonsai','aLeafy','aWood','aSticky']},
  {out:'BonsaiSlimy',par:['Slimeplant','BonsaiJungle','BonsaiRubber'],pools:['aSlime','aBouncy']},
  {out:'Bamboo',par:['BonsaiJungle','Vine'],pools:['aGreen','aPointed','aStem'],note:'BiomesOPlenty req'},
  {out:'Eyebulb',par:['NetherStoneLily','RedTulip'],pools:['aNether','aEvil','aBad'],note:'BiomesOPlenty req'},
  {out:'FloweringVine',par:['OxeyeDaisy','Ivy'],pools:['aGreen','aTendrilly','aFlower','aClimbable'],note:'BiomesOPlenty req'},
  {out:'Glowflower',par:['NetherStoneLily','Dandelion'],pools:['aNether','aLight','aShiny'],note:'BiomesOPlenty req'},
  {out:'GlowingCoral',par:['Glowflower','Waterlily'],pools:['aWater','aLight','aShiny'],note:'BiomesOPlenty req'},
  {out:'Glowshroom',par:['BlueGlowshroom','GreenGlowshroom','PurpleGlowshroom'],pools:['aFood','aMushroom','aIngredient','aNether','aLight','aGreen'],note:'BiomesOPlenty req'},
  {out:'Ivy',par:['Vine','BonsaiSpruce'],pools:['aGreen','aTendrilly','aFlower','aBad','aPoison','aClimbable','aPointed'],note:'BiomesOPlenty req'},
  {out:'Moss',par:['Ivy','FloweringVine'],pools:['aGreen','aClimbable'],note:'BiomesOPlenty req'},
  {out:'Fertilia',par:['Corium','Corpseplant'],pools:['aHealing','aFlower']},
  {out:'Flax',par:['Wheat','AzureBluet'],pools:['aSilk','aTendrilly','aAddictive']},
  {out:'Hemp',par:['Flax','Papyrus'],pools:['aSilk','aGreen','aOrange','aStem','aAddictive']},
  {out:'BoPBerry',par:['Poppy','Blackberry'],pools:['aBerry','aFood','aRed','aIngredient'],note:'BiomesOPlenty req'},
  {out:'Turnip',par:['Potato','BoPBerry'],pools:['aFood','aPurple','aCarrots'],note:'BiomesOPlenty req'},
  {out:'WildCarrot',par:['Carrot','BoPBerry'],pools:['aFood','aWhite','aCarrots'],note:'BiomesOPlenty req'},
  {out:'Barley',par:['Bamboo','Wheat'],pools:['aGreen','aFood','aWheat'],note:'Natura req'},
  {out:'Blackberry',par:['Strawberry','Blueberry'],pools:['aBerry','aFood','aBlack'],note:'Natura req'},
  {out:'Blueberry',par:['AzureBluet','BonsaiOak'],pools:['aBerry','aFood','aBlue'],note:'Natura req'},
  {out:'Maloberry',par:['OrangeTulip','Blueberry'],pools:['aBerry','aFood','aYellow'],note:'Natura req'},
  {out:'Raspberry',par:['RedTulip','OxeyeDaisy'],pools:['aBerry','aFood','aRed'],note:'Natura req'},
  {out:'SaguaroCactus',par:['Cactus','SandLily'],pools:['aGreen','aFood','aCactus','aDanger'],note:'Natura req'},
  {out:'Strawberry',par:['Wheat','Raspberry'],pools:['aBerry','aFood','aRed'],note:'PamsHarvestCraft req'},
  {out:'Chilly',par:['Cactus','Cocoa'],pools:['aFood','aRed','aFire']},
  {out:'Coffee',par:['Cocoa','BonsaiAcacia'],pools:['aLeaves','aIngredient','aBean','aAddictive']},
  {out:'Cucumber',par:['Melon','Carrot'],pools:['aFood','aGreen','aTendrilly']},
  {out:'Grape',par:['Blueberry','Blackberry'],pools:['aFood','aPurple','aClimbable','aTendrilly']},
  {out:'Hops',par:['Hemp','Dandelion'],pools:['aGreen','aIngredient','aWheat']},
  {out:'Huckleberry',par:['Blackberry','Grape'],pools:['aBerry','aFood','aPurple','aLeaves']},
  {out:'Lemon',par:['BonsaiOak','BonsaiAcacia'],pools:['aFood','aYellow','aTree','aLeafy']},
  {out:'Onion',par:['Allium','Carrot'],pools:['aFood','aBrown','aRoot']},
  {out:'SugarBeet',par:['SugarCane','Allium'],pools:['aFood','aWhite','aIngredient','aRoot']},
  {out:'Tea',par:['Blueberry','BonsaiJungle'],pools:['aFood','aGreen','aIngredient'],note:'Natura req'},
  {out:'Tomato',par:['Onion','RedTulip'],pools:['aFood','aRed','aTendrilly']},
  {out:'Dayflower',par:['AzureBluet','BlueOrchid'],pools:['aBlue','aFlower','aAddictive']},
  {out:'Malaxia',par:['OrangeTulip','Pumpkin','StoneLily'],pools:['aOrange','aLeaves','aMetal','aCopper']},
  {out:'Plumbshade',par:['AzureBluet','Malaxia','BlackGraniteLily'],pools:['aDense','aLeaves','aMetal','aLead']},
  {out:'Silviscus',par:['Cassitine','Malaxia','MarbleLily'],pools:['aSilver','aLeaves','aMetal','aSilver']},
  {out:'Cassitine',par:['Malaxia','StoneLily','MarbleLily'],pools:['aShiny','aLeaves','aMetal','aTin']},
  {out:'StickyCane',par:['BonsaiJungle','SugarCane'],pools:['aReed','aSticky','aGreen','aStem']},
  {out:'PurpleTulip',par:['RedTulip','BlueOrchid'],pools:['aPurple','aFlower','aTulip']},
  {out:'Necrobloom',par:['Spidernip','PurpleTulip'],pools:['aPurple','aFlower','aTulip','aPoison','aDanger']},
  {out:'Argentia',par:['Plumbilia','Tine'],pools:['aShiny','aMetal','aSilver']},
  {out:'Auronia',par:['Plumbilia','Coppon'],pools:['aGold','aLeaves','aMetal','aDense']},
  {out:'Bauxia',par:['Galvania','Nickelback'],pools:[],machine:true},
  {out:'BobsYerUncleRanks',par:['Diareed','Olivia'],pools:['aShiny','aTendrilly','aCrystal']},
  {out:'Canola',par:['OxeyeDaisy','Wheat'],pools:['aFood','aYellow','aOil']},
  {out:'Coppon',par:['StoneLily','NetherStoneLily'],pools:['aShiny','aMetal','aCotton','aCopper','aBush']},
  {out:'Diareed',par:['Withereed','EvilOre'],pools:['aFire','aShiny','aReed','aCoal','aCrystal']},
  {out:'EvilOre',par:['NetherStoneLily','SoulSandLily'],pools:['aCrystal','aFire','aNether']},
  {out:'Ferrofern',par:['StoneLily','BlackGraniteLily'],pools:['aGray','aLeaves','aMetal','aIron']},
  {out:'Galvania',par:['Tine','Ferrofern'],pools:['aMetal','aAlloy','aBush']},
  {out:'Thiosulfine',par:['Galvania','Plumbilia'],pools:['aYellow','aFlower','aBad','aSulfur']},
  {out:'Garnydinia',par:['Diareed','RedStraw'],pools:[],machine:true},
  {out:'Glowheat',par:['Glowflower','Wheat'],pools:['aLight','aShiny','aCrystal','aWheat'],note:'BiomesOPlenty req'},
  {out:'GodOfThunder',par:['BobsYerUncleRanks','Withereed'],pools:[],machine:true},
  {out:'Indigo',par:['Dayflower','BlueOrchid'],pools:['aFlower','aBlue','aIngredient']},
  {out:'Iridine',par:['Scheelinium','Platina'],pools:[],machine:true},
  {out:'Lazulia',par:['StoneLily','Indigo'],pools:['aShiny','aBad','aCrystal','aBlue']},
  {out:'Liveroot',par:['Torchberry','BonsaiDarkOak'],pools:['aWood','aTendrilly'],note:'TwilightForest req'},
  {out:'MagicalNightshade',par:['PrimordialBerry','ManaBean','Cinderpearl','Shimmerleaf'],pools:[],machine:true,note:'Thaumcraft+ThaumicTinkerer req'},
  {out:'Micadia',par:['Tine','Bauxia'],pools:[],machine:true},
  {out:'MilkWart',par:['Corium','Netherwart'],pools:['aFood','aMilk','aCow']},
  {out:'Nickelback',par:['Ferrofern','Coppon'],pools:['aMetal','aFire','aAlloy']},
  {out:'OilBerry',par:['SoulSandLily','Withereed'],pools:[],machine:true},
  {out:'Olivia',par:['EndStoneLily','EvilOre'],pools:[],machine:true},
  {out:'Osmianth',par:['Platina','Scheelinium'],pools:[],machine:true},
  {out:'Papyrus',par:['Corium','BonsaiBirch'],pools:['aWhite','aStem']},
  {out:'Platina',par:['Diareed','Rubyne'],pools:[],machine:true},
  {out:'Plumbilia',par:['Coppon','Withereed'],pools:['aMetal','aLead','aReed','aDense']},
  {out:'Pyrolusium',par:['Nickelback','Bauxia'],pools:['aMetal','aBush']},
  {out:'Reactoria',par:['Titania','GodOfThunder'],pools:[],machine:true},
  {out:'RedStraw',par:['NetherStoneLily','Wheat'],pools:['aRed','aStone','aWheat']},
  {out:'Rubyne',par:['RedStraw','Diareed'],pools:['aRed','aCrystal','aShiny']},
  {out:'SaltyRoot',par:['SugarBeet','Canola'],pools:['aGray','aRoot','aSaltpeter']},
  {out:'Sapphirum',par:['EvilOre','Lazulia'],pools:['aCrystal','aShiny','aMetal']},
  {out:'Scheelinium',par:['Titania','Pyrolusium','EndStoneLily'],pools:[],machine:true},
  {out:'SpaceFlower',par:['EndStoneLily','Titania'],pools:[],machine:true},
  {out:'Stargatium',par:['Iridine','Trollplant'],pools:[],machine:true},
  {out:'StarWart',par:['Withereed','Titania','GodOfThunder'],pools:[],machine:true},
  {out:'Steeleafranks',par:['Torchberry','KnightmetalBerry'],pools:['aMetal','aTendrilly','aIron'],note:'TwilightForest req'},
  {out:'Tine',par:['StoneLily','BonsaiSpruce'],pools:['aShiny','aMetal','aPine','aTin','aBush']},
  {out:'Titania',par:['Bauxia','RedStraw'],pools:[],machine:true},
  {out:'Transformium',par:['Trollplant','Bauxia','Titania'],pools:[],machine:true},
  {out:'Trollplant',par:['Goldfish','Reactoria','Fertilia'],pools:[],machine:true,req:'Special machine catalysts required (see source)'},
  {out:'Withereed',par:['BasaltLily','BlackGraniteLily'],pools:['aFire','aUndead','aReed','aCoal','aRotten','aSulfur']},
  {out:'InkBloom',par:['Blackberry','Goldfish'],pools:['aBlack','aFlower','aRose'],note:'Natura req'},
  {out:'Blazereed',par:['SugarCane','Cinderpearl'],pools:['aFire','aBlaze','aReed','aSulfur','aNether'],note:'Thaumcraft req'},
  {out:'Corium',par:['Wheat','Cocoa'],pools:['aCow','aSilk','aTendrilly','aMilk']},
  {out:'Corpseplant',par:['Zomplant','Eyebulb'],pools:['aToxic','aUndead','aTendrilly','aFood','aRotten','aZombie'],note:'BiomesOPlenty req'},
  {out:'Creeperweed',par:['NetherStoneLily','Withereed','SaltyRoot'],pools:['aTendrilly','aFire','aSulfur','aSaltpeter','aCoal']},
  {out:'EggPlant',par:['Corium','OxeyeDaisy'],pools:['aChicken','aFood','aFlower','aAddictive']},
  {out:'Enderbloom',par:['EndStoneLily','Creeperweed'],pools:['aEnder','aFlower','aShiny','aAlien']},
  {out:'Goldfish',par:['Waterlily','WaterArtichoke','Mandrake'],pools:['aNether','aFish','aFood','aBad','aWater'],note:'Witchery req'},
  {out:'Meatrose',par:['Goldfish','EggPlant','Corium'],pools:['aFood','aFlower','aCow','aFish','aChicken','aRose']},
  {out:'Slimeplant',par:['BlueOrchid','ClayLily'],pools:['aSlime','aBouncy','aSticky','aBush']},
  {out:'Spidernip',par:['Flax','Hemp','Zomplant'],pools:['aToxic','aSilk','aFlower','aIngredient','aAddictive']},
  {out:'Tearstalks',par:['Goldfish','SoulSandLily','NetherStoneLily'],pools:['aHealing','aNether','aIngredient','aReed']},
  {out:'Zomplant',par:['Withereed','Eyebulb'],pools:['aZombie','aRotten','aUndead'],note:'BiomesOPlenty req'},
  {out:'Blightberry',par:['Maloberry','Raspberry'],pools:['aBerry','aToxic','aBad','aGreen','aNether','aAddictive'],note:'Natura req'},
  {out:'Duskberry',par:['InkBloom','Blackberry'],pools:['aBerry','aToxic','aBad','aGray','aNether','aAddictive'],note:'Natura req'},
  {out:'Skyberry',par:['Dayflower','Blueberry'],pools:['aBerry','aToxic','aBad','aBlue','aNether','aAddictive'],note:'Natura req'},
  {out:'Stingberry',par:['Thornvine','SaguaroCactus'],pools:['aBerry','aToxic','aBad','aGreen','aNether','aAddictive','aDanger'],note:'Natura req'},
  {out:'Cotton',par:['Flax','Hemp'],pools:['aWhite','aCotton'],note:'Natura req'},
  {out:'Thornvine',par:['Vine','Cactus'],pools:['aNether','aClimbable','aBad','aDanger'],note:'Natura req'},
  {out:'BlueGlowshroom',par:['BlueOrchid','Glowflower'],pools:['aFood','aMushroom','aIngredient','aNether','aLight'],note:'Natura req'},
  {out:'GreenGlowshroom',par:['Cactus','Glowflower'],pools:['aFood','aMushroom','aIngredient','aNether','aLight'],note:'Natura req'},
  {out:'PurpleGlowshroom',par:['Indigo','Glowflower'],pools:['aFood','aMushroom','aIngredient','aNether','aLight'],note:'Natura req'},
  {out:'AluminiumOreBerry',par:['GoldOreBerry','EssenceOreBerry'],pools:['aOreBerry','aAluminium','aMetal','aAluminium','aDanger'],note:'TinkerConstruct req'},
  {out:'ArditeOreBerry',par:['NetherStoneLily','Coppon','CopperOreBerry','Malaxia'],pools:['aOreBerry','aMetal','aOrange','aDanger'],note:'TinkerConstruct req'},
  {out:'CobaltOreBerry',par:['NetherStoneLily','ArditeOreBerry','Lazulia','GoldOreBerry'],pools:['aOreBerry','aMetal','aBlue','aDanger'],note:'TinkerConstruct req'},
  {out:'CopperOreBerry',par:['Malaxia','BoPBerry','StoneLily'],pools:['aOreBerry','aCopper','aMetal','aShiny','aDanger','aOrange'],note:'TinkerConstruct req'},
  {out:'EssenceOreBerry',par:['Creeperweed','Zomplant','Spidernip','Tearstalks'],pools:['aOreBerry','aUndead','aDanger','aGreen'],note:'TinkerConstruct req'},
  {out:'GoldOreBerry',par:['CopperOreBerry','IronOreBerry','TinOreBerry'],pools:['aOreBerry','aGold','aMetal','aDanger','aYellow','aDense'],note:'TinkerConstruct req'},
  {out:'IronOreBerry',par:['TinOreBerry','StoneLily'],pools:['aOreBerry','aGray','aMetal','aDanger','aIron'],note:'TinkerConstruct req'},
  {out:'TinOreBerry',par:['Cassitine','BoPBerry','StoneLily'],pools:['aOreBerry','aTin','aMetal','aShiny','aDanger','aWhite'],note:'TinkerConstruct req'},
  {out:'KnightmetalBerry',par:['IronOreBerry','Torchberry','BonsaiDarkOak'],pools:['aOreBerry','aMetal','aDanger','aGray','aGreen'],note:'TinkerConstruct req'},
  {out:'ThaumiumOreBerry',par:['StoneLily','GoldOreBerry'],pools:['aOreBerry','aMagic','aMetal','aVoid','aDanger','aPurple'],note:'TinkerConstruct req'},
  {out:'VoidOreBerry',par:['ThaumiumOreBerry','GoldOreBerry'],pools:['aOreBerry','aMagic','aMetal','aVoid','aDanger','aBlack'],note:'TinkerConstruct req'},
  {out:'ThauminiteOreBerry',par:['ThaumiumOreBerry','ManaBean'],pools:['aOreBerry','aMagic','aMetal','aVoid','aDanger','aBlue'],note:'TinkerConstruct req'},
  {out:'AndesiteLily',par:['StoneLily','ClayLily'],pools:['aGray','aStone','aMetal'],note:'Botania+Chisel req'},
  {out:'DioriteLily',par:['StoneLily','MarbleLily'],pools:['aWhite','aStone','aShiny'],note:'Botania+Chisel req'},
  {out:'GraniteLily',par:['BlackGraniteLily','RedGraniteLily'],pools:['aRed','aStone','aFire'],note:'Botania+Chisel req'},
  {out:'TuffLily',par:['BlackGraniteLily','AndesiteLily'],pools:['aGray','aStone','aDark'],note:'Botania+Chisel req'},
  {out:'DeepslateLily',par:['TuffLily','BlackGraniteLily'],pools:['aBlack','aStone','aDark'],note:'Botania+Chisel req'},
  {out:'BasaltLily',par:['StoneLily','InkBloom'],pools:['aBlack','aStone','aDark']},
  {out:'BlackGraniteLily',par:['StoneLily','BasaltLily'],pools:['aBlack','aStone','aDark']},
  {out:'ClayLily',par:['StoneLily','Waterlily'],pools:['aGray','aStone','aWater']},
  {out:'EndStoneLily',par:['StoneLily','Enderbloom'],pools:['aYellow','aStone','aAlien','aEnder']},
  {out:'MarbleLily',par:['StoneLily','OxeyeDaisy'],pools:['aWhite','aStone','aShiny']},
  {out:'NetherStoneLily',par:['StoneLily','Netherwart'],pools:['aNether','aStone','aEvil']},
  {out:'RedGraniteLily',par:['StoneLily','Poppy'],pools:['aRed','aStone','aFire']},
  {out:'SandLily',par:['StoneLily','Cactus'],pools:['aYellow','aStone','aCactus']},
  {out:'SoulSandLily',par:['NetherStoneLily','SandLily'],pools:['aNether','aStone','aEvil','aSoulsand','aOil']},
  {out:'StoneLily',par:['Vine','Pumpkin'],pools:['aGray','aStone','aMetal']},
  {out:'Cinderpearl',par:['EmberMoss','GlintWeed'],pools:['aMagic','aBlaze','aNether'],note:'Thaumcraft req'},
  {out:'ManaBean',par:['Cocoa','Cinderpearl','Shimmerleaf'],pools:['aBerry','aBean','aMagic'],note:'Thaumcraft req'},
  {out:'Shimmerleaf',par:['WhiteTulip','RedStraw'],pools:['aMagic','aSilver','aToxic','aShimmer'],note:'Thaumcraft req'},
  {out:'Torchberry',par:['Glowflower','BoPBerry'],pools:['aBerry','aLight','aShimmer'],note:'TwilightForest+BiomesOPlenty req'},
  {out:'Cocoa',par:['Melon','BonsaiJungle'],pools:['aBrown','aFood','aStem']},
  {out:'Melon',par:['Pumpkin','BonsaiJungle'],pools:['aGreen','aFood','aStem']},
  {out:'Pumpkin',par:['Carrot','SugarCane'],pools:['aOrange','aStem']},
  {out:'RedMushroom',par:['Pumpkin','Poppy'],pools:['aRed','aFood','aMushroom']},
  {out:'BrownMushroom',par:['Cocoa','RedMushroom'],pools:['aBrown','aFood','aMushroom']},
  {out:'BlueOrchid',par:['Poppy','Waterlily'],pools:['aFlower','aBlue']},
  {out:'AzureBluet',par:['Poppy','Potato'],pools:['aFlower','aWhite']},
  {out:'RedTulip',par:['Poppy','WhiteTulip'],pools:['aFlower','aRed','aTulip']},
  {out:'OrangeTulip',par:['RedTulip','Dandelion'],pools:['aFlower','aOrange','aTulip']},
  {out:'PinkTulip',par:['RedTulip','WhiteTulip'],pools:['aFlower','aRed','aTulip']},
  {out:'WhiteTulip',par:['PinkTulip','OxeyeDaisy'],pools:['aFlower','aWhite','aTulip']},
  {out:'Allium',par:['PinkTulip','PurpleTulip'],pools:['aFlower','aPurple','aRoot']},
  {out:'OxeyeDaisy',par:['AzureBluet','Dandelion'],pools:['aFlower','aWhite']},
  {out:'Cactus',par:['SugarCane','Potato'],pools:['aGreen','aCactus','aDanger']},
  {out:'SugarCane',par:['Carrot','Potato'],pools:['aReed','aGreen','aFood','aStem']},
  {out:'Netherwart',par:['RedMushroom','BrownMushroom'],pools:['aRed','aNether','aIngredient','aSoulsand']},
  {out:'Vine',par:['Pumpkin','BlueOrchid'],pools:['aGreen','aTendrilly','aClimbable']},
  {out:'Waterlily',par:['Vine','SugarCane'],pools:['aBlue','aWater','aGreen']},
  {out:'Belladonna',par:['PurpleTulip','Huckleberry'],pools:['aPurple','aFlower','aToxic','aIngredient'],note:'Witchery req'},
  {out:'EmberMoss',par:['RedTulip','Moss'],pools:['aFire','aIngredient','aBad','aClimbable'],note:'Witchery req'},
  {out:'Garlic',par:['Onion','Allium'],pools:['aFood','aIngredient','aHealing','aRoot'],note:'Witchery req'},
  {out:'GlintWeed',par:['Vine','EmberMoss'],pools:['aOrange','aFlower','aMagic'],note:'Witchery req'},
  {out:'Mandrake',par:['Carrot','Belladonna'],pools:['aFlower','aMagic','aBad','aToxic','aIngredient'],note:'Witchery req'},
  {out:'Snowbell',par:['Belladonna','GlintWeed'],pools:['aWhite','aFlower','aToxic','aIngredient'],note:'Witchery req'},
  {out:'SpanishMoss',par:['Moss','EmberMoss'],pools:['aGreen','aClimbable','aMagic'],note:'Witchery req'},
  {out:'WaterArtichoke',par:['Waterlily','Hops'],pools:['aFlower','aWater','aBlue','aIngredient'],note:'Witchery req'},
  {out:'Wolfsbane',par:['WaterArtichoke','Belladonna'],pools:['aFlower','aToxic','aPurple','aIngredient'],note:'Witchery req'},
];
const POOL_MAP = {"aYellow":["Canola","Dandelion","EndStoneLily","GoldOreBerry","Lemon","Maloberry","Potato","SandLily","Thiosulfine","Wheat"],"aFood":["Barley","Blackberry","BlueGlowshroom","Blueberry","BoPBerry","BonsaiOak","BrownMushroom","Canola","Carrot","Chilly","Cocoa","Corpseplant","Cucumber","EggPlant","Garlic","Glowshroom","Goldfish","Grape","GreenGlowshroom","Huckleberry","Lemon","Maloberry","Meatrose","Melon","MilkWart","Onion","Potato","PurpleGlowshroom","Raspberry","RedMushroom","SaguaroCactus","Strawberry","SugarBeet","SugarCane","Tea","Tomato","Turnip","Wheat","WildCarrot"],"aWheat":["Barley","Glowheat","Hops","RedStraw","Wheat"],"aOrange":["ArditeOreBerry","Carrot","CopperOreBerry","GlintWeed","Hemp","Malaxia","OrangeTulip","Pumpkin"],"aCarrots":["Carrot","Turnip","WildCarrot"],"aRoot":["Allium","Carrot","Garlic","Onion","Potato","SaltyRoot","SugarBeet"],"aGreen":["Bamboo","Barley","Blightberry","Cactus","Cucumber","EssenceOreBerry","FloweringVine","Glowshroom","Hemp","Hops","Ivy","KnightmetalBerry","Melon","Moss","SaguaroCactus","SpanishMoss","StickyCane","Stingberry","SugarCane","Tea","Vine","Waterlily"],"aStem":["Bamboo","Cocoa","Hemp","Melon","Papyrus","Pumpkin","StickyCane","SugarCane"],"aBrown":["BrownMushroom","Cocoa","Onion"],"aCactus":["Cactus","SaguaroCactus","SandLily"],"aDanger":["AluminiumOreBerry","ArditeOreBerry","Cactus","CobaltOreBerry","CopperOreBerry","EssenceOreBerry","GoldOreBerry","IronOreBerry","KnightmetalBerry","Necrobloom","SaguaroCactus","Stingberry","ThauminiteOreBerry","ThaumiumOreBerry","Thornvine","TinOreBerry","VoidOreBerry"],"aReed":["Blazereed","Diareed","Plumbilia","StickyCane","SugarCane","Tearstalks","Withereed"],"aTendrilly":["BobsYerUncleRanks","Corium","Corpseplant","Creeperweed","Cucumber","Flax","FloweringVine","Grape","Ivy","Liveroot","Steeleafranks","Tomato","Vine"],"aClimbable":["EmberMoss","FloweringVine","Grape","Ivy","Moss","SpanishMoss","Thornvine","Vine"],"aBlue":["BlueOrchid","Blueberry","CobaltOreBerry","Dayflower","Indigo","Lazulia","Skyberry","ThauminiteOreBerry","WaterArtichoke","Waterlily"],"aWater":["ClayLily","GlowingCoral","Goldfish","WaterArtichoke","Waterlily"],"aRed":["BoPBerry","Chilly","GraniteLily","Netherwart","PinkTulip","Poppy","Raspberry","RedGraniteLily","RedMushroom","RedStraw","RedTulip","Rubyne","Strawberry","Tomato"],"aNether":["Blazereed","Blightberry","BlueGlowshroom","Cinderpearl","Duskberry","EvilOre","Eyebulb","Glowflower","Glowshroom","Goldfish","GreenGlowshroom","NetherStoneLily","Netherwart","PurpleGlowshroom","Skyberry","SoulSandLily","Stingberry","Tearstalks","Thornvine"],"aIngredient":["Belladonna","BlueGlowshroom","BoPBerry","Coffee","EmberMoss","Garlic","Glowshroom","GreenGlowshroom","Hops","Indigo","Mandrake","Netherwart","PurpleGlowshroom","Snowbell","Spidernip","SugarBeet","Tea","Tearstalks","WaterArtichoke","Wolfsbane"],"aSoulsand":["Netherwart","SoulSandLily"],"aFlower":["Allium","AzureBluet","Belladonna","BlueOrchid","Dandelion","Dayflower","EggPlant","Enderbloom","Fertilia","FloweringVine","GlintWeed","Indigo","InkBloom","Ivy","Mandrake","Meatrose","Necrobloom","OrangeTulip","OxeyeDaisy","PinkTulip","Poppy","PurpleTulip","RedTulip","Snowbell","Spidernip","Thiosulfine","WaterArtichoke","WhiteTulip","Wolfsbane"],"aRose":["InkBloom","Meatrose","Poppy"],"aWhite":["AzureBluet","Cotton","DioriteLily","MarbleLily","OxeyeDaisy","Papyrus","Snowbell","SugarBeet","TinOreBerry","WhiteTulip","WildCarrot"],"aTulip":["Necrobloom","OrangeTulip","PinkTulip","PurpleTulip","RedTulip","WhiteTulip"],"aPurple":["Allium","Belladonna","Grape","Huckleberry","Necrobloom","PurpleTulip","ThaumiumOreBerry","Turnip","Wolfsbane"],"aMushroom":["BlueGlowshroom","BrownMushroom","Glowshroom","GreenGlowshroom","PurpleGlowshroom","RedMushroom"],"aTree":["BonsaiAcacia","BonsaiBirch","BonsaiDarkOak","BonsaiJungle","BonsaiOak","BonsaiRubber","BonsaiSpruce","Lemon"],"aBonsai":["BonsaiAcacia","BonsaiBirch","BonsaiDarkOak","BonsaiJungle","BonsaiOak","BonsaiRubber","BonsaiSpruce"],"aLeafy":["BonsaiAcacia","BonsaiBirch","BonsaiDarkOak","BonsaiJungle","BonsaiOak","BonsaiRubber","BonsaiSpruce","Lemon"],"aWood":["BonsaiAcacia","BonsaiBirch","BonsaiDarkOak","BonsaiJungle","BonsaiOak","BonsaiRubber","BonsaiSpruce","Liveroot"],"aDark":["BasaltLily","BlackGraniteLily","BonsaiDarkOak","DeepslateLily","TuffLily"],"aSticky":["BonsaiRubber","Slimeplant","StickyCane"],"aSlime":["BonsaiSlimy","Slimeplant"],"aBouncy":["BonsaiSlimy","Slimeplant"],"aGray":["AndesiteLily","ClayLily","Duskberry","Ferrofern","IronOreBerry","KnightmetalBerry","SaltyRoot","StoneLily","TuffLily"],"aStone":["AndesiteLily","BasaltLily","BlackGraniteLily","ClayLily","DeepslateLily","DioriteLily","EndStoneLily","GraniteLily","MarbleLily","NetherStoneLily","RedGraniteLily","RedStraw","SandLily","SoulSandLily","StoneLily","TuffLily"],"aMetal":["AluminiumOreBerry","AndesiteLily","ArditeOreBerry","Argentia","Auronia","Cassitine","CobaltOreBerry","CopperOreBerry","Coppon","Ferrofern","Galvania","GoldOreBerry","IronOreBerry","KnightmetalBerry","Malaxia","Nickelback","Plumbilia","Plumbshade","Pyrolusium","Sapphirum","Silviscus","Steeleafranks","StoneLily","ThauminiteOreBerry","ThaumiumOreBerry","TinOreBerry","Tine","VoidOreBerry"],"aShiny":["Argentia","BobsYerUncleRanks","Cassitine","CopperOreBerry","Coppon","Diareed","DioriteLily","Enderbloom","Glowflower","Glowheat","GlowingCoral","Lazulia","MarbleLily","Rubyne","Sapphirum","TinOreBerry","Tine"],"aBlack":["BasaltLily","BlackGraniteLily","Blackberry","DeepslateLily","InkBloom","VoidOreBerry"],"aFire":["Blazereed","Chilly","Creeperweed","Diareed","EmberMoss","EvilOre","GraniteLily","Nickelback","RedGraniteLily","Withereed"],"aEvil":["Eyebulb","NetherStoneLily","SoulSandLily"],"aOil":["Canola","SoulSandLily"],"aAlien":["EndStoneLily","Enderbloom"],"aEnder":["EndStoneLily","Enderbloom"],"aSilk":["Corium","Flax","Hemp","Spidernip"],"aAddictive":["Blightberry","Coffee","Dayflower","Duskberry","EggPlant","Flax","Hemp","Skyberry","Spidernip","Stingberry"],"aHealing":["Fertilia","Garlic","Tearstalks"],"aPoison":["Ivy","Necrobloom"],"aUndead":["Corpseplant","EssenceOreBerry","Withereed","Zomplant"],"aCoal":["Creeperweed","Diareed","Withereed"],"aRotten":["Corpseplant","Withereed","Zomplant"],"aSulfur":["Blazereed","Creeperweed","Thiosulfine","Withereed"],"aCrystal":["BobsYerUncleRanks","Diareed","EvilOre","Glowheat","Lazulia","Rubyne","Sapphirum"],"aLead":["Plumbilia","Plumbshade"],"aDense":["Auronia","GoldOreBerry","Plumbilia","Plumbshade"],"aPine":["Tine"],"aTin":["Cassitine","TinOreBerry","Tine"],"aBush":["Coppon","Galvania","Pyrolusium","Slimeplant","Tine"],"aLeaves":["Auronia","Cassitine","Coffee","Ferrofern","Huckleberry","Malaxia","Plumbshade","Silviscus"],"aIron":["Ferrofern","IronOreBerry","Steeleafranks"],"aCotton":["Coppon","Cotton"],"aCopper":["CopperOreBerry","Coppon","Malaxia"],"aAlloy":["Galvania","Nickelback"],"aSilver":["Argentia","Shimmerleaf","Silviscus","Silviscus"],"aGold":["Auronia","GoldOreBerry"],"aBad":["Blightberry","Duskberry","EmberMoss","Eyebulb","Goldfish","Ivy","Lazulia","Mandrake","Skyberry","Stingberry","Thiosulfine","Thornvine"],"aLight":["BlueGlowshroom","Glowflower","Glowheat","GlowingCoral","Glowshroom","GreenGlowshroom","PurpleGlowshroom","Torchberry"],"aSaltpeter":["Creeperweed","SaltyRoot"],"aCow":["Corium","Meatrose","MilkWart"],"aMilk":["Corium","MilkWart"],"aChicken":["EggPlant","Meatrose"],"aToxic":["Belladonna","Blightberry","Corpseplant","Duskberry","Mandrake","Shimmerleaf","Skyberry","Snowbell","Spidernip","Stingberry","Wolfsbane"],"aFish":["Goldfish","Meatrose"],"aZombie":["Corpseplant","Zomplant"],"aBean":["Coffee","ManaBean"],"aBerry":["Blackberry","Blightberry","Blueberry","BoPBerry","Duskberry","Huckleberry","Maloberry","ManaBean","Raspberry","Skyberry","Stingberry","Strawberry","Torchberry"],"aMagic":["Cinderpearl","GlintWeed","ManaBean","Mandrake","PrimordialBerry","Shimmerleaf","SpanishMoss","ThauminiteOreBerry","ThaumiumOreBerry","VoidOreBerry"],"aBlaze":["Blazereed","Cinderpearl"],"aShimmer":["Shimmerleaf","Torchberry"],"aPointed":["Bamboo","Ivy"],"aOreBerry":["AluminiumOreBerry","ArditeOreBerry","CobaltOreBerry","CopperOreBerry","EssenceOreBerry","GoldOreBerry","IronOreBerry","KnightmetalBerry","ThauminiteOreBerry","ThaumiumOreBerry","TinOreBerry","VoidOreBerry"],"aAluminium":["AluminiumOreBerry","AluminiumOreBerry"],"aVoid":["ThauminiteOreBerry","ThaumiumOreBerry","VoidOreBerry"]};
const CROP_POOLS = {"Wheat":["aFood","aWheat","aYellow"],"Carrot":["aCarrots","aFood","aOrange","aRoot"],"Potato":["aFood","aRoot","aYellow"],"Melon":["aFood","aGreen","aStem"],"Pumpkin":["aOrange","aStem"],"Cocoa":["aBrown","aFood","aStem"],"Cactus":["aCactus","aDanger","aGreen"],"SugarCane":["aFood","aGreen","aReed","aStem"],"Vine":["aClimbable","aGreen","aTendrilly"],"Waterlily":["aBlue","aGreen","aWater"],"Netherwart":["aIngredient","aNether","aRed","aSoulsand"],"Dandelion":["aFlower","aYellow"],"Poppy":["aFlower","aRed","aRose"],"BlueOrchid":["aBlue","aFlower"],"AzureBluet":["aFlower","aWhite"],"RedTulip":["aFlower","aRed","aTulip"],"OrangeTulip":["aFlower","aOrange","aTulip"],"PinkTulip":["aFlower","aRed","aTulip"],"WhiteTulip":["aFlower","aTulip","aWhite"],"Allium":["aFlower","aPurple","aRoot"],"OxeyeDaisy":["aFlower","aWhite"],"BrownMushroom":["aBrown","aFood","aMushroom"],"RedMushroom":["aFood","aMushroom","aRed"],"BonsaiOak":["aBonsai","aFood","aLeafy","aTree","aWood"],"BonsaiBirch":["aBonsai","aLeafy","aTree","aWood"],"BonsaiSpruce":["aBonsai","aLeafy","aTree","aWood"],"BonsaiDarkOak":["aBonsai","aDark","aLeafy","aTree","aWood"],"BonsaiAcacia":["aBonsai","aLeafy","aTree","aWood"],"BonsaiJungle":["aBonsai","aLeafy","aTree","aWood"],"BonsaiRubber":["aBonsai","aLeafy","aSticky","aTree","aWood"],"BonsaiSlimy":["aBouncy","aSlime"],"StoneLily":["aGray","aMetal","aStone"],"SandLily":["aCactus","aStone","aYellow"],"ClayLily":["aGray","aStone","aWater"],"MarbleLily":["aShiny","aStone","aWhite"],"BasaltLily":["aBlack","aDark","aStone"],"BlackGraniteLily":["aBlack","aDark","aStone"],"RedGraniteLily":["aFire","aRed","aStone"],"NetherStoneLily":["aEvil","aNether","aStone"],"SoulSandLily":["aEvil","aNether","aOil","aSoulsand","aStone"],"EndStoneLily":["aAlien","aEnder","aStone","aYellow"],"StickyCane":["aGreen","aReed","aStem","aSticky"],"Flax":["aAddictive","aSilk","aTendrilly"],"Hemp":["aAddictive","aGreen","aOrange","aSilk","aStem"],"Indigo":["aBlue","aFlower","aIngredient"],"Dayflower":["aAddictive","aBlue","aFlower"],"Canola":["aFood","aOil","aYellow"],"Fertilia":["aFlower","aHealing"],"Papyrus":["aStem","aWhite"],"PurpleTulip":["aFlower","aPurple","aTulip"],"Necrobloom":["aDanger","aFlower","aPoison","aPurple","aTulip"],"RedStraw":["aRed","aStone","aWheat"],"Withereed":["aCoal","aFire","aReed","aRotten","aSulfur","aUndead"],"EvilOre":["aCrystal","aFire","aNether"],"Plumbilia":["aDense","aLead","aMetal","aReed"],"Tine":["aBush","aMetal","aPine","aShiny","aTin"],"Ferrofern":["aGray","aIron","aLeaves","aMetal"],"Coppon":["aBush","aCopper","aCotton","aMetal","aShiny"],"Nickelback":["aAlloy","aFire","aMetal"],"Galvania":["aAlloy","aBush","aMetal"],"Malaxia":["aCopper","aLeaves","aMetal","aOrange"],"Cassitine":["aLeaves","aMetal","aShiny","aTin"],"Plumbshade":["aDense","aLead","aLeaves","aMetal"],"Silviscus":["aLeaves","aMetal","aSilver","aSilver"],"Argentia":["aMetal","aShiny","aSilver"],"Auronia":["aDense","aGold","aLeaves","aMetal"],"Thiosulfine":["aBad","aFlower","aSulfur","aYellow"],"Pyrolusium":["aBush","aMetal"],"Lazulia":["aBad","aBlue","aCrystal","aShiny"],"Rubyne":["aCrystal","aRed","aShiny"],"Sapphirum":["aCrystal","aMetal","aShiny"],"BobsYerUncleRanks":["aCrystal","aShiny","aTendrilly"],"Diareed":["aCoal","aCrystal","aFire","aReed","aShiny"],"Glowheat":["aCrystal","aLight","aShiny","aWheat"],"SaltyRoot":["aGray","aRoot","aSaltpeter"],"Corium":["aCow","aMilk","aSilk","aTendrilly"],"EggPlant":["aAddictive","aChicken","aFlower","aFood"],"Creeperweed":["aCoal","aFire","aSaltpeter","aSulfur","aTendrilly"],"Spidernip":["aAddictive","aFlower","aIngredient","aSilk","aToxic"],"InkBloom":["aBlack","aFlower","aRose"],"Slimeplant":["aBouncy","aBush","aSlime","aSticky"],"Goldfish":["aBad","aFish","aFood","aNether","aWater"],"Enderbloom":["aAlien","aEnder","aFlower","aShiny"],"Zomplant":["aRotten","aUndead","aZombie"],"Corpseplant":["aFood","aRotten","aTendrilly","aToxic","aUndead","aZombie"],"Tearstalks":["aHealing","aIngredient","aNether","aReed"],"MilkWart":["aCow","aFood","aMilk"],"Meatrose":["aChicken","aCow","aFish","aFlower","aFood","aRose"],"Lemon":["aFood","aLeafy","aTree","aYellow"],"Onion":["aBrown","aFood","aRoot"],"SugarBeet":["aFood","aIngredient","aRoot","aWhite"],"Tomato":["aFood","aRed","aTendrilly"],"Cucumber":["aFood","aGreen","aTendrilly"],"Chilly":["aFire","aFood","aRed"],"Coffee":["aAddictive","aBean","aIngredient","aLeaves"],"Hops":["aGreen","aIngredient","aWheat"],"Strawberry":["aBerry","aFood","aRed"],"Blueberry":["aBerry","aBlue","aFood"],"Blackberry":["aBerry","aBlack","aFood"],"Raspberry":["aBerry","aFood","aRed"],"Grape":["aClimbable","aFood","aPurple","aTendrilly"],"Huckleberry":["aBerry","aFood","aLeaves","aPurple"],"Maloberry":["aBerry","aFood","aYellow"],"Cotton":["aCotton","aWhite"],"ManaBean":["aBean","aBerry","aMagic"],"Cinderpearl":["aBlaze","aMagic","aNether"],"Shimmerleaf":["aMagic","aShimmer","aSilver","aToxic"],"PrimordialBerry":["aMagic"],"Eyebulb":["aBad","aEvil","aNether"],"Glowflower":["aLight","aNether","aShiny"],"Bamboo":["aGreen","aPointed","aStem"],"FloweringVine":["aClimbable","aFlower","aGreen","aTendrilly"],"GlowingCoral":["aLight","aShiny","aWater"],"Ivy":["aBad","aClimbable","aFlower","aGreen","aPointed","aPoison","aTendrilly"],"Moss":["aClimbable","aGreen"],"Blightberry":["aAddictive","aBad","aBerry","aGreen","aNether","aToxic"],"Duskberry":["aAddictive","aBad","aBerry","aGray","aNether","aToxic"],"Skyberry":["aAddictive","aBad","aBerry","aBlue","aNether","aToxic"],"Stingberry":["aAddictive","aBad","aBerry","aDanger","aGreen","aNether","aToxic"],"Thornvine":["aBad","aClimbable","aDanger","aNether"],"WaterArtichoke":["aBlue","aFlower","aIngredient","aWater"],"Mandrake":["aBad","aFlower","aIngredient","aMagic","aToxic"],"Belladonna":["aFlower","aIngredient","aPurple","aToxic"],"Garlic":["aFood","aHealing","aIngredient","aRoot"],"GlintWeed":["aFlower","aMagic","aOrange"],"Snowbell":["aFlower","aIngredient","aToxic","aWhite"],"Wolfsbane":["aFlower","aIngredient","aPurple","aToxic"],"EmberMoss":["aBad","aClimbable","aFire","aIngredient"],"SpanishMoss":["aClimbable","aGreen","aMagic"],"Torchberry":["aBerry","aLight","aShimmer"],"BoPBerry":["aBerry","aFood","aIngredient","aRed"],"Turnip":["aCarrots","aFood","aPurple"],"WildCarrot":["aCarrots","aFood","aWhite"],"Barley":["aFood","aGreen","aWheat"],"Blazereed":["aBlaze","aFire","aNether","aReed","aSulfur"],"SaguaroCactus":["aCactus","aDanger","aFood","aGreen"],"Tea":["aFood","aGreen","aIngredient"],"IronOreBerry":["aDanger","aGray","aIron","aMetal","aOreBerry"],"GoldOreBerry":["aDanger","aDense","aGold","aMetal","aOreBerry","aYellow"],"CopperOreBerry":["aCopper","aDanger","aMetal","aOrange","aOreBerry","aShiny"],"TinOreBerry":["aDanger","aMetal","aOreBerry","aShiny","aTin","aWhite"],"AluminiumOreBerry":["aAluminium","aAluminium","aDanger","aMetal","aOreBerry"],"EssenceOreBerry":["aDanger","aGreen","aOreBerry","aUndead"],"ArditeOreBerry":["aDanger","aMetal","aOrange","aOreBerry"],"CobaltOreBerry":["aBlue","aDanger","aMetal","aOreBerry"],"ThaumiumOreBerry":["aDanger","aMagic","aMetal","aOreBerry","aPurple","aVoid"],"ThauminiteOreBerry":["aBlue","aDanger","aMagic","aMetal","aOreBerry","aVoid"],"VoidOreBerry":["aBlack","aDanger","aMagic","aMetal","aOreBerry","aVoid"],"KnightmetalBerry":["aDanger","aGray","aGreen","aMetal","aOreBerry"],"AndesiteLily":["aGray","aMetal","aStone"],"DioriteLily":["aShiny","aStone","aWhite"],"GraniteLily":["aFire","aRed","aStone"],"TuffLily":["aDark","aGray","aStone"],"DeepslateLily":["aBlack","aDark","aStone"],"BlueGlowshroom":["aFood","aIngredient","aLight","aMushroom","aNether"],"GreenGlowshroom":["aFood","aIngredient","aLight","aMushroom","aNether"],"PurpleGlowshroom":["aFood","aIngredient","aLight","aMushroom","aNether"],"Glowshroom":["aFood","aGreen","aIngredient","aLight","aMushroom","aNether"],"Liveroot":["aTendrilly","aWood"],"Steeleafranks":["aIron","aMetal","aTendrilly"]};

const DIRECT_POOL_REGISTRATIONS = {"Wheat":["aYellow","aFood","aWheat"],"Carrot":["aOrange","aFood","aCarrots","aRoot"],"Potato":["aYellow","aFood","aRoot"],"Dandelion":["aFlower","aYellow"],"Poppy":["aRed","aFlower","aRose"]};


// Biome tags and rainfall — verified against GTNH biome table
const BIOMES={
  "Ocean":["OCEAN"],
  "Plains":["PLAINS"],
  "Desert":["HOT","DRY","SANDY"],
  "Extreme Hills":["MOUNTAIN","HILLS"],
  "Forest":["FOREST"],
  "Taiga":["COLD","CONIFEROUS","FOREST"],
  "Swampland":["WET","SWAMP"],
  "River":["RIVER"],
  "Hell":["HOT","DRY","NETHER"],
  "Sky":["COLD","DRY","END"],
  "FrozenOcean":["COLD","OCEAN","SNOWY"],
  "FrozenRiver":["COLD","RIVER","SNOWY"],
  "Ice Plains":["COLD","SNOWY","WASTELAND"],
  "Ice Mountains":["COLD","MOUNTAIN","SNOWY"],
  "MushroomIsland":["MUSHROOM"],
  "MushroomIslandShore":["MUSHROOM","BEACH"],
  "Beach":["BEACH"],
  "DesertHills":["HOT","DRY","HILLS","SANDY"],
  "ForestHills":["FOREST","HILLS"],
  "TaigaHills":["COLD","CONIFEROUS","FOREST","HILLS"],
  "Extreme Hills Edge":["MOUNTAIN"],
  "Jungle":["HOT","DENSE","WET","JUNGLE"],
  "JungleHills":["HOT","DENSE","WET","JUNGLE","HILLS"],
  "JungleEdge":["HOT","WET","JUNGLE","FOREST"],
  "Deep Ocean":["OCEAN"],
  "Stone Beach":["BEACH"],
  "Cold Beach":["COLD","SNOWY","BEACH"],
  "Birch Forest":["FOREST"],
  "Birch Forest Hills":["FOREST","HILLS"],
  "Roofed Forest":["DENSE","SPOOKY","FOREST"],
  "Cold Taiga":["COLD","CONIFEROUS","FOREST","SNOWY"],
  "Cold Taiga Hills":["COLD","CONIFEROUS","FOREST","HILLS","SNOWY"],
  "Mega Taiga":["COLD","CONIFEROUS","FOREST"],
  "Mega Taiga Hills":["COLD","CONIFEROUS","FOREST","HILLS"],
  "Extreme Hills+":["SPARSE","FOREST","MOUNTAIN"],
  "Savanna":["HOT","SPARSE","SAVANNA","PLAINS"],
  "Savanna Plateau":["HOT","SPARSE","SAVANNA","PLAINS"],
  "Mesa":["MESA","SANDY"],
  "Mesa Plateau F":["SPARSE","MESA","SANDY"],
  "Mesa Plateau":["MESA","SANDY"],
  "Alps Forest":["COLD","FOREST","MOUNTAIN","SNOWY"],
  "Alps":["COLD","MOUNTAIN","SNOWY"],
  "Arctic":["COLD","DEAD","SNOWY","WASTELAND"],
  "Bamboo Forest":["DENSE","JUNGLE","LUSH","FOREST"],
  "Bayou":["WET","LUSH","OCEAN","RIVER","SWAMP"],
  "Bog":["WET","DEAD","FOREST","SWAMP"],
  "Boreal Forest":["DENSE","CONIFEROUS","LUSH","FOREST"],
  "Brushland":["HOT","DRY","SAVANNA","PLAINS"],
  "Canyon":["HOT","SPARSE","DRY","MOUNTAIN","HILLS","SANDY"],
  "Canyon Ravine":["HOT","DRY","HILLS","SANDY"],
  "Chaparral":["SPARSE","PLAINS"],
  "Cherry Blossom Grove":["LUSH","MAGICAL","FOREST"],
  "Coniferous Forest":["DENSE","CONIFEROUS","FOREST","HILLS"],
  "Coral Reef":["OCEAN","RIVER"],
  "Crag":["DRY","SPOOKY","DEAD","MOUNTAIN","WASTELAND"],
  "Dead Forest":["SPARSE","SPOOKY","DEAD","FOREST"],
  "Dead Swamp":["SPARSE","SPOOKY","DEAD","SWAMP"],
  "Deciduous Forest":["DENSE","DRY","FOREST"],
  "Dry River":["HOT","DRY","PLAINS","SANDY"],
  "Eucalyptus Forest":["HOT","WET","PLAINS"],
  "Fen":["WET","DEAD","FOREST","SWAMP"],
  "Flower Field":["LUSH","PLAINS"],
  "Frost Forest":["COLD","SPARSE","FOREST","SNOWY"],
  "Fungi Forest":["WET","LUSH","MUSHROOM","MAGICAL","FOREST","SWAMP"],
  "Garden":["LUSH","MAGICAL","PLAINS"],
  "Glacier":["COLD","DEAD","HILLS","SNOWY"],
  "Grassland":["SPARSE","LUSH","PLAINS","HILLS","SWAMP"],
  "Grove":["DENSE","LUSH","FOREST","PLAINS"],
  "Heathland":["DRY","SAVANNA","PLAINS"],
  "Highland":["SPARSE","MOUNTAIN","HILLS"],
  "Jade Cliffs":["DENSE","FOREST","MOUNTAIN"],
  "Kelp Forest":["OCEAN","RIVER","FOREST"],
  "Land of Lakes":["WET","PLAINS"],
  "Land of Lakes Marsh":["WET","SWAMP"],
  "Lavender Fields":["SPARSE","LUSH","PLAINS"],
  "Lush Desert":["HOT","DRY","SAVANNA","LUSH","SANDY"],
  "Lush River":["RIVER","PLAINS"],
  "Lush Swamp":["WET","LUSH","OCEAN","RIVER","SWAMP"],
  "Mangrove":["WET","LUSH","OCEAN","RIVER","FOREST"],
  "Maple Woods":["COLD","FOREST"],
  "Marsh":["SPARSE","WET","LUSH","OCEAN","RIVER","SWAMP"],
  "Meadow Forest":["LUSH","FOREST","PLAINS"],
  "Meadow":["LUSH","FOREST","PLAINS"],
  "Moor":["SPARSE","WET","HILLS","SWAMP"],
  "Mountain":["DRY","FOREST","MOUNTAIN"],
  "Mystic Grove":["WET","LUSH","MAGICAL","FOREST"],
  "Oasis":["HOT","DRY","JUNGLE","LUSH","SANDY"],
  "Ominous Woods":["SPOOKY","DEAD","MAGICAL","FOREST","SWAMP"],
  "Orchard":["SPARSE","LUSH","FOREST","PLAINS"],
  "Origin Valley":["PLAINS"],
  "Outback":["HOT","DRY","SAVANNA","PLAINS","SANDY"],
  "Polar Chasm":["HOT","DRY","SAVANNA","PLAINS"],
  "Prairie":["SPARSE","DRY","PLAINS"],
  "Quagmire":["WET","SPOOKY","DEAD","SWAMP","WASTELAND"],
  "Rainforest":["DENSE","WET","JUNGLE","LUSH","FOREST","HILLS"],
  "Redwood Forest":["DENSE","CONIFEROUS","FOREST"],
  "Sacred Springs":["DENSE","WET","LUSH","MAGICAL","FOREST","MOUNTAIN"],
  "Scrubland":["HOT","SPARSE","DRY","SAVANNA","PLAINS"],
  "Seasonal Forest Clearing":["PLAINS"],
  "Seasonal Forest":["DENSE","LUSH","FOREST"],
  "Shield":["WET","CONIFEROUS","OCEAN","RIVER","FOREST"],
  "Shrubland":["SPARSE","DRY","PLAINS"],
  "Silkglades":["SPOOKY","DEAD","FOREST","SWAMP"],
  "Sludgepit":["WET","SPOOKY","DEAD","FOREST","SWAMP","WASTELAND"],
  "Snowy Coniferous Forest":["COLD","DENSE","CONIFEROUS","FOREST","HILLS","SNOWY"],
  "Spectral Garden":["HOT","DRY","SAVANNA","PLAINS"],
  "Spruce Woods":["DENSE","CONIFEROUS","LUSH","FOREST"],
  "Steppe":["HOT","SPARSE","DRY","SAVANNA","DEAD","PLAINS","SANDY"],
  "Temperate Rainforest":["WET","CONIFEROUS","LUSH","FOREST","HILLS"],
  "Thicket":["DENSE","DRY","DEAD","FOREST","PLAINS"],
  "Tropical Rainforest":["HOT","DENSE","WET","JUNGLE","LUSH"],
  "Tropics":["WET","JUNGLE","LUSH","OCEAN","RIVER","BEACH"],
  "Tundra":["COLD","SPARSE","DRY","DEAD","WASTELAND"],
  "Visceral Heap":["SPOOKY","NETHER"],
  "Volcano":["HOT","DRY","MOUNTAIN","WASTELAND"],
  "Wasteland":["SPARSE","SPOOKY","DEAD","WASTELAND"],
  "Wetland":["DENSE","WET","LUSH","FOREST","SWAMP"],
  "Woodland":["DENSE","DRY","FOREST"],
  "Xeric Shrubland":["HOT","PLAINS","SANDY"],
  "Dense Forest":["PLAINS"],
  "Ocean Oil Field":["OCEAN","RIVER"],
  "Desert Oil Field":["SANDY"],
  "Boneyard":["SPOOKY","NETHER","WASTELAND"],
  "Sunflower Plains":["PLAINS"],
  "Desert M":["HOT","DRY","PLAINS","SANDY"],
  "Extreme Hills M":["HILLS"],
  "Flower Forest":["FOREST","HILLS"],
  "Taiga M":["HILLS"],
  "Swampland M":["WET","SWAMP"],
  "Corrupted Sands":["SPOOKY","NETHER","SANDY"],
  "Phantasmagoric Inferno":["SPOOKY","NETHER"],
  "Undergarden":["JUNGLE","SPOOKY","NETHER"],
  "Ice Plains Spikes":["COLD","HILLS","SNOWY"],
  "moon":["COLD","DRY","DEAD"],
  "marsFlat":["COLD","DRY","DEAD","SANDY"],
  "asteroids":["COLD","DRY","SPOOKY","DEAD"],
  "space":["DRY","PLAINS"],
  "Jungle M":["HOT","WET","HILLS"],
  "JungleEdge M":["HOT","HILLS"],
  "Birch Forest M":["HILLS"],
  "Birch Forest Hills M":["HILLS"],
  "Roofed Forest M":["HILLS"],
  "Cold Taiga M":["COLD","HILLS","SNOWY"],
  "Mega Spruce Taiga":["DENSE","FOREST"],
  "Mega Spruce Taiga 2":["DENSE","FOREST"],
  "Extreme Hills+ M":["HILLS"],
  "Savanna M":["HOT","SPARSE","DRY","SAVANNA","HILLS"],
  "Savanna Plateau M":["HOT","SPARSE","DRY","SAVANNA","HILLS"],
  "Mesa (Bryce)":["HOT","DRY","PLAINS","SANDY"],
  "Mesa Plateau F M":["HOT","DRY","FOREST","SANDY"],
  "Mesa Plateau M":["HOT","DRY","PLAINS","SANDY"],
  "Twilight Clearing":["SPARSE","PLAINS"],
  "Dark Forest":["DENSE","SPOOKY","FOREST"],
  "Dark Forest Center":["DENSE","SPOOKY","MAGICAL","FOREST"],
  "Deep Mushroom Forest":["MUSHROOM","FOREST"],
  "Fire Swamp":["HOT","SWAMP","WASTELAND"],
  "Twilight Glacier":["COLD","SNOWY","WASTELAND"],
  "Twilight Highlands":["CONIFEROUS","FOREST","MOUNTAIN"],
  "Highlands Center":["DRY","DEAD","MESA","WASTELAND"],
  "Twilight Lake":["OCEAN"],
  "Firefly Forest":["LUSH","FOREST"],
  "Mushroom Forest":["MUSHROOM","FOREST"],
  "Oak Savanna":["SPARSE","FOREST"],
  "Twilight Stream":["RIVER"],
  "Twilight Swamp":["WET","SWAMP"],
  "Thornlands":["DRY","DEAD","HILLS","WASTELAND"],
  "Twilight Forest":["FOREST"],
  "Dense Twilight Forest":["DENSE","FOREST"],
  "Enchanted Forest":["MAGICAL","FOREST"],
  "Eerie":["SPOOKY","MAGICAL"],
  "Eldritch":["SPOOKY","END","MAGICAL"],
  "Magical Forest":["MAGICAL","FOREST"],
  "Tainted Land":["MAGICAL","WASTELAND"],
  "Snowy Forest":["COLD","CONIFEROUS","FOREST","SNOWY"],
  "Toxic Everglades":["DENSE","DEAD","FOREST","HILLS"],
  "rwg_riverIce":["COLD","RIVER","SNOWY"],
  "rwg_riverCold":["COLD","CONIFEROUS","RIVER","FOREST"],
  "rwg_riverTemperate":["COLD","RIVER","FOREST"],
  "rwg_riverHot":["HOT","DRY","RIVER","SANDY"],
  "rwg_riverWet":["HOT","WET","JUNGLE","RIVER"],
  "rwg_riverOasis":["HOT","WET","JUNGLE","RIVER"],
  "rwg_oceanIce":["COLD","OCEAN","SNOWY","BEACH"],
  "rwg_oceanCold":["COLD","CONIFEROUS","OCEAN","FOREST","BEACH"],
  "rwg_oceanTemperate":["COLD","OCEAN","FOREST","BEACH"],
  "rwg_oceanHot":["HOT","DRY","OCEAN","SANDY","BEACH"],
  "rwg_oceanOasis":["HOT","WET","JUNGLE","OCEAN","BEACH"],
  "rwg_snowDesert":["COLD","SNOWY","WASTELAND"],
  "rwg_coldPlains":["COLD","WASTELAND"],
  "rwg_coldForest":["COLD","DENSE","CONIFEROUS","FOREST","HILLS"],
  "rwg_hotPlains":["HOT","SPARSE","SAVANNA","PLAINS"],
  "rwg_hotForest":["HOT","SPARSE","SAVANNA","PLAINS"],
  "rwg_hotDesert":["HOT","DRY","SANDY"],
  "rwg_plains":["PLAINS"],
  "rwg_tropical":["HOT","WET","JUNGLE"],
  "rwg_redwood":["COLD","CONIFEROUS","FOREST"],
  "rwg_jungle":["HOT","WET","JUNGLE"],
  "rwg_oasis":["HOT","WET","PLAINS"],
  "rwg_temperateForest":["PLAINS"],
  "rwg_oceanWet":["HOT","WET","JUNGLE","OCEAN","BEACH"],
};
const BIOME_RAINFALL={"Ocean":0.5,"Plains":0.4,"Desert":0.0,"Extreme Hills":0.3,"Forest":0.8,"Taiga":0.8,"Swampland":0.9,"River":0.5,"Hell":0.0,"Sky":0.5,"FrozenOcean":0.5,"FrozenRiver":0.5,"Ice Plains":0.5,"Ice Mountains":0.5,"MushroomIsland":1.0,"MushroomIslandShore":1.0,"Beach":0.4,"DesertHills":0.0,"ForestHills":0.8,"TaigaHills":0.8,"Extreme Hills Edge":0.3,"Jungle":0.9,"JungleHills":0.9,"JungleEdge":0.8,"Deep Ocean":0.5,"Stone Beach":0.3,"Cold Beach":0.3,"Birch Forest":0.6,"Birch Forest Hills":0.6,"Roofed Forest":0.8,"Cold Taiga":0.4,"Cold Taiga Hills":0.4,"Mega Taiga":0.8,"Mega Taiga Hills":0.8,"Extreme Hills+":0.3,"Savanna":0.0,"Savanna Plateau":0.0,"Mesa":0.0,"Mesa Plateau F":0.0,"Mesa Plateau":0.0,"Alps Forest":0.5,"Alps":0.5,"Arctic":0.5,"Bamboo Forest":0.9,"Bayou":0.9,"Bog":0.9,"Boreal Forest":0.6,"Brushland":0.1,"Canyon":0.3,"Canyon Ravine":0.3,"Chaparral":0.6,"Cherry Blossom Grove":0.8,"Coniferous Forest":0.5,"Coral Reef":0.9,"Crag":0.0,"Dead Forest":0.3,"Dead Swamp":0.9,"Deciduous Forest":0.8,"Dry River":0.0,"Eucalyptus Forest":1.0,"Fen":0.4,"Flower Field":0.7,"Frost Forest":0.5,"Fungi Forest":1.0,"Garden":0.8,"Glacier":0.2,"Grassland":0.7,"Grove":0.8,"Heathland":0.2,"Highland":0.8,"Jade Cliffs":0.9,"Kelp Forest":0.9,"Land of Lakes":0.9,"Land of Lakes Marsh":0.9,"Lavender Fields":0.7,"Lush Desert":0.5,"Lush River":0.8,"Lush Swamp":1.0,"Mangrove":0.9,"Maple Woods":0.8,"Marsh":0.9,"Meadow Forest":0.7,"Meadow":0.7,"Moor":1.0,"Mountain":0.1,"Mystic Grove":1.0,"Oasis":0.3,"Ominous Woods":0.9,"Orchard":0.7,"Origin Valley":0.8,"Outback":0.05,"Polar Chasm":0.0,"Prairie":0.3,"Quagmire":0.9,"Rainforest":1.0,"Redwood Forest":0.7,"Sacred Springs":0.5,"Scrubland":0.0,"Seasonal Forest Clearing":0.8,"Seasonal Forest":0.8,"Shield":0.8,"Shrubland":0.05,"Silkglades":0.9,"Sludgepit":0.9,"Snowy Coniferous Forest":0.5,"Spectral Garden":0.0,"Spruce Woods":0.8,"Steppe":0.05,"Temperate Rainforest":1.2,"Thicket":0.2,"Tropical Rainforest":1.0,"Tropics":1.0,"Tundra":0.5,"Visceral Heap":0.0,"Volcano":0.05,"Wasteland":0.05,"Wetland":0.9,"Woodland":0.4,"Xeric Shrubland":0.2,"Dense Forest":0.7,"Ocean Oil Field":0.5,"Desert Oil Field":0.0,"Boneyard":0.0,"Sunflower Plains":0.4,"Desert M":0.0,"Extreme Hills M":0.3,"Flower Forest":0.8,"Taiga M":0.8,"Swampland M":0.9,"Corrupted Sands":0.0,"Phantasmagoric Inferno":0.0,"Undergarden":0.0,"Ice Plains Spikes":0.5,"moon":0.0,"marsFlat":0.0,"asteroids":0.0,"space":0.0,"Jungle M":0.9,"JungleEdge M":0.8,"Birch Forest M":0.6,"Birch Forest Hills M":0.6,"Roofed Forest M":0.8,"Cold Taiga M":0.4,"Mega Spruce Taiga":0.8,"Mega Spruce Taiga 2":0.8,"Extreme Hills+ M":0.3,"Savanna M":0.0,"Savanna Plateau M":0.0,"Mesa (Bryce)":0.0,"Mesa Plateau F M":0.0,"Mesa Plateau M":0.0,"Twilight Clearing":0.4,"Dark Forest":0.8,"Dark Forest Center":0.8,"Deep Mushroom Forest":1.0,"Fire Swamp":0.4,"Twilight Glacier":0.1,"Twilight Highlands":0.7,"Highlands Center":0.2,"Twilight Lake":1.0,"Firefly Forest":1.0,"Mushroom Forest":0.8,"Oak Savanna":0.0,"Twilight Stream":1.0,"Twilight Swamp":0.9,"Thornlands":0.2,"Twilight Forest":0.5,"Dense Twilight Forest":0.8,"Enchanted Forest":0.5,"Eerie":0.5,"Eldritch":0.5,"Magical Forest":0.6,"Tainted Land":0.5,"Snowy Forest":0.9,"Toxic Everglades":0.7,"rwg_riverIce":0.1,"rwg_riverCold":0.4,"rwg_riverTemperate":0.6,"rwg_riverHot":0.2,"rwg_riverWet":0.9,"rwg_riverOasis":0.9,"rwg_oceanIce":0.1,"rwg_oceanCold":0.4,"rwg_oceanTemperate":0.6,"rwg_oceanHot":0.2,"rwg_oceanOasis":0.9,"rwg_snowDesert":0.1,"rwg_coldPlains":0.2,"rwg_coldForest":0.4,"rwg_hotPlains":0.1,"rwg_hotForest":0.2,"rwg_hotDesert":0.0,"rwg_plains":0.4,"rwg_tropical":0.8,"rwg_redwood":0.6,"rwg_jungle":0.9,"rwg_oasis":0.9,"rwg_temperateForest":0.6,"rwg_oceanWet":0.9};
